### PR TITLE
etcdutl: Fix snapshot restore memory alloc issue

### LINKED ISSUE #16052: etcdutl snapshot restore cannot allocate memory
### Bug report criteria

- [X] This bug report is not security related, security issues should be disclosed privately via security@etcd.io.
- [X] This is not a support request, support requests should be raised in the etcd [discussion forums](https://github.com/etcd-io/etcd/discussions).
- [X] You have read the etcd [bug reporting guidelines](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/reporting_bugs.md).
- [X] Existing open issues along with etcd [frequently asked questions](https://etcd.io/docs/latest/faq) have been checked and this is not a duplicate.

### What happened?

etcdutl crashs when I restore db from snapshot in the container.

```
2023-06-09T12:07:38Z	panic	backend/backend.go:186	failed to open database	{"path": "/tmp/etcd/member/snap/db", "error": "cannot allocate memory"}
```

### What did you expect to happen?

.

### How can we reproduce it (as minimally and precisely as possible)?

restore db in not enough memory container

### Anything else we need to know?

_No response_

### Etcd version (please run commands below)

<details>

```console
# Copied from github release
$ etcdutl version
etcdutl version: 3.5.7
API version: 3.5

# I builded from main branch
$ ./etcdutl version
etcdutl version: 3.6.0-alpha.0
API version: 3.6

```

</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

### Relevant log output

```Shell
ETCDCTL_API=3 ./etcdutl snapshot restore --skip-hash-check=true --data-dir=/tmp/etcd --name=etc02 --initial-cluster=etc01=http://10.88.0.19:2380,etc03=http://10.88.0.21:2380,etc02=http://10.88.0.20:2380 --initial-advertise-peer-urls=http://10.88.0.20:2380 /root/snap.db

2023-06-09T12:07:38Z	info	snapshot/v3_snapshot.go:257	restoring snapshot	{"path": "/root/snap.db", "wal-dir": "/tmp/etcd/member/wal", "data-dir": "/tmp/etcd", "snap-dir": "/tmp/etcd/member/snap"}
2023-06-09T12:07:38Z	panic	backend/backend.go:186	failed to open database	{"path": "/tmp/etcd/member/snap/db", "error": "cannot allocate memory"}
go.etcd.io/etcd/server/v3/storage/backend.newBackend
	go.etcd.io/etcd/server/v3@v3.6.0-alpha.0/storage/backend/backend.go:186
go.etcd.io/etcd/server/v3/storage/backend.NewDefaultBackend
	go.etcd.io/etcd/server/v3@v3.6.0-alpha.0/storage/backend/backend.go:170
go.etcd.io/etcd/etcdutl/v3/snapshot.(*v3Manager).saveDB
	go.etcd.io/etcd/etcdutl/v3/snapshot/v3_snapshot.go:303
go.etcd.io/etcd/etcdutl/v3/snapshot.(*v3Manager).Restore
	go.etcd.io/etcd/etcdutl/v3/snapshot/v3_snapshot.go:265
go.etcd.io/etcd/etcdutl/v3/etcdutl.SnapshotRestoreCommandFunc
	go.etcd.io/etcd/etcdutl/v3/etcdutl/snapshot_command.go:132
go.etcd.io/etcd/etcdutl/v3/etcdutl.snapshotRestoreCommandFunc
	go.etcd.io/etcd/etcdutl/v3/etcdutl/snapshot_command.go:102
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.7.0/command.go:944
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.7.0/command.go:1068
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.7.0/command.go:992
main.Start
	go.etcd.io/etcd/etcdutl/v3/ctl.go:56
main.main
	go.etcd.io/etcd/etcdutl/v3/main.go:23
runtime.main
	runtime/proc.go:250
panic: failed to open database

goroutine 1 [running]:
go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x2?, 0x2?, {0x0?, 0x0?, 0xc0006246c0?})
	go.uber.org/zap@v1.24.0/zapcore/entry.go:198 +0x65
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc00064cb60, {0xc0001c6600, 0x2, 0x2})
	go.uber.org/zap@v1.24.0/zapcore/entry.go:264 +0x3ec
go.uber.org/zap.(*Logger).Panic(0xc00048e318?, {0xbc27c8?, 0xa3dc06?}, {0xc0001c6600, 0x2, 0x2})
	go.uber.org/zap@v1.24.0/logger.go:258 +0x59
go.etcd.io/etcd/server/v3/storage/backend.newBackend({{0xc00048e318, 0x18}, 0x5f5e100, 0x2710, {0x0, 0x0}, 0x280000000, 0xc000652f50, 0x0, 0x0, ...})
	go.etcd.io/etcd/server/v3@v3.6.0-alpha.0/storage/backend/backend.go:186 +0x2ff
go.etcd.io/etcd/server/v3/storage/backend.NewDefaultBackend(0xc0005df110?, {0xc00048e318?, 0x1?})
	go.etcd.io/etcd/server/v3@v3.6.0-alpha.0/storage/backend/backend.go:170 +0xc5
go.etcd.io/etcd/etcdutl/v3/snapshot.(*v3Manager).saveDB(0xc0005dfbd8)
	go.etcd.io/etcd/etcdutl/v3/snapshot/v3_snapshot.go:303 +0xbe
go.etcd.io/etcd/etcdutl/v3/snapshot.(*v3Manager).Restore(0xc0005dfbd8, {{0x40008008d6, 0xd}, {0x40008007f2, 0x15}, {0x40008007e1, 0x9}, {0xc00048e0a8, 0x14}, {0xc000203ee0, ...}, ...})
	go.etcd.io/etcd/etcdutl/v3/snapshot/v3_snapshot.go:265 +0x7dc
go.etcd.io/etcd/etcdutl/v3/etcdutl.SnapshotRestoreCommandFunc({0x400080081a, 0x86}, {0xbba16b, 0xc}, {0x40008007e1?, 0x0?}, {0x0, 0x0}, {0x40008008bf, 0x16}, ...)
	go.etcd.io/etcd/etcdutl/v3/etcdutl/snapshot_command.go:132 +0x365
go.etcd.io/etcd/etcdutl/v3/etcdutl.snapshotRestoreCommandFunc(0xc00030ec00?, {0xc00064e4e0?, 0x6?, 0x6?})
	go.etcd.io/etcd/etcdutl/v3/etcdutl/snapshot_command.go:102 +0xed
github.com/spf13/cobra.(*Command).execute(0xc00030ec00, {0xc00064e480, 0x6, 0x6})
	github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x1168fc0)
	github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.7.0/command.go:992
main.Start(...)
	go.etcd.io/etcd/etcdutl/v3/ctl.go:56
main.main()
	go.etcd.io/etcd/etcdutl/v3/main.go:23 +0x5e
```

### PR DESCRIPTION
**Pull request by ivanvc**
When running the snapshot command, allow receiving an initial memory map allocation for the database, avoiding future memory allocation issues.

As discussed in the fortnightly etc triage meeting, I'm continuing the work from #16055 by squashing the commits and rebasing @fatihusta's original branch with main.

Fixes #16052.

Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

File: etcdutl/snapshot/v3_snapshot.go [hunk 1]
```diff
@@ -471,8 +480,10 @@ func (s *v3Manager) saveWALAndSnap() (*raftpb.HardState, error) {
 		return nil, err
 	}
 
-	// add members again to persist them to the backend we create.
-	be := backend.NewDefaultBackend(s.lg, s.outDbPath())
+	// add members again to persist them to the store we create.
+	st := v2store.New(etcdserver.StoreClusterPrefix, etcdserver.StoreKeysPrefix)
+	s.cl.SetStore(st)
```
Comment (ahrtr) [inline etcdutl/snapshot/v3_snapshot.go:485]: can you explain why adding this (v2store)?

File: etcdutl/etcdutl/snapshot_command.go [hunk 2]
```diff
@@ -38,6 +38,7 @@ var (
 	restorePeerURLs     string
 	restoreName         string
 	skipHashCheck       bool
+	initialMmapSize     = uint64(10 * 1024 * 1024 * 1024)
```
Comment (ahrtr) [inline etcdutl/etcdutl/snapshot_command.go:41]: It might be better to reuse the existing `initialMmapSize` defined in server/storage/backend? We need to export that variable.

File: etcdutl/etcdutl/snapshot_command.go [hunk 3]
```diff
@@ -77,6 +78,7 @@ func NewSnapshotRestoreCommand() *cobra.Command {
 	cmd.Flags().StringVar(&restorePeerURLs, "initial-advertise-peer-urls", defaultInitialAdvertisePeerURLs, "List of this member's peer URLs to advertise to the rest of the cluster")
 	cmd.Flags().StringVar(&restoreName, "name", defaultName, "Human-readable name for this member")
 	cmd.Flags().BoolVar(&skipHashCheck, "skip-hash-check", false, "Ignore snapshot integrity hash value (required if copied from data directory)")
+	cmd.Flags().Uint64Var(&initialMmapSize, "initial-memory-map-size", initialMmapSize, "Initial memory map allocation size(bytes) for the DB. if not defined, it uses the default. Also 0 means use default")
```
Comment (ahrtr) [inline etcdutl/etcdutl/snapshot_command.go:81]:
```suggestion
	cmd.Flags().Uint64Var(&initialMmapSize, "initial-memory-map-size", initialMmapSize, "Initial memory map allocation size(bytes) for the DB. It uses the default value if not defined or defined to 0")
```

File: etcdutl/snapshot/v3_snapshot.go (hunk 1 above)
Comment (ivanvc) [reply etcdutl/snapshot/v3_snapshot.go:485]: Good catch. I'm reviewing the original PR, and I probably wrongly fixed a conflict, as the implementation of `v3_snapshot` had that `v2store` before, and it's not here anymore. I'll check for any other differences with the original PR and update this PR.

Comment (ivanvc) [reply etcdutl/snapshot/v3_snapshot.go]: Removed.

File: etcdutl/etcdutl/snapshot_command.go (hunk 2 above)
Comment (ivanvc) [reply etcdutl/etcdutl/snapshot_command.go:41]: Hey @ahrtr, should I proceed to make this change? Or do you think I should wait for consensus from more maintainers?

Comment (ahrtr) [reply etcdutl/etcdutl/snapshot_command.go:41]: Please feel free to make the change. We will request maintainers to review & approve later.

File: server/storage/backend/backend.go [hunk 4]
```diff
@@ -164,9 +164,17 @@ func New(bcfg BackendConfig) Backend {
 	return newBackend(bcfg)
 }
 
-func NewDefaultBackend(lg *zap.Logger, path string) Backend {
-	bcfg := DefaultBackendConfig(lg)
-	bcfg.Path = path
+func NewDefaultBackend(bc BackendConfig) Backend {
+
```
Comment (ahrtr) [inline server/storage/backend/backend.go:168]:
```suggestion
```

File: server/storage/backend/backend.go [hunk 5]
```diff
@@ -164,9 +164,17 @@ func New(bcfg BackendConfig) Backend {
...
+	bcfg := DefaultBackendConfig(bc.Logger)
+	bcfg.Path = bc.Path
+
+	if bc.MmapSize > 0 {
+		bcfg.MmapSize = bc.MmapSize
+	} else {
+		bcfg.MmapSize = InitialMmapSize
+	}
```
Comment (ahrtr) [inline server/storage/backend/backend.go:176]: There are several fields in `BackendConfig`, but we we make use of only `MmapSize`, then why we have to pass into a `bc BackendConfig`? Suggest to follow the similar pattern something like below. We can only define one function `WithMmapSize` for now, and add others when needed in future,

https://github.com/etcd-io/etcd/blob/42f0cb9762cafa440a3f77884b0deb454ccb22c5/client/v3/op.go#L450-L477

Comment (ivanvc) [reply server/storage/backend/backend.go:176]: To make sure I re-implement correctly, you're suggesting to also return the `NewDefaultBackend` signature to `*zap.Logger, string`, right?

Comment (ivanvc) [reply server/storage/backend/backend.go:176]: Something like this:
https://github.com/etcd-io/etcd/blob/9ecdead32e5911f79a14613e8cbca5ef28866352/server/storage/backend/backend.go#L167-L181

And used like this:
https://github.com/etcd-io/etcd/blob/9ecdead32e5911f79a14613e8cbca5ef28866352/etcdutl/snapshot/v3_snapshot.go#L328

Comment (ahrtr) [reply server/storage/backend/backend.go:176]: Exactly.

File: etcdutl/etcdutl/snapshot_command.go [hunk 6]
```diff
@@ -77,6 +79,7 @@ func NewSnapshotRestoreCommand() *cobra.Command {
 	cmd.Flags().StringVar(&restorePeerURLs, "initial-advertise-peer-urls", defaultInitialAdvertisePeerURLs, "List of this member's peer URLs to advertise to the rest of the cluster")
 	cmd.Flags().StringVar(&restoreName, "name", defaultName, "Human-readable name for this member")
 	cmd.Flags().BoolVar(&skipHashCheck, "skip-hash-check", false, "Ignore snapshot integrity hash value (required if copied from data directory)")
+	cmd.Flags().Uint64Var(&initialMmapSize, "initial-memory-map-size", initialMmapSize, "Initial memory map allocation size(bytes) for the DB. It uses the default value if not defined or defined to 0")
```
[the remark this answers is not in the document]
Comment (ivanvc) [reply etcdutl/etcdutl/snapshot_command.go]: Done.

File: server/storage/backend/backend.go (hunk 4 above)
Comment (ivanvc) [reply server/storage/backend/backend.go]: Done.

File: server/storage/backend/backend.go (hunk 5 above)
Comment (ivanvc) [reply server/storage/backend/backend.go]: Done.

File: etcdutl/etcdutl/snapshot_command.go (hunk 2 above)
Comment (ivanvc) [reply etcdutl/etcdutl/snapshot_command.go]: Done.

File: server/storage/backend/backend.go [hunk 7]
```diff
@@ -151,11 +151,13 @@ type BackendConfig struct {
 	Hooks Hooks
 }
 
+type BackendConfigFunc func(*BackendConfig)
```
Comment (ahrtr) [inline server/storage/backend/backend.go:154]:
```suggestion
type BackendConfigOption func(*BackendConfig)
```

File: server/storage/backend/backend.go [hunk 8]
```diff
@@ -164,9 +166,19 @@ func New(bcfg BackendConfig) Backend {
...
 }
 
-func NewDefaultBackend(lg *zap.Logger, path string) Backend {
+func WithMmapSize(size uint64) BackendConfigFunc {
+	return func(bcfg *BackendConfig) {
+		bcfg.MmapSize = size
+	}
+}
+
+func NewDefaultBackend(lg *zap.Logger, path string, bcfns ...BackendConfigFunc) Backend {
```
Comment (ahrtr) [inline server/storage/backend/backend.go:175]:
```suggestion
func NewDefaultBackend(lg *zap.Logger, path string, opts ...BackendConfigOption) Backend {
```

File: server/config/config.go [hunk 9]
```diff
@@ -119,6 +119,7 @@ type ServerConfig struct {
 	CompactionBatchLimit    int
 	CompactionSleepInterval time.Duration
 	QuotaBackendBytes       int64
+	InitialMmapSize         uint64
```
Comment (ahrtr) [inline server/config/config.go:122]: Do we still need this field?

File: server/storage/backend/backend.go (hunk 7 above)
Comment (ivanvc) [reply server/storage/backend/backend.go:154]: Done.

File: server/storage/backend/backend.go (hunk 8 above)
Comment (ivanvc) [reply server/storage/backend/backend.go:175]: Done.

**Review by ahrtr — APPROVED** [review]
lgtm

Nice work! thx

**Review by serathius — APPROVED** [review]
