### PR TITLE
etcdserver: optimize range request with KEY ASCEND sorting

### LINKED ISSUE #20745: Range requests with limit ignore limit when sorting by key ascending
### Bug report criteria

- [x] This bug report is not security related, security issues should be disclosed privately via security@etcd.io.
- [x] This is not a support request or question, support requests or questions should be raised in the etcd [discussion forums](https://github.com/etcd-io/etcd/discussions).
- [x] You have read the etcd [bug reporting guidelines](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/reporting_bugs.md).
- [x] Existing open issues along with etcd [frequently asked questions](https://etcd.io/docs/latest/faq) have been checked and this is not a duplicate.

### What happened?

When performing a range request with a limit and sorting by key in ascending order, etcd currently ignores the limit and fetches all matching keys from the backend, then truncates them in memory. This causes unnecessary performance overhead and memory usage.

### What did you expect to happen?

The query result is correct, but it would be better if the server retained the limit requested by the user.

### How can we reproduce it (as minimally and precisely as possible)?

Execute a query with sort order set to ascending by key. You can't directly observe this bug, but the internal behavior of the server when executing this query is inefficient.

### Anything else we need to know?

_No response_

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
etcd Version: 3.5.17
Git SHA: 507c0de87
Go Version: go1.23.3
Go OS/Arch: darwin/arm64


$ etcdctl version

etcdctl version: 3.5.17
API version: 3.5

```

</details>

This behavior is also present in 3.6

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

### Relevant log output

```Shell

```

### PR DESCRIPTION
**Pull request by kairosci**
This PR optimizes range request handling by passing the limit to the backend when sorting by key in ascending order, as the backend already returns keys in this order. This avoids fetching all keys and then truncating in memory.

```
goos: windows
goarch: amd64
pkg: go.etcd.io/etcd/server/v3/etcdserver/txn
cpu: Intel(R) Core(TM) 5 120U

                                            │        old.txt        │              new.txt               │
                                            │         sec/op        │   sec/op      vs base              │
--------------------------------------------------------------------------------------------------------
RangeLimitOptimization/KeyAscendLimit100_10k/Old       3.056m ± 0%       26.93μ ± 0%   -99.12% (p=0.000)
RangeLimitOptimization/KeyAscendLimit100_100k/Old     16.639m ± 0%       27.11μ ± 0%   -99.84% (p=0.000)
RangeLimitOptimization/KeyAscendLimit100_1m/Old     168.512m ± 0%       25.22μ ± 0%   -99.99% (p=0.000)
RangeLimitOptimization/KeyAscendLimit1000_10k/Old     2.412m ± 0%      256.44μ ± 0%   -89.37% (p=0.000)
geomean                                        14.274m              49.52μ         -99.65%
```

Closes #20745

### CODE REVIEW

File: server/etcdserver/txn/range_test.go [hunk 1]
```diff
@@ -0,0 +1,79 @@
...
+				SortOrder:  pb.RangeRequest_ASCEND,
+				SortTarget: pb.RangeRequest_VERSION,
+			},
+			expected: 0,
+		},
+	}
+
+	for _, tt := range tests {
+		t.Run(tt.name, func(t *testing.T) {
+			actual := rangeLimit(tt.request)
```
Comment (serathius) [inline server/etcdserver/txn/range_test.go]: Make no sense to test low level function like `rangeLimit`, at some point it might be rewritten and the test will be useless. 

Instead of depending on unit test validating limit returned by the function, we should test and benchmark for the whole range for Range. This way we know that range still behaves correctly after the change and we can see performance improvement in benchmark.

cc @nwnt

**Comment by kairosci** [comment]
Addressed the review feedback:

Replaced the `TestRangeLimit` unit test with integration tests that test the full `Range` function:

- `TestRangeWithSortAndLimit`: Tests correctness with various sort orders, targets, and limits
- `TestRangeKeyAscendOptimizationCorrectness`:  Validates the optimized path produces identical results to non-optimized paths  
- `BenchmarkRange`:  Benchmarks demonstrating ~40x performance improvement with KEY ASCEND sorting

The tests no longer depend on the internal `rangeLimit` function.

**Comment by kairosci** [comment]
@serathius could you take another look? Thank you!

**Comment by serathius** [comment]
/ok-to-test

Nont can you do a first round of review?
/cc @nwnt

**Comment by serathius** [comment]
Please fix 
```
../server/etcdserver/txn/range_test.go:194:4: formatter: use assert.Equalf (testifylint)
			assert.Equal(t, tt.wantKeys, gotKeys, "returned keys mismatch")
			^
../server/etcdserver/txn/range_test.go:195:4: formatter: use assert.Equalf (testifylint)
			assert.Equal(t, tt.wantMore, resp.More, "More flag mismatch")
			^
../server/etcdserver/txn/range_test.go:196:4: formatter: use assert.Equalf (testifylint)
			assert.Equal(t, tt.wantCount, resp.Count, "Count mismatch")
			^
../server/etcdserver/txn/range_test.go:251:4: len: use assert.Len (testifylint)
			assert.Equal(t, len(respNoSort.Kvs), len(respAscend.Kvs), "number of keys mismatch")
			^
../server/etcdserver/txn/range_test.go:253:5: formatter: use assert.Equalf (testifylint)
				assert.Equal(t, string(respNoSort.Kvs[i].Key), string(respAscend.Kvs[i].Key),
				^
../server/etcdserver/txn/range_test.go:256:4: formatter: use assert.Equalf (testifylint)
			assert.Equal(t, respNoSort.More, respAscend.More, "More flag mismatch")
			^
../server/etcdserver/txn/range_test.go:257:4: formatter: use assert.Equalf (testifylint)
			assert.Equal(t, respNoSort.Count, respAscend.Count, "Count mismatch")
			^
7 issues:
```

File: server/etcdserver/txn/range.go [hunk 2]
```diff
@@ -67,7 +67,11 @@ func executeRange(ctx context.Context, lg *zap.Logger, txnRead mvcc.TxnRead, r *
 
 func rangeLimit(r *pb.RangeRequest) int64 {
 	limit := r.Limit
-	if r.SortOrder != pb.RangeRequest_NONE ||
+	sortOrder := r.SortOrder
```
Comment (nwnt) [inline server/etcdserver/txn/range.go]: I think it would be much better to give it a named conditional variable than lumping it into `pb.RangeRequest_NONE`.  That way when we look at the conditions, it's clearer.

```suggestion
	keySortAscending = r.SortTarget == pb.RangeRequest_KEY && sortOrder == pb.RangeRequest_ASCEND

    if r.SortTarget != pb.RangeRequest_None || !keySortAscending ....
```

File: server/etcdserver/txn/range_test.go [hunk 3]
```diff
@@ -0,0 +1,346 @@
...
+			wantKeys:  []string{"a", "b"}, // a (rev 3), b (rev 4), d (rev 5), e (rev 6) - first 2
+			wantMore:  true,
+			wantCount: 5, // count is total before filtering
+		},
+	}
+
+	for _, tt := range tests {
+		t.Run(tt.name, func(t *testing.T) {
+			b, _ := betesting.NewDefaultTmpBackend(t)
+			t.Cleanup(func() {
```
Comment (nwnt) [inline server/etcdserver/txn/range_test.go]: Is there any particular reason to use this than `defer`?  If not I think let's keep things simple by using `defer`.

File: server/etcdserver/txn/range_test.go [hunk 4]
```diff
@@ -0,0 +1,346 @@
...
+				betesting.Close(t, b)
+			})
+			s := mvcc.NewStore(zaptest.NewLogger(t), b, &lease.FakeLessor{}, mvcc.StoreConfig{})
+			t.Cleanup(func() {
```
Comment (nwnt) [inline server/etcdserver/txn/range_test.go]: ditto

File: server/etcdserver/txn/range_test.go [hunk 5]
```diff
@@ -0,0 +1,346 @@
...
+	}
+}
+
+// TestRangeKeyAscendOptimizationCorrectness specifically tests that the
+// KEY ASCEND optimization produces the same results as the non-optimized path.
+func TestRangeKeyAscendOptimizationCorrectness(t *testing.T) {
+	b, _ := betesting.NewDefaultTmpBackend(t)
+	t.Cleanup(func() {
+		betesting.Close(t, b)
+	})
```
Comment (nwnt) [inline server/etcdserver/txn/range_test.go]: ditto

File: server/etcdserver/txn/range_test.go [hunk 6]
```diff
@@ -0,0 +1,346 @@
...
+	s := mvcc.NewStore(zaptest.NewLogger(t), b, &lease.FakeLessor{}, mvcc.StoreConfig{})
+	t.Cleanup(func() {
```
Comment (nwnt) [inline server/etcdserver/txn/range_test.go]: ditto

File: server/etcdserver/txn/range_test.go [hunk 7]
```diff
@@ -0,0 +1,346 @@
...
+		s.Close()
+	})
+
+	// Insert 100 keys in random order
+	keys := make([]string, 100)
+	for i := 0; i < 100; i++ {
```
Comment (nwnt) [inline server/etcdserver/txn/range_test.go]:
```suggestion
	for i := range 100 {
```

File: server/etcdserver/txn/range_test.go [hunk 8]
```diff
@@ -0,0 +1,346 @@
...
+	t.Cleanup(func() {
+		betesting.Close(t, b)
+	})
+	s := mvcc.NewStore(zaptest.NewLogger(t), b, &lease.FakeLessor{}, mvcc.StoreConfig{})
+	t.Cleanup(func() {
+		s.Close()
+	})
+
+	// Insert 100 keys in random order
+	keys := make([]string, 100)
```
Comment (nwnt) [inline server/etcdserver/txn/range_test.go]: I think these two loops can be combined.

File: server/etcdserver/txn/range_test.go [hunk 9]
```diff
@@ -0,0 +1,346 @@
...
+			},
+		},
+	}
+
+	for _, keyCount := range []int{100, 1000, 10000} {
+		for _, bm := range benchmarks {
+			b.Run(fmt.Sprintf("keys_%d/%s", keyCount, bm.name), func(b *testing.B) {
+				be, _ := betesting.NewDefaultTmpBackend(b)
+				s := mvcc.NewStore(zaptest.NewLogger(b), be, &lease.FakeLessor{}, mvcc.StoreConfig{})
+				defer func() {
```
Comment (nwnt) [inline server/etcdserver/txn/range_test.go]: Can we just defer each of them after creating, without putting them in an anonymous func?

File: server/etcdserver/txn/range_test.go [hunk 10]
```diff
@@ -0,0 +1,346 @@
...
+					s.Close()
+					betesting.Close(b, be)
+				}()
+
+				// Insert keys
+				for i := 0; i < keyCount; i++ {
```
Comment (nwnt) [inline server/etcdserver/txn/range_test.go]:
```suggestion
				for i := range keyCount {
```

File: server/etcdserver/txn/range_test.go [hunk 11]
```diff
@@ -0,0 +1,346 @@
...
+					s.Put([]byte(fmt.Sprintf("key-%05d", i)), []byte("value"), lease.NoLease)
+				}
+				s.Commit()
+
+				ctx := context.Background()
+				lg := zaptest.NewLogger(b)
+
+				b.ReportAllocs()
+				b.ResetTimer()
+				for i := 0; i < b.N; i++ {
```
Comment (nwnt) [inline server/etcdserver/txn/range_test.go]:
```suggestion
				for i := range b.N {
```

File: server/etcdserver/txn/range_test.go [hunk 12]
```diff
@@ -0,0 +1,346 @@
...
+// BenchmarkRange benchmarks Range requests with different configurations.
+// This helps demonstrate the performance improvement from the KEY ASCEND optimization.
+func BenchmarkRange(b *testing.B) {
+	benchmarks := []struct {
+		name    string
+		request *pb.RangeRequest
+	}{
+		{
+			name: "no_sort_no_limit",
+			request: &pb.RangeRequest{
```
Comment (nwnt) [inline server/etcdserver/txn/range_test.go]: The only parameters that seem changing are just the limit, sort order and sort target.  We can specify them in the struct instead of having the full `*pb.RangeRequest`, and in the main test loop you can construct the RangeRequest with them.

File: server/etcdserver/txn/range_test.go [hunk 13]
```diff
@@ -0,0 +1,346 @@
...
+			}
+			assert.Equalf(t, respNoSort.More, respAscend.More, "More flag mismatch")
+			assert.Equalf(t, respNoSort.Count, respAscend.Count, "Count mismatch")
+		})
+	}
+}
+
+// BenchmarkRange benchmarks Range requests with different configurations.
+// This helps demonstrate the performance improvement from the KEY ASCEND optimization.
+func BenchmarkRange(b *testing.B) {
```
Comment (nwnt) [inline server/etcdserver/txn/range_test.go]: I think the convention in the project is to put benchmarking tests in a *_bench_test.go.  You can look at server/storage/mvcc/ for some examples.

File: server/etcdserver/txn/range_test.go [hunk 14]
```diff
@@ -0,0 +1,346 @@
...
+			assert.Equalf(t, tt.wantKeys, gotKeys, "returned keys mismatch")
+			assert.Equalf(t, tt.wantMore, resp.More, "More flag mismatch")
+			assert.Equalf(t, tt.wantCount, resp.Count, "Count mismatch")
+		})
+	}
+}
+
+// TestRangeKeyAscendOptimizationCorrectness specifically tests that the
+// KEY ASCEND optimization produces the same results as the non-optimized path.
+func TestRangeKeyAscendOptimizationCorrectness(t *testing.T) {
```
Comment (nwnt) [inline server/etcdserver/txn/range_test.go]: Unless I miss anything, I think we can combine this and the above test.  The case this test is trying to ensure seems saying no sort and sort by key ascending are the same.  That's already asserted by the second and third test cases in the above test function.  You can add the key randomization to the above though.

File: server/etcdserver/txn/range.go [hunk 15]
```diff
@@ -67,7 +67,11 @@ func executeRange(ctx context.Context, lg *zap.Logger, txnRead mvcc.TxnRead, r *
...
+	if r.SortTarget == pb.RangeRequest_KEY && sortOrder == pb.RangeRequest_ASCEND {
```
Comment (nwnt) [inline server/etcdserver/txn/range.go]: I don't think this has been resolved yet.  Like I mentioned previously, these scenarios are not the same and we should not classify that _sorting by key ascending_ is the same as sort order none.

File: server/etcdserver/txn/range_test.go [hunk 16]
```diff
@@ -0,0 +1,198 @@
+// Copyright 2025 The etcd Authors
```
Comment (nwnt) [inline server/etcdserver/txn/range_test.go]: Now this file seems to be similar to `TestKVGet` in `tests/common/kv_test.go`, can we drop this file and add the same tests there?

**Comment by serathius** [comment]
Please squash commits

File: server/etcdserver/txn/range.go [hunk 17]
```diff
@@ -67,20 +68,27 @@ func executeRange(ctx context.Context, lg *zap.Logger, txnRead mvcc.TxnRead, r *
...
 	}
-	if limit > 0 {
+	if limit > 0 && limit < math.MaxInt64 {
 		// fetch one extra for 'more' flag
 		limit = limit + 1
 	}
 	return limit
 }
 
+func hasFilters(r *pb.RangeRequest) bool {
```
Comment (nwnt) [inline server/etcdserver/txn/range.go]: nit: `hasRevisionFilters` would be more specific.

File: server/etcdserver/txn/range.go [hunk 18]
```diff
@@ -106,13 +114,16 @@ func sortRangeResults(rr *mvcc.RangeResult, r *pb.RangeRequest, lg *zap.Logger)
 		// sorted by keys in lexiographically ascending order,
 		// sort ASCEND by default only when target is not 'KEY'
 		sortOrder = pb.RangeRequest_ASCEND
-	} else if r.SortTarget == pb.RangeRequest_KEY && sortOrder == pb.RangeRequest_ASCEND {
+	}
+
+	needSort := sortOrder != pb.RangeRequest_NONE
+	if r.SortTarget == pb.RangeRequest_KEY && sortOrder == pb.RangeRequest_ASCEND {
```
Comment (nwnt) [inline server/etcdserver/txn/range.go]: This boolean logic is a duplicate of line 71.  Can you please extract it?

Comment (nwnt) [reply server/etcdserver/txn/range.go]: And perhaps this can be combined with line 119, so we don't need the if statement.

File: tests/common/kv_test.go [hunk 19]
```diff
@@ -119,6 +119,8 @@ func TestKVGet(t *testing.T) {
 					{name: "--prefix of foo -> all entries with the prefix", begin: "foo", options: config.GetOptions{Prefix: true}, wantResponse: &clientv3.GetResponse{Header: currentHeader, Count: 2, Kvs: []*mvccpb.KeyValue{kvFoo, kvFooAbc}}},
 					{name: "--from-key of 'foo' -> [", begin: "foo", options: config.GetOptions{FromKey: true}, wantResponse: &clientv3.GetResponse{Header: currentHeader, Count: 3, Kvs: []*mvccpb.KeyValue{kvFoo, kvFooAbc, kvFop}}},
 					{name: "blank key with limit set", begin: "", options: config.GetOptions{Prefix: true, Limit: 2}, wantResponse: &clientv3.GetResponse{Header: currentHeader, Count: 6, Kvs: []*mvccpb.KeyValue{kvA, kvB}, More: true}},
+					{name: "all KVs ordered by key ascending, limit 2", begin: "", options: config.GetOptions{Prefix: true, Order: clientv3.SortAscend, SortBy: clientv3.SortByKey, Limit: 2}, wantResponse: &clientv3.GetResponse{Header: currentHeader, Count: 6, Kvs: []*mvccpb.KeyValue{kvA, kvB}, More: true}},
```
Comment (nwnt) [inline tests/common/kv_test.go]: Move the ascending case above line 128 to group the similar cases together.  I think we don't need the descending case as it's pretty much a duplicate of what we currently have, so please can you remove it?

File: tests/common/kv_test.go [hunk 20]
```diff
@@ -121,6 +121,7 @@ func TestKVGet(t *testing.T) {
 					{name: "blank key with limit set", begin: "", options: config.GetOptions{Prefix: true, Limit: 2}, wantResponse: &clientv3.GetResponse{Header: currentHeader, Count: 6, Kvs: []*mvccpb.KeyValue{kvA, kvB}, More: true}},
 					{name: "all kvs ordered by mod revision ascending", begin: "", options: config.GetOptions{Prefix: true, Order: clientv3.SortAscend, SortBy: clientv3.SortByModRevision}, wantResponse: &clientv3.GetResponse{Header: currentHeader, Count: 6, Kvs: allKvs}},
 					{name: "all KVs ordered by version ascending", begin: "", options: config.GetOptions{Prefix: true, Order: clientv3.SortAscend, SortBy: clientv3.SortByVersion}, wantResponse: &clientv3.GetResponse{Header: currentHeader, Count: 6, Kvs: kvsByVersion}},
+					{name: "all KVs ordered by key ascending, limit 2", begin: "", options: config.GetOptions{Prefix: true, Order: clientv3.SortAscend, SortBy: clientv3.SortByKey, Limit: 2}, wantResponse: &clientv3.GetResponse{Header: currentHeader, Count: 6, Kvs: []*mvccpb.KeyValue{kvA, kvB}, More: true}},
```
Comment (serathius) [inline tests/common/kv_test.go]: Please send test improvements in separate PR that would be merged first.

Comment (kairosci) [reply tests/common/kv_test.go]: #21577

**Comment by kairosci** [comment]
@serathius So I've rebased and removed the tests, leaving only `server/etcdserver/txn/range.go` in this PR. Let me know if there are any other changes to make; it should be fine.

File: server/etcdserver/txn/range.go [hunk 21]
```diff
@@ -67,20 +68,27 @@ func executeRange(ctx context.Context, lg *zap.Logger, txnRead mvcc.TxnRead, r *
...
 	return limit
 }
 
+func hasRevisionFilters(r *pb.RangeRequest) bool {
+	return r.MinModRevision != 0 || r.MaxModRevision != 0 ||
+		r.MinCreateRevision != 0 || r.MaxCreateRevision != 0
+}
+
 func filterRangeResults(rr *mvcc.RangeResult, r *pb.RangeRequest) {
+	if !hasRevisionFilters(r) {
```
Comment (serathius) [inline server/etcdserver/txn/range.go]: Adding a early return here create a risk of if statements becoming out of date with hasRevisionFilters function. 
Don't think there is any benefit of this if statement.

If you want to improve it I recommend doing it in separate PR by rewriting to switch.

File: server/etcdserver/txn/range.go [hunk 22]
```diff
@@ -106,13 +114,13 @@ func sortRangeResults(rr *mvcc.RangeResult, r *pb.RangeRequest, lg *zap.Logger)
...
-		// sorted by keys in lexiographically ascending order,
-		// don't re-sort when target is 'KEY' and order is ASCEND
-		sortOrder = pb.RangeRequest_NONE
 	}
-	if sortOrder != pb.RangeRequest_NONE {
+
+	// Since current mvcc.Range implementation returns results
+	// sorted by keys in lexiographically ascending order,
+	// don't re-sort when target is 'KEY' and order is ASCEND
+	needSort := sortOrder != pb.RangeRequest_NONE && !(r.SortTarget == pb.RangeRequest_KEY && sortOrder == pb.RangeRequest_ASCEND)
```
Comment (serathius) [inline server/etcdserver/txn/range.go]: Please don't write conditions based on negation. Prefer positive conditions like:
```
isDefaultOrdering := sortOrder == pb.RangeRequest_NONE || (r.SortTarget == pb.RangeRequest_KEY && sortOrder == pb.RangeRequest_ASCEND)
needSort := !isDefaultOrdering
```

**Comment by serathius** [comment]
Please utilize the added range benchmark to show improvement that this PR brings. See https://www.youtube.com/watch?v=jiXnzkAzy30 for how to benchmark code.

File: server/etcdserver/txn/range.go (hunk 21 above)
Comment (kairosci) [reply server/etcdserver/txn/range.go]: #21580

**Comment by serathius** [comment]
> I analyzed the benchmarks using Daniel Martí’s approach.

Can you just paste the results like in https://github.com/etcd-io/etcd/pull/21486

**Comment by kairosci** [comment]
goarch: amd64
 pkg: go.etcd.io/etcd/server/v3/etcdserver/txn
 cpu: Intel(R) Core(TM) 5 120U
 
                                               │ benchmark_main.txt │         benchmark_optimized.txt         │
                                               │       sec/op       │     sec/op      vs base                 │
 RangeLimit/KEY_ASCEND_with_limit-12                 0.3392n ± 315%   2.9755n ±  59%  +777.08% (p=0.000 n=10)
 RangeLimit/KEY_ASCEND_without_limit-12               1.418n ±   4%    3.007n ±   6%  +111.98% (p=0.000 n=10)
 RangeLimit/MOD_REVISION_sorting_with_limit-12        1.410n ±   9%    2.143n ±   4%   +51.99% (p=0.000 n=10)
 RangeLimit/no_sorting_with_limit-12                 0.3106n ±   3%   0.8933n ± 225%  +187.60% (p=0.000 n=10)
 RangeLimit/with_revision_filters-12                 0.3065n ±   3%   1.0800n ±   3%  +252.37% (p=0.000 n=10)
 geomean                                             0.5781n           1.792n         +210.02%

**Comment by serathius** [comment]
/cc @ahrtr @fuweid 

Note: change is covered by tests:

https://github.com/etcd-io/etcd/blob/93f54aee4d8b112e68291bdc8edf7e6f1a9b4040/tests/common/kv_test.go#L59-L167

File: server/etcdserver/txn/range.go [hunk 23]
```diff
@@ -67,31 +68,39 @@ func executeRange(ctx context.Context, lg *zap.Logger, txnRead mvcc.TxnRead, r *
 
 func rangeLimit(r *pb.RangeRequest) int64 {
 	limit := r.Limit
-	if r.SortOrder != pb.RangeRequest_NONE ||
-		r.MinModRevision != 0 || r.MaxModRevision != 0 ||
-		r.MinCreateRevision != 0 || r.MaxCreateRevision != 0 {
+	keySortAscending := r.SortTarget == pb.RangeRequest_KEY && r.SortOrder == pb.RangeRequest_ASCEND
+	if (r.SortOrder != pb.RangeRequest_NONE && !keySortAscending) || hasRevisionFilters(r) {
```
Comment (ahrtr) [inline server/etcdserver/txn/range.go]: can we add a function something like below so that it can be reused here and in `sortRangeResults`?

```
func isDefaultOrdering(r *pb.RangeRequest) bool {
	return r.SortOrder == pb.RangeRequest_NONE ||
		r.SortTarget == pb.RangeRequest_KEY && r.SortOrder == pb.RangeRequest_ASCEND
}
```

File: server/etcdserver/txn/range.go [hunk 24]
```diff
@@ -67,48 +68,56 @@ func executeRange(ctx context.Context, lg *zap.Logger, txnRead mvcc.TxnRead, r *
...
 
+func isDefaultOrdering(r *pb.RangeRequest) bool {
+	return r.SortOrder == pb.RangeRequest_NONE ||
+		r.SortTarget == pb.RangeRequest_KEY && r.SortOrder == pb.RangeRequest_ASCEND
+}
+
+func isDefaultOrderingWithTarget(r *pb.RangeRequest, sortOrder pb.RangeRequest_SortOrder) bool {
+	return sortOrder == pb.RangeRequest_NONE ||
+		(r.SortTarget == pb.RangeRequest_KEY && sortOrder == pb.RangeRequest_ASCEND)
+}
```
Comment (ahrtr) [inline server/etcdserver/txn/range.go]: let's consolidate them into one function
```suggestion
func isDefaultOrdering(sortTarget pb.RangeRequest_SortTarget, sortOrder pb.RangeRequest_SortOrder) bool {
	return sortOrder == pb.RangeRequest_NONE ||
		(sortTarget == pb.RangeRequest_KEY && sortOrder == pb.RangeRequest_ASCEND)
}
```

File: server/etcdserver/txn/range.go [hunk 25]
```diff
@@ -67,48 +68,51 @@ func executeRange(ctx context.Context, lg *zap.Logger, txnRead mvcc.TxnRead, r *
...
-	} else if r.SortTarget == pb.RangeRequest_KEY && sortOrder == pb.RangeRequest_ASCEND {
-		// Since current mvcc.Range implementation returns results
-		// sorted by keys in lexiographically ascending order,
-		// don't re-sort when target is 'KEY' and order is ASCEND
-		sortOrder = pb.RangeRequest_NONE
 	}
-	if sortOrder != pb.RangeRequest_NONE {
+
+	if !isDefaultOrdering(r.SortTarget, sortOrder) {
 		var sorter sort.Interface
```
Comment (ahrtr) [inline server/etcdserver/txn/range.go:112]: Please keep this comment for `isDefaultOrdering`


```
		// Since current mvcc.Range implementation returns results
		// sorted by keys in lexiographically ascending order,
		// don't re-sort when target is 'KEY' and order is ASCEND
```
