### PR TITLE
Fix cluster peer HTTP SRV discovery when no HTTPS records exist

### LINKED ISSUE #11321: etcd cluster fails to start when using DNS SRV discovery with non-TLS
I am running etcd (version 3.4.3) on Fedora CoreOS (version 30) using Podman.

When running etcd with no TLS and SRV discovery, the installation is **failing** because it doesn't find `_etcd-server-ssl` entries. This should not fail since entries do not exist as TLS is not being used.

```
2019-10-31 09:53:30.575647 E | embed: couldn't resolve during SRV discovery (error querying DNS SRV records for _etcd-server-ssl lookup _etcd-server-ssl._tcp.libvirt.labs on 172.16.10.1:53: no such host)
2019-10-31 09:53:30.575892 C | etcdmain: error setting up initial cluster: error querying DNS SRV records for _etcd-server-ssl lookup _etcd-server-ssl._tcp.libvirt.labs on 172.16.10.1:53: no such host
```

It also fails on 3.4.2, 3.4.1 and 3.4.0. However, in **3.3.17 it is working properly** (see table blelow) but I don't see any change in [**3.4 changelog**](https://github.com/etcd-io/etcd/blob/master/CHANGELOG-3.4.md) that forces to use TLS when SRV discovery is enabled. Is this the correct behaviour in 3.4?

```
+--------------------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
|            ENDPOINT            |        ID        | VERSION | DB SIZE | IS LEADER | IS LEARNER | RAFT TERM | RAFT INDEX | RAFT APPLIED INDEX | ERRORS |
+--------------------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
| http://etcd1.libvirt.labs:2379 | ceb796e1dfaeb27e |  3.3.17 |   20 kB |      true |      false |        11 |          9 |                  0 |        |
| http://etcd2.libvirt.labs:2379 | b8dfd5ef2d30984a |  3.3.17 |   20 kB |     false |      false |        11 |          9 |                  0 |        |
| http://etcd3.libvirt.labs:2379 | dde9feb56ac9a7ad |  3.3.17 |   20 kB |     false |      false |        11 |          9 |                  0 |        |
+--------------------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
```

The first member of the cluster is getting started with:

```bash
ETCD_UUID="5d9701ad-6c02-4f64-b614-1e4561c29181" # $(uuidgen)
ETCD_VERSION="v3.4.3"
ETCD_NODE_NAME="$(hostname -s)"
ETCD_NODE_CLIENT_ADVERTISE_URL="http://$(hostname | cut -d' ' -f1):2379"
ETCD_NODE_SERVER_ADVERTISE_URL="http://$(hostname | cut -d' ' -f1):2380"
ETCD_NODE_CLIENT_LISTEN_URL="http://$(hostname -I | cut -d' ' -f1):2379"
ETCD_NODE_SERVER_LISTEN_URL="http://$(hostname -I | cut -d' ' -f1):2380"
ETCD_DATA_DIR="/var/lib/etcd"
ETCD_DNS_SRV_DOMAIN="$(dnsdomainname)"

mkdir -p ${ETCD_DATA_DIR}

podman run \
  --name etcd \
  --volume ${ETCD_DATA_DIR}:/etcd-data:z \
  --net=host \
  quay.io/coreos/etcd:${ETCD_VERSION} \
    /usr/local/bin/etcd \
      --name ${ETCD_NODE_NAME} \
      --data-dir /etcd-data \
      --initial-cluster-state new \
      --initial-cluster-token ${ETCD_UUID} \
      --discovery-srv ${ETCD_DNS_SRV_DOMAIN} \
      --advertise-client-urls ${ETCD_NODE_CLIENT_ADVERTISE_URL} \
      --initial-advertise-peer-urls ${ETCD_NODE_SERVER_ADVERTISE_URL} \
      --listen-client-urls ${ETCD_NODE_CLIENT_LISTEN_URL} \
      --listen-peer-urls ${ETCD_NODE_SERVER_LISTEN_URL}
```

The DNS SRV entries for etcd cluster are:
```bash
$ dig +noall +answer SRV _etcd-server._tcp.libvirt.labs _etcd-client._tcp.libvirt.labs
_etcd-server._tcp.libvirt.labs.	0 IN	SRV	0 0 2380 etcd1.libvirt.labs.
_etcd-server._tcp.libvirt.labs.	0 IN	SRV	0 0 2380 etcd3.libvirt.labs.
_etcd-server._tcp.libvirt.labs.	0 IN	SRV	0 0 2380 etcd2.libvirt.labs.
_etcd-client._tcp.libvirt.labs.	0 IN	SRV	0 0 2379 etcd3.libvirt.labs.
_etcd-client._tcp.libvirt.labs.	0 IN	SRV	0 0 2379 etcd2.libvirt.labs.
_etcd-client._tcp.libvirt.labs.	0 IN	SRV	0 0 2379 etcd1.libvirt.labs.
``` 

The DNS A entries for etcd cluster are:
```bash
$ dig +noall +answer etcd1.libvirt.labs etcd2.libvirt.labs etcd3.libvirt.labs
etcd1.libvirt.labs.	0	IN	A	172.16.10.49
etcd2.libvirt.labs.	0	IN	A	172.16.10.188
etcd3.libvirt.labs.	0	IN	A	172.16.10.36
```

Etcd version is:

```
etcd Version: 3.4.3
Git SHA: 3cf2f69b5
Go Version: go1.12.12
Go OS/Arch: linux/amd64
```

### PR DESCRIPTION
**Pull request by brandond**
embed: Fix cluster peer HTTP SRV discovery

Fixed issue where peer SRV discovery failed if no HTTPS endpoints were discovered. HTTP endpoints were never added to the address list due to a bad error check, and the `_etcd-server-ssl._tcp.<domain>` failure masked the subsequent success of lookups for `_etcd-server._tcp.<domain>`

Fixes #11321

### CODE REVIEW

**Comment by xorjain** [comment]
Thanks a lot for this fix @brandond .

Can someone from the team please merge this change? Thanks in advance.

**Comment by der-eismann** [comment]
Yeah, we also really need this PR merged so we can finally upgrade our cluster.

**Comment by brandond** [comment]
Is there anything I can do to help move this forward? I realize pulling in multierr might be controversial, I'm open to alternate approaches to wrapping or combining the errors.

**Comment by trivigy** [comment]
@brandond have you been able to find a workaround in the meantime? Or did you endup just using your own fork?

**Comment by brandond** [comment]
@trivigy yeah I'm just running off a local fork.

**Comment by der-eismann** [comment]
@gyuho could you (or another maintainer) maybe have a look? We finally want to upgrade, but don't have the time to switch on TLS.

**Comment by der-eismann** [comment]
Not stale

File: embed/config.go [hunk 1]
```diff
@@ -683,7 +684,7 @@ func (cfg *Config) GetDNSClusterNames() ([]string, error) {
 		zap.Error(httpCerr),
 	)
 
-	return clusterStrs, cerr
+	return clusterStrs, multierr.Combine(cerr, httpCerr)
```
Comment (ptabor) [inline embed/config.go:687]: Could you, please, add comments to "GetDNSClusterNames" signature that the method might return combination of the experienced errors and actual collected results ?

File: embed/config.go [hunk 2]
```diff
@@ -611,7 +612,7 @@ func (cfg *Config) PeerURLsMapAndToken(which string) (urlsmap types.URLsMap, tok
 	case cfg.DNSCluster != "":
 		clusterStrs, cerr := cfg.GetDNSClusterNames()
 		lg := cfg.logger
-		if cerr != nil {
+		if len(clusterStrs) == 0 && cerr != nil {
 			lg.Warn("failed to resolve during SRV discovery", zap.Error(cerr))
```
Comment (ptabor) [inline embed/config.go:616]: Can we log the warning always when cerr != nil, 
but return from the method only when clusterStrs is empty.

**Review by ptabor — CHANGES_REQUESTED** [review]
I'm sorry for not looking at this earlier. Thank you for the fix. 

Could you, please: 
 - Rebase this
 - Add a regression test for this scenario.

File: embed/config.go (hunk 1 above)
Comment (brandond) [reply embed/config.go]: Done

File: embed/config.go (hunk 2 above)
Comment (brandond) [reply embed/config.go]: Done

**Comment by brandond** [comment]
Rebased and requested changes made.

**Comment by ptabor** [comment]
Thank you for the iteration. 

* Please run ./script/fix.sh, as go.mod -> go.sum went out of sync, and that's the reason why the test fails. 
* Is it possible to add a regression test for this scenario ?

**Comment by brandond** [comment]
@ptabor go.sum should be fixed now. I added some tests for both sections of the codebase that I touched; hopefully that looks good? I'm not sure how to get codecov to update.

**Comment by ptabor** [comment]
Don't worry about code cov. 
There is inconsistency in go.mod's that break PASSES="fmt" ./test.sh

```
FAIL: inconsistent versions for depencency: go.uber.org/multierr
  - go.uber.org/multierr@v1.5.0 from: go.etcd.io/etcd/client/v3
  - go.uber.org/multierr@v1.6.0 from: go.etcd.io/etcd/server/v3
FAIL: inconsistent dependencies
```

**Comment by brandond** [comment]
I have no idea where any of that is coming from, the only go.mod that references multierr is in server. I'm going to see if squashing my changes and then doing a clean set of go.mod changes fixes this.

**Comment by brandond** [comment]
Well I fixed that but now CodeQL appears to be failing due to some transient github error?

**Comment by ptabor** [comment]
Thank you !
