### PR TITLE
Adjust time resolution to microseconds

### LINKED ISSUE #15236: Regression in timestamp resolution
### What happened?

If you compare timestamp of different loggers.
Like capnslog 
```
2023-02-02 13:50:27.813478 I | etcdmain: etcd Version: 3.4.23
2023-02-02 13:50:27.813518 I | etcdmain: Git SHA: e4b1542-FAILPOINTS
2023-02-02 13:50:27.813525 I | etcdmain: Go Version: go1.17.13
2023-02-02 13:50:27.813531 I | etcdmain: Go OS/Arch: linux/amd64
2023-02-02 13:50:27.813538 I | etcdmain: setting maximum number of CPUs to 24, total number of available CPUs is 24
2023-02-02 13:50:27.813547 W | etcdmain: no data-dir provided, using default data-dir ./default.etcd
2023-02-02 13:50:27.813603 N | etcdmain: the server is already initialized as member before, starting as etcd member...
2023-02-02 13:50:27.814080 I | embed: name = default
2023-02-02 13:50:27.814089 I | embed: data dir = default.etcd
2023-02-02 13:50:27.814103 I | embed: member dir = default.etcd/member
2023-02-02 13:50:27.814109 I | embed: heartbeat = 100ms
2023-02-02 13:50:27.814113 I | embed: election = 1000ms
2023-02-02 13:50:27.814118 I | embed: snapshot count = 100000
2023-02-02 13:50:27.814129 I | embed: advertise client URLs = http://localhost:2379
2023-02-02 13:50:27.814136 I | embed: initial advertise peer URLs = http://localhost:2380
2023-02-02 13:50:27.814142 I | embed: initial cluster = 
2023-02-02 13:50:27.815089 I | etcdserver: restarting member 8e9e05c52164694d in cluster cdf818194e3a8c32 at commit index 14
2023-02-02 13:50:27.817933 W | auth: simple token is not cryptographically signed
2023-02-02 13:50:27.824925 I | etcdserver: starting server... [version: 3.4.23, cluster version: to_be_decided]
2023-02-02 13:50:27.824988 I | pkg/fileutil: started to purge file, dir: default.etcd/member/snap, suffix: snap.db, max: 5, interval: 30s
2023-02-02 13:50:27.825004 I | pkg/fileutil: started to purge file, dir: default.etcd/member/snap, suffix: snap, max: 5, interval: 30s
2023-02-02 13:50:27.825016 I | pkg/fileutil: started to purge file, dir: default.etcd/member/wal, suffix: wal, max: 5, interval: 30s
2023-02-02 13:50:27.825457 I | etcdserver/membership: added member 8e9e05c52164694d [http://localhost:2380] to cluster cdf818194e3a8c32
2023-02-02 13:50:27.826120 N | etcdserver/membership: set the initial cluster version to 3.4
2023-02-02 13:50:27.826305 I | etcdserver/api: enabled capabilities for version 3.4
2023-02-02 13:50:27.828102 I | embed: listening for peers on 127.0.0.1:2380
```

And zap:
```
{"level":"warn","ts":"2023-02-02T13:52:04.214+0100","caller":"etcdmain/etcd.go:119","msg":"'data-dir' was empty; using default","data-dir":"default.etcd"}
{"level":"info","ts":"2023-02-02T13:52:04.214+0100","caller":"etcdmain/etcd.go:134","msg":"server has been already initialized","data-dir":"default.etcd","dir-type":"member"}
{"level":"info","ts":"2023-02-02T13:52:04.214+0100","caller":"embed/etcd.go:117","msg":"configuring peer listeners","listen-peer-urls":["http://localhost:2380"]}
{"level":"info","ts":"2023-02-02T13:52:04.214+0100","caller":"embed/etcd.go:127","msg":"configuring client listeners","listen-client-urls":["http://localhost:2379"]}
{"level":"info","ts":"2023-02-02T13:52:04.214+0100","caller":"embed/etcd.go:305","msg":"starting an etcd server","etcd-version":"3.4.23","git-sha":"e4b1542-FAILPOINTS","go-version":"go1.17.13","go-os":"linux","go-arch":"amd64","max-cpu-set":24,"max-cpu-available":24,"member-initialized":true,"name":"default","data-dir":"default.etcd","wal-dir":"","wal-dir-dedicated":"","member-dir":"default.etcd/member","force-new-cluster":false,"heartbeat-interval":"100ms","election-timeout":"1s","initial-election-tick-advance":true,"snapshot-count":100000,"max-wals":5,"max-snapshots":5,"snapshot-catchup-entries":5000,"initial-advertise-peer-urls":["http://localhost:2380"],"listen-peer-urls":["http://localhost:2380"],"advertise-client-urls":["http://localhost:2379"],"listen-client-urls":["http://localhost:2379"],"listen-metrics-urls":[],"cors":["*"],"host-whitelist":["*"],"initial-cluster":"","initial-cluster-state":"new","initial-cluster-token":"","quota-backend-bytes":2147483648,"max-request-bytes":1572864,"max-concurrent-streams":4294967295,"pre-vote":false,"initial-corrupt-check":false,"corrupt-check-time-interval":"0s","auto-compaction-mode":"periodic","auto-compaction-retention":"0s","auto-compaction-interval":"0s","discovery-url":"","discovery-proxy":""}
{"level":"info","ts":"2023-02-02T13:52:04.214+0100","caller":"etcdserver/backend.go:80","msg":"opened backend db","path":"default.etcd/member/snap/db","took":"86.873µs"}
{"level":"info","ts":"2023-02-02T13:52:04.215+0100","caller":"etcdserver/raft.go:586","msg":"restarting local member","cluster-id":"cdf818194e3a8c32","local-member-id":"8e9e05c52164694d","commit-index":16}
{"level":"info","ts":"2023-02-02T13:52:04.216+0100","caller":"raft/raft.go:1523","msg":"8e9e05c52164694d switched to configuration voters=()"}
{"level":"info","ts":"2023-02-02T13:52:04.216+0100","caller":"raft/raft.go:706","msg":"8e9e05c52164694d became follower at term 7"}
{"level":"info","ts":"2023-02-02T13:52:04.216+0100","caller":"raft/raft.go:389","msg":"newRaft 8e9e05c52164694d [peers: [], term: 7, commit: 16, applied: 0, lastindex: 16, lastterm: 7]"}
{"level":"warn","ts":"2023-02-02T13:52:04.226+0100","caller":"auth/store.go:1380","msg":"simple token is not cryptographically signed"}
{"level":"info","ts":"2023-02-02T13:52:04.231+0100","caller":"etcdserver/quota.go:98","msg":"enabled backend quota with default value","quota-name":"v3-applier","quota-size-bytes":2147483648,"quota-size":"2.1 GB"}
{"level":"info","ts":"2023-02-02T13:52:04.233+0100","caller":"etcdserver/server.go:816","msg":"starting etcd server","local-member-id":"8e9e05c52164694d","local-server-version":"3.4.23","cluster-version":"to_be_decided"}
{"level":"info","ts":"2023-02-02T13:52:04.233+0100","caller":"etcdserver/server.go:704","msg":"starting initial election tick advance","election-ticks":10}
{"level":"info","ts":"2023-02-02T13:52:04.233+0100","caller":"fileutil/purge.go:42","msg":"started to purge file","dir":"default.etcd/member/snap","suffix":"snap.db","max":5,"interval":"30s"}
{"level":"info","ts":"2023-02-02T13:52:04.233+0100","caller":"fileutil/purge.go:42","msg":"started to purge file","dir":"default.etcd/member/snap","suffix":"snap","max":5,"interval":"30s"}
{"level":"info","ts":"2023-02-02T13:52:04.233+0100","caller":"fileutil/purge.go:42","msg":"started to purge file","dir":"default.etcd/member/wal","suffix":"wal","max":5,"interval":"30s"}
{"level":"info","ts":"2023-02-02T13:52:04.233+0100","caller":"raft/raft.go:1523","msg":"8e9e05c52164694d switched to configuration voters=(10276657743932975437)"}
{"level":"info","ts":"2023-02-02T13:52:04.234+0100","caller":"membership/cluster.go:392","msg":"added member","cluster-id":"cdf818194e3a8c32","local-member-id":"8e9e05c52164694d","added-peer-id":"8e9e05c52164694d","added-peer-peer-urls":["http://localhost:2380"]}
{"level":"info","ts":"2023-02-02T13:52:04.234+0100","caller":"membership/cluster.go:558","msg":"set initial cluster version","cluster-id":"cdf818194e3a8c32","local-member-id":"8e9e05c52164694d","cluster-version":"3.4"}
{"level":"info","ts":"2023-02-02T13:52:04.235+0100","caller":"api/capability.go:76","msg":"enabled capabilities for version","cluster-version":"3.4"}
{"level":"info","ts":"2023-02-02T13:52:04.236+0100","caller":"embed/etcd.go:587","msg":"serving peer traffic","address":"127.0.0.1:2380"}
{"level":"info","ts":"2023-02-02T13:52:04.236+0100","caller":"embed/etcd.go:247","msg":"now serving peer/client/metrics","local-member-id":"8e9e05c52164694d","initial-advertise-peer-urls":["http://localhost:2380"],"listen-peer-urls":["http://localhost:2380"],"advertise-client-urls":["http://localhost:2379"],"listen-client-urls":["http://localhost:2379"],"listen-metrics-urls":[]}
{"level":"info","ts":"2023-02-02T13:52:05.717+0100","caller":"raft/raft.go:929","msg":"8e9e05c52164694d is starting a new election at term 7"}
{"level":"info","ts":"2023-02-02T13:52:05.717+0100","caller":"raft/raft.go:719","msg":"8e9e05c52164694d became candidate at term 8"}
{"level":"info","ts":"2023-02-02T13:52:05.717+0100","caller":"raft/raft.go:830","msg":"8e9e05c52164694d received MsgVoteResp from 8e9e05c52164694d at term 8"}
{"level":"info","ts":"2023-02-02T13:52:05.717+0100","caller":"raft/raft.go:771","msg":"8e9e05c52164694d became leader at term 8"}
{"level":"info","ts":"2023-02-02T13:52:05.717+0100","caller":"raft/node.go:327","msg":"raft.node: 8e9e05c52164694d elected leader 8e9e05c52164694d at term 8"}
{"level":"info","ts":"2023-02-02T13:52:05.727+0100","caller":"etcdserver/server.go:2077","msg":"published local member to cluster through raft","local-member-id":"8e9e05c52164694d","local-member-attributes":"{Name:default ClientURLs:[http://localhost:2379]}","request-path":"/0/members/8e9e05c52164694d/attributes","cluster-id":"cdf818194e3a8c32","publish-timeout":"7s"}
{"level":"info","ts":"2023-02-02T13:52:05.728+0100","caller":"embed/serve.go:145","msg":"serving client traffic insecurely; this is strongly discouraged!","address":"127.0.0.1:2379"}
```

We went from microsecond in capslogn to millisecond resolution in zap. This is a big problem as most centralized logging solutions use timestamp for ordering. If you look into zap logs timestamp it's pretty often that multiple logs are generated within the same millisecond.

cc @ahrtr @ptabor 

### What did you expect to happen?

I expect that zap logging also gives microsecond timestamp resolution

### How can we reproduce it (as minimally and precisely as possible)?

Run `./etcd --logger=capslogn` and `./etcd --logger=zap` on older versions that support both like v3.4.

### Anything else we need to know?

_No response_

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
etcd Version: 3.4.23
Git SHA: e4b1542
Go Version: go1.17.13
Go OS/Arch: linux/amd64
```

</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jmhbnz**
Historic capnslog timestamps are in microsecond resolution. We need to match that when we migrate to the zap logger.

The standard zap time encoder options are listed here: https://github.com/uber-go/zap/blob/077b03eb1c5f4ed0703209766e4c897bb88ae6fb/zapcore/encoder.go#L171 

Unfortunately none of these completely matched both the precision and format of the historic capnslog format so I've added a custom encoder function that matches exactly.  

Here is a comparison:

| Format | Example |
| ------------- | ------------- |
| Old capnslog  | 2023-02-02 13:50:27.813478 |
| Zap RFC3339NanoTimeEncoder  | 2023-02-03T20:08:58.299954658+13:00  |
| Zap RFC3339TimeEncoder  | 2023-02-03T20:09:52+13:00  |
| Zap EpochMillisTimeEncoder  | 1675408253432.4639  |
| Zap EpochNanosTimeEncoder  | 1675408290557930192 |
| Zap custom function | 2023-02-03 20:12:20.789477 |

Fixes #15236.

Edit: Here is a sample of the new log output:

```bash
 ➜ ./bin/etcd --logger=zap
{"level":"warn","ts":"2023-02-03 20:42:37.898898","caller":"embed/config.go:790","msg":"it isn't recommended to use default name, please set a value for --name. Note that etcd might run into 
issue when multiple members have the same default name","name":"default"}
{"level":"info","ts":"2023-02-03 20:42:37.898953","caller":"etcdmain/etcd.go:64","msg":"Running: ","args":["./bin/etcd","--logger=zap"]}
{"level":"warn","ts":"2023-02-03 20:42:37.898969","caller":"etcdmain/etcd.go:96","msg":"'data-dir' was empty; using default","data-dir":"default.etcd"}
{"level":"info","ts":"2023-02-03 20:42:37.898997","caller":"etcdmain/etcd.go:107","msg":"server has already been initialized","data-dir":"default.etcd","dir-type":"member"}
{"level":"warn","ts":"2023-02-03 20:42:37.899006","caller":"embed/config.go:790","msg":"it isn't recommended to use default name, please set a value for --name. Note that etcd might run into 
issue when multiple members have the same default name","name":"default"}
```

### CODE REVIEW

File: client/pkg/logutil/zap.go [hunk 1]
```diff
@@ -15,10 +15,10 @@
 package logutil
 
 import (
-	"sort"
-
 	"go.uber.org/zap"
 	"go.uber.org/zap/zapcore"
+	"sort"
+	"time"
```
Comment (ahrtr) [inline client/pkg/logutil/zap.go:21]:
```suggestion
	"sort"
	"time"

	"go.uber.org/zap"
	"go.uber.org/zap/zapcore"
```

**Comment by ahrtr** [comment]
Please squash the commits, and could you build & run etcd and paste a couple of the log message?

File: client/pkg/logutil/zap.go (hunk 1 above)
Comment (jmhbnz) [reply client/pkg/logutil/zap.go]: Fixed thanks, make verify told me to change this initially for some reason.

**Review by ahrtr — APPROVED** [review]
LGTM

Thanks @jmhbnz 

Could you backport this PR to release-3.5 and release-3.4?

**Comment by jmhbnz** [comment]
Thanks @ahrtr - Just want to double check the full e2e suite passes in case there are any tests that also need fixing etc.

Happy to help with backporting, what process does the `etcd` project follow to do that, are we just cherry picking a commit back to a release branch or something similar?  Thanks 🙏🏻

**Comment by ahrtr** [comment]
release-3.5 and 3.4 have very big different code structure, you'd better to backport the change manually.

**Comment by jmhbnz** [comment]
> release-3.5 and 3.4 have very big different code structure, you'd better to backport the change manually.

3.5 Backport raised #15240 

It looks like 3.4 didn't have any of the zap logger content, only 3.5 did so I'm not sure we need to take it back that far?

**Comment by ahrtr** [comment]
3.4: https://github.com/etcd-io/etcd/blob/b4e3ed72e377d090886531006ee4f297c339a6ad/pkg/logutil/zap.go#L46

File: client/pkg/logutil/zap.go [hunk 2]
```diff
@@ -46,15 +47,20 @@ var DefaultZapLoggerConfig = zap.Config{
...
+		NameKey:       "logger",
+		CallerKey:     "caller",
+		MessageKey:    "msg",
+		StacktraceKey: "stacktrace",
+		LineEnding:    zapcore.DefaultLineEnding,
+		EncodeLevel:   zapcore.LowercaseLevelEncoder,
+
+		// Custom EncodeTime function to ensure we match format and precision of historic capnslog timestamps
+		EncodeTime: func(t time.Time, enc zapcore.PrimitiveArrayEncoder) {
+			enc.AppendString(t.Format("2006-01-02 15:04:05.999999"))
```
Comment (serathius) [inline client/pkg/logutil/zap.go:61]:
```suggestion
			enc.AppendString(t.Format("2006-01-02T15:04:05.999999Z0700"))
```
To be able to backport this change we should not break the format. `ISO8601TimeEncoder` by zap gives millisecond precision, however ISO8601 standard itself doesn't specify maximum precision.

By just taking ISO8601 and adding decimal places, we can maintain backward compatibility to while increasing precision.

**Review by serathius — CHANGES_REQUESTED** [review]
Please don't make a breaking change

File: client/pkg/logutil/zap.go (hunk 2 above)
Comment (jmhbnz) [reply client/pkg/logutil/zap.go]: Thanks for the review and guidance @serathius. Updated to reflect.

**Comment by ptabor** [comment]
I would vote for `RFC3339NanoTimeEncoder` as the default for v3.6. It's 3 digits too long IMHO, but better than use standard than something custom just to have usec instead of nanos. 

For v3.4 & v3.5 we should have this flag driven to avoid a breaking change. So most likely flag in v3.6 as well
(just we a different default).

**Comment by serathius** [comment]
> I would vote for `RFC3339NanoTimeEncoder` as the default for v3.6. It's 3 digits too long IMHO, but better than use standard than something custom just to have usec instead of nanos. 

@ptabor Don't disagree, but we can make it a feature request handled in separate issue/PR?

**Comment by ptabor** [comment]
> > I would vote for `RFC3339NanoTimeEncoder` as the default for v3.6. It's 3 digits too long IMHO, but better than use standard than something custom just to have usec instead of nanos.
> 
> @ptabor Don't disagree, but we can make it a feature request handled in separate issue/PR?

I'm lost. Why would  we go over 2 changes of the same exact logic instead of deciding what's the expected end state ?

**Comment by ptabor** [comment]
2006-01-02T15:04:05.999999999Z07:00.     
To double check: 

@serathius Are you saying change: 
```
2006-01-02T15:04:05.000Z0700  ->   2006-01-02T15:04:05.999999Z0700
``` 
is backward compatible and can be backported - as it stays within ISO 8601 standard: 

```
YYYY-MM-DDThh:mm:ssTZD (eg 1997-07-16T19:20:30+01:00)
   Complete date plus hours, minutes, seconds and a decimal fraction of a
second

s    = one or more digits representing a decimal fraction of a second
```

while going to RFC3339 is breaking due timezone representation is breaking ? 

---- 
If so - seems acceptable. For v3.4 sounds a little brave.

**Comment by ptabor** [comment]
It's interesting that the old code using ISO8601TimeEncoder was writing: 
```2006-01-02T15:04:05.999999Z0700```
While according to ISO8601 (https://en.wikipedia.org/wiki/ISO_8601#Time_offsets_from_UTC) it should be: 
```2006-01-02T15:04:05.999999Z+07:00``

that's I assume the biggest risk to backward compatibility

**Comment by ahrtr** [comment]
> It's interesting that the old code using ISO8601TimeEncoder was writing: `2006-01-02T15:04:05.999999Z0700` While according to ISO8601 (https://en.wikipedia.org/wiki/ISO_8601#Time_offsets_from_UTC) it should be: `2006-01-02T15:04:05.999999Z+07:00`
> 
> that's I assume the biggest risk to backward compatibility

Does it mean that [ISO8601TimeEncoder](https://github.com/uber-go/zap/blob/077b03eb1c5f4ed0703209766e4c897bb88ae6fb/zapcore/encoder.go#L136) isn't compliant with standard? Probably we should raise an issue to zap?

**Comment by ahrtr** [comment]
Based on https://en.wikipedia.org/wiki/UTC_offset, all the following formats are valid,

```
 ±[hh]:[mm], ±[hh][mm], or ±[hh]
```

So `RFC3339NanoTimeEncoder` should be OK.

**Comment by ahrtr** [comment]
@jmhbnz Please move forward per the discussion above. 

- Use RFC3339NanoTimeEncoder for main branch;

**Comment by serathius** [comment]
> So RFC3339NanoTimeEncoder should be OK.
> @jmhbnz Please move forward per the discussion above.

Let's wait until there is a clear agreement on the topic.

Can we first summarize, what are the options, what issues we see in zap that should be reported and what is the preferred solution so everyone can agree on?

> @serathius Are you saying change:
> ```
>  2006-01-02T15:04:05.000Z0700  ->   2006-01-02T15:04:05.999999Z0700
> ```
> is backward compatible and can be backported - as it stays within ISO 8601 standard:

Yes, as [4.2.2.4 section of ISO 8601 standard](https://www.loc.gov/standards/datetime/iso-tc154-wg5_n0038_iso_wd_8601-1_2016-02-16.pdf) states about decimal fraction:
```
The interchange parties, dependent upon the application, shall agree the number of digits in the decimal
fraction. The format shall be [hhmmss,ss], [hhmm,mm] or[hh,hh] as appropriate (hour minute second, 
hour minute,  and  hour, respectively),  with as many digits as necessary following the decimal sign. A
decimal fraction shall have at least one digit. 
```

**Comment by ptabor** [comment]
For me the concern is the colon in timezone. 

For 3.4, 3.5 we should be using `2006-01-02T15:04:05.999999Z0700` (it's no colons in timezone)

For 3.6 I don't have strong opinion, but leaning towards the more standard (RFC3339NanoTimeEncoder): 
   "2006-01-02T15:04:05.999999999Z07:00"

**Comment by serathius** [comment]
Let's report lack of colon to zap people and see what they have to say about this.

**Comment by serathius** [comment]
Reading through https://www.loc.gov/standards/datetime/iso-tc154-wg5_n0038_iso_wd_8601-1_2016-02-16.pdf looks like zap made a strange choice to combine extended format (includes semicolon) and basic format (minimal representation without separators).

```
2.3.3
basic format
format of a date and time representation or date and time format representation comprising the	
minimum number of time elements necessary for the accuracy required
Note to entry: The basic format should be avoided in plain text.
2.3.4
extended format
extension of the basic format that includes additional separators
```

**Review by serathius — APPROVED** [review]
