### PR TITLE
Client: fix check for WithPrefix op

### LINKED ISSUE #14056: Client: IsOptsWithPrefix returns false even if WithPrefix() is included
### What happened?

If you use the function `IsOptsWithPrefix` with opts containing `WithPrefix()` it always returns `false` instead of true.

### What did you expect to happen?

`IsOptsWithPrefix` should return true if `opts` contains `WithPrefix()`

### How can we reproduce it (as minimally and precisely as possible)?

```go
package main

import (
  "log"
  etcd "go.etcd.io/etcd/client/v3"
)

func main() {
  log.Printf("%v", etcd.IsOptsWithPrefix([]etcd.OpOption{etcd.WithPrefix()}))
}
```

Logs `false` instead of `true`

### Anything else we need to know?

`IsOptsWithPrefix` creates an empty op with `NewOp` which sets a key with len 0. Therefore the len check in `WithPrefix` also is true and the flag is not set.

### Etcd version (please run commands below)

Not related to etcd backend, only client. Tested versions: v3.5.4, v3.6.0-alpha.0

### Etcd configuration (command line flags or environment variables)

_No response_

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by spzala**
Make sure that WithPrefix correctly set the flag, and add test.
Also, add test for WithFromKey.

fixes #14056

### CODE REVIEW

**Comment by spzala** [comment]
cc @serathius @ptabor @ahrtr

File: client/v3/op.go [hunk 1]
```diff
@@ -391,6 +391,7 @@ func WithPrefix() OpOption {
 	return func(op *Op) {
 		if len(op.key) == 0 {
 			op.key, op.end = []byte{0}, []byte{0}
+			op.isOptsWithPrefix = true
```
Comment (ahrtr) [inline client/v3/op.go:394]: minor comment: Both line 394 and 397 set `isOptsWithPrefix` as `true`, so I suggest to move 			`op.isOptsWithPrefix = true` to the beginning of the function.

Comment (spzala) [reply client/v3/op.go]: @ahrtr Good catch, I missed it. Thanks!

**Review by ahrtr — APPROVED** [review]
LGTM

**Review by serathius — APPROVED** [review]

**Comment by spzala** [comment]
@ahrtr @serathius thanks for the quick review! Build is green so merging.
