### PR TITLE
antithesis: replaced Reachable/Unreachable assertion with Always

### LINKED ISSUE #19885: [Antithesis] Use `Always` assertion instead of `Reachable/Unreachable`
### What would you like to be added?

Replace https://github.com/etcd-io/etcd/blob/297e9d1d586a12388c8ec49d3bf5e36803064ae0/tests/antithesis/test-template/robustness/main.go#L67-L73 with 
```
assert.Always(result.Error == nil, "Robustness validation failed", map[string]any{"error": result.Error})
```

### Why is this needed?

Simplifies code
/cc @nwnt @henrybear327 @abdurrehman107

### PR DESCRIPTION
**Pull request by subrajeet-maharana**
Fixes #19885

### CODE REVIEW

File: tests/antithesis/test-template/robustness/main.go [hunk 1]
```diff
@@ -82,13 +82,8 @@ func testRobustness(ctx context.Context, hosts []string, baseTime time.Time, dur
 	if err != nil {
 		lg.Error("Failed to save visualization", zap.Error(result.Error))
 	}
-	if result.Error != nil {
-		lg.Error("Robustness validation failed", zap.Error(result.Error))
-		assert.Unreachable("Robustness validation failed", map[string]any{"error": result.Error})
-		return
-	}
+	assert.Always(result.Error == nil, "Robustness validation failed", map[string]any{"error": result.Error})
```
Comment (serathius) [inline tests/antithesis/test-template/robustness/main.go:85]:
```suggestion
	assert.Always(result.Error == nil, "Robustness validation doesn't return error", map[string]any{"error": result.Error})
```

File: tests/antithesis/test-template/robustness/main.go [hunk 2]
```diff
@@ -82,7 +82,7 @@ func testRobustness(ctx context.Context, hosts []string, baseTime time.Time, dur
 	if err != nil {
 		lg.Error("Failed to save visualization", zap.Error(result.Error))
 	}
-	assert.Always(result.Error == nil, "Robustness validation failed", map[string]any{"error": result.Error})
+	assert.Always(result.Error == nil, "Robustness validation passes", map[string]any{"error": result.Error})
 	lg.Info("Completed robustness validation")
```
Comment (serathius) [inline tests/antithesis/test-template/robustness/main.go:86]:
```suggestion
	lg.Info("Completed robustness validation", zap.Error(result.Error))
```

**Comment by joshjms** [comment]
Please squash the commits

File: tests/antithesis/test-template/robustness/main.go (hunk 2 above)
Comment (serathius) [reply tests/antithesis/test-template/robustness/main.go:86]: Assertion is just for antithesis system, by itself doesn't show up in logs. This means if we run it locally we will not see the error.

File: tests/antithesis/test-template/robustness/main.go [hunk 3]
```diff
@@ -82,7 +82,7 @@ func testRobustness(ctx context.Context, hosts []string, baseTime time.Time, dur
 	if err != nil {
 		lg.Error("Failed to save visualization", zap.Error(result.Error))
```
Comment (serathius) [inline tests/antithesis/test-template/robustness/main.go:83]:
```suggestion
		lg.Error("Failed to save visualization", zap.Error(err))
```

Comment (serathius) [reply tests/antithesis/test-template/robustness/main.go:83]: Ups, we report wrong error.

File: tests/antithesis/test-template/robustness/main.go (hunk 2 above)
Comment (serathius) [reply tests/antithesis/test-template/robustness/main.go:86]: Can you fix this?

**Review by serathius — APPROVED** [review]
