### PR TITLE
server: Director can be stopped

### LINKED ISSUE #14021: panic: Log in goroutine after TestNewDirectorScheme has completed
I see this panic multiple times. 

It's an issue on the main branch, but probably previous releases have this issue as well. Let's fix it in main branch firstly.  See also [step:5:1022](https://github.com/etcd-io/etcd/runs/6332845004?check_suite_focus=true#step:5:1022)

The [goroutine](https://github.com/etcd-io/etcd/blob/b7be91f98b7a7a6202ed9e9bc37b692d484585a8/server/proxy/httpproxy/director.go#L46-L71) is out of control once it being created. We need to figure out a solution to make it under control. 

```

panic: Log in goroutine after TestNewDirectorScheme has completed: 2022-05-07T06:52:44.542Z	INFO	endpoints found	{"endpoints": ["http://example.com:8080/", "http://192.0.2.8:4002/"]}

goroutine 13 [running]:
testing.(*common).logDepth(0x8c00f00, {0x8c26600, 0x71}, 0x3)
	/opt/hostedtoolcache/go/1.17.8/x64/src/testing/testing.go:779 +0x482
testing.(*common).log(...)
	/opt/hostedtoolcache/go/1.17.8/x64/src/testing/testing.go:761
testing.(*common).Logf(0x8c00f00, {0x83d6620, 0x2}, {0x8c0daf8, 0x1, 0x1})
	/opt/hostedtoolcache/go/1.17.8/x64/src/testing/testing.go:807 +0x65
go.uber.org/zap/zaptest.testingWriter.Write({{0x845c2f4, 0x8c00f00}, 0x0}, {0x8d9c800, 0x72, 0x400})
	/home/runner/go/pkg/mod/go.uber.org/zap@v1.17.0/zaptest/logger.go:130 +0xee
go.uber.org/zap/zapcore.(*ioCore).Write(0x8d02888, {0x0, {0xc095a3af2057fbdf, 0x27395f, 0x8688a20}, {0x0, 0x0}, {0x83da80c, 0xf}, {0x0, ...}, ...}, ...)
	/home/runner/go/pkg/mod/go.uber.org/zap@v1.17.0/zapcore/core.go:90 +0xac
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0x8c67b90, {0x8c58e10, 0x1, 0x1})
	/home/runner/go/pkg/mod/go.uber.org/zap@v1.17.0/zapcore/entry.go:220 +0x1e8
go.uber.org/zap.(*Logger).Info(0x8c589f0, {0x83da80c, 0xf}, {0x8c58e10, 0x1, 0x1})
	/home/runner/go/pkg/mod/go.uber.org/zap@v1.17.0/logger.go:189 +0x5e
go.etcd.io/etcd/server/v3/proxy/httpproxy.newDirector.func1.1()
	/home/runner/work/etcd/etcd/server/proxy/httpproxy/director.go:65 +0x1e6
sync.(*Once).doSlow(0x869cba8, 0x8c34fc8)
	/opt/hostedtoolcache/go/1.17.8/x64/src/sync/once.go:68 +0x93
sync.(*Once).Do(0x869cba8, 0x8c34fc8)
	/opt/hostedtoolcache/go/1.17.8/x64/src/sync/once.go:59 +0x3f
go.etcd.io/etcd/server/v3/proxy/httpproxy.newDirector.func1(0x8c58a20, 0xdf8475800, 0x8c589f0)
	/home/runner/work/etcd/etcd/server/proxy/httpproxy/director.go:60 +0xe4
created by go.etcd.io/etcd/server/v3/proxy/httpproxy.newDirector
	/home/runner/work/etcd/etcd/server/proxy/httpproxy/director.go:46 +0x1c3
FAIL	go.etcd.io/etcd/server/v3/proxy/httpproxy	0.007s
```

### PR DESCRIPTION
**Pull request by caproven**
Goroutine for new directors would live past director scope. Tests
could occasionally fail if this goroutine had log events after
test execution should have ended.

Fixes #14021

### CODE REVIEW

**Comment by caproven** [comment]
With these changes, I've seen the tests passing consistently with GOMAXPROCS=1 (see https://github.com/etcd-io/etcd/issues/14021#issuecomment-1123154617).

```
❯ GOMAXPROCS=1 go test ./proxy/httpproxy -count=300000
ok      go.etcd.io/etcd/server/v3/proxy/httpproxy       45.706s
```
```
❯ go test ./proxy/httpproxy -count=300000
ok      go.etcd.io/etcd/server/v3/proxy/httpproxy       42.044s
```

**Comment by caproven** [comment]
@ahrtr I saw that some test errors surfaced (see https://github.com/etcd-io/etcd/runs/6382325888?check_suite_focus=true#step:5:667). I could not find any direct relation to the PR changes, should I investigate this further?

File: server/proxy/httpproxy/director.go [hunk 1]
```diff
@@ -33,7 +33,7 @@ func init() {
 	rand.Seed(time.Now().UnixNano())
 }
 
-func newDirector(lg *zap.Logger, urlsFunc GetProxyURLs, failureWait time.Duration, refreshInterval time.Duration) *director {
+func newDirector(lg *zap.Logger, urlsFunc GetProxyURLs, failureWait time.Duration, refreshInterval time.Duration, stop <-chan struct{}, donec chan<- struct{}) *director {
```
Comment (ahrtr) [inline server/proxy/httpproxy/director.go:36]: `stop` -> `stopc` so as to be consistent with `donc`?

File: server/proxy/httpproxy/director_test.go [hunk 2]
```diff
@@ -55,7 +55,8 @@ func TestNewDirectorScheme(t *testing.T) {
 		uf := func() []string {
 			return tt.urls
 		}
-		got := newDirector(zaptest.NewLogger(t), uf, time.Minute, time.Minute)
+		stop, donec := make(chan struct{}), make(chan struct{})
```
Comment (ahrtr) [inline server/proxy/httpproxy/director_test.go:58]: same as above, `stopc`.

**Comment by ahrtr** [comment]
Thanks @caproven for the fix. I agree this PR can resolve the test failure. 

But you only fix the test failure, I would suggest to fix the production code as well. Proposed changes:
1. wrap the `donec` and `stopc` in the [director](https://github.com/etcd-io/etcd/blob/5fd69102ce785136aeb3168c56adce7957b99e2d/server/proxy/httpproxy/director.go#L75);
2. Register a interrupt handler using [RegisterInterruptHandler](https://github.com/etcd-io/etcd/blob/5fd69102ce785136aeb3168c56adce7957b99e2d/pkg/osutil/interrupt_unix.go#L42) , and stop the [goroutine](https://github.com/etcd-io/etcd/blob/5fd69102ce785136aeb3168c56adce7957b99e2d/server/proxy/httpproxy/director.go#L46) in the handler.

**Comment by ahrtr** [comment]
> @ahrtr I saw that some test errors surfaced (see https://github.com/etcd-io/etcd/runs/6382325888?check_suite_focus=true#step:5:667). I could not find any direct relation to the PR changes, should I investigate this further?

Yes, the failure should have nothing to do with this PR. There are indeed some flaky test. Let's continue to work on this PR.

File: server/proxy/httpproxy/director.go (hunk 1 above)
Comment (caproven) [reply server/proxy/httpproxy/director.go:36]: Agreed. With the suggestion of wrapping `stopc` and `donec` in director, this consistency looks much nicer.

File: server/proxy/httpproxy/director.go [hunk 3]
```diff
@@ -33,20 +34,23 @@ func init() {
...
 	}
 	d := &director{
 		lg:          lg,
 		uf:          urlsFunc,
 		failureWait: failureWait,
+		stopc:       make(chan struct{}),
+		donec:       make(chan struct{}),
 	}
+	osutil.RegisterInterruptHandler(func() {
+		close(d.stopc)
```
Comment (caproven) [inline server/proxy/httpproxy/director.go:49]: This at least tells the goroutine to stop. Should it also wait for it to finish (read from `donec`)?

Comment (caproven) [inline server/proxy/httpproxy/director.go:49]: I don't think it would be problematic, but looking for input. The tests also close `stopc` - should this handler accommodate the channel already being closed?

Comment (ahrtr) [reply server/proxy/httpproxy/director.go:49]: I think yes. We should wait, such as 1 second. 

It's better to get the handler included in a method, so that the unit test case can use as well.

Comment (ahrtr) [reply server/proxy/httpproxy/director.go:49]: After second thought, I think it makes more sense to register the interrupt handler in higher level. It seems that it needs a little refactor, let me handle it. Please get this handler included in a method.

**Comment by ahrtr** [comment]
I just realized that v2server and v2 commands have already been removed. I don't see any reason to keep the [v2httpproxy](https://github.com/etcd-io/etcd/tree/main/server/proxy/httpproxy). It can also greatly simply the code base cc @ptabor @serathius @spzala  WDYT?

File: server/proxy/httpproxy/director.go [hunk 4]
```diff
@@ -41,9 +42,13 @@ func newDirector(lg *zap.Logger, urlsFunc GetProxyURLs, failureWait time.Duratio
 		lg:          lg,
 		uf:          urlsFunc,
 		failureWait: failureWait,
+		stopc:       make(chan struct{}),
+		donec:       make(chan struct{}),
 	}
+	osutil.RegisterInterruptHandler(d.stop)
```
Comment (ahrtr) [inline server/proxy/httpproxy/director.go:48]: Please remove this for now, and let upper layer to handle the interrupt handler. 

We might also be totally removing the v2 http proxy.

File: server/proxy/httpproxy/director.go (hunk 3 above)
Comment (caproven) [reply server/proxy/httpproxy/director.go]: No worries, thanks for thinking through this. I've since removed the interrupt handler registration.

**Review by ahrtr — APPROVED** [review]
LGTM

This PR should be good to go for now. We can take care of the v2httpproxy removal in a separate PR. cc @ptabor @serathius @spzala

**Comment by ahrtr** [comment]
Since the PR [14034](https://github.com/etcd-io/etcd/pull/14034) have been approved, so let me merge this one to honor the @caproven 's effort.
