### PR TITLE
auth: fix NoPassWord check when add user

### LINKED ISSUE #11414: GRPC Gateway authentication fails on version v3.4.*
I followed the doc here https://github.com/etcd-io/etcd/blob/v3.4.3/Documentation/dev-guide/api_grpc_gateway.md

Run this exact script from the doc:

```bash
# create root user
curl -L http://localhost:2379/v3/auth/user/add \
  -X POST -d '{"name": "root", "password": "pass"}'
# {"header":{"cluster_id":"14841639068965178418","member_id":"10276657743932975437","revision":"1","raft_term":"2"}}

# create root role
curl -L http://localhost:2379/v3/auth/role/add \
  -X POST -d '{"name": "root"}'
# {"header":{"cluster_id":"14841639068965178418","member_id":"10276657743932975437","revision":"1","raft_term":"2"}}

# grant root role
curl -L http://localhost:2379/v3/auth/user/grant \
  -X POST -d '{"user": "root", "role": "root"}'
# {"header":{"cluster_id":"14841639068965178418","member_id":"10276657743932975437","revision":"1","raft_term":"2"}}

# enable auth
curl -L http://localhost:2379/v3/auth/enable -X POST -d '{}'
# {"header":{"cluster_id":"14841639068965178418","member_id":"10276657743932975437","revision":"1","raft_term":"2"}}

# get the auth token for the root user
curl -L http://localhost:2379/v3/auth/authenticate \
  -X POST -d '{"name": "root", "password": "pass"}'
# {"header":{"cluster_id":"14841639068965178418","member_id":"10276657743932975437","revision":"1","raft_term":"2"},"token":"sssvIpwfnLAcWAQH.9"}

```

And I get these result

```plain
{"header":{"cluster_id":"11588568905070377092","member_id":"128088275939295631","revision":"1","raft_term":"2"}}{"header":{"cluster_id":"11588568905070377092","member_id":"128088275939295631","revision":"1","raft_term":"2"}}{"header":{"cluster_id":"11588568905070377092","member_id":"128088275939295631","revision":"1","raft_term":"2"}}{"header":{"cluster_id":"11588568905070377092","member_id":"128088275939295631","revision":"1","raft_term":"2"}}{"error":"etcdserver: authentication failed, invalid user ID or password","message":"etcdserver: authentication failed, invalid user ID or password","code":3}
```

Somehow I cannot add user using grpc gayway.

And:
- Only happens with version >= v3.4.0
- If I add user using etcdctl, the auth (gen token) api through grpc gatway works well

### PR DESCRIPTION
**Pull request by YoyinZyc**
fix #11414
There is one more concern about the usage of `NoPassword`. If the user is created like `etcdctl user add user:`, should it be inferred as no password? 
@jingyih PHAL

### CODE REVIEW

**Comment by jingyih** [comment]
Could we add an e2e test to mimic the work flow reported in the original issue? I am surprised that the bug was not caught by test.

**Comment by jingyih** [comment]
The fix looks good to me.

**Comment by YoyinZyc** [comment]
> Could we add an e2e test to mimic the work flow reported in the original issue? I am surprised that the bug was not caught by test.

SGTM. I will add more tests for `NoPassword`

File: tests/e2e/v3_curl_test.go [hunk 1]
```diff
@@ -274,6 +279,63 @@ func testV3CurlAuth(cx ctlCtx) {
 	}
 }
 
+func testV3CurlAuthWithoutOption(cx ctlCtx) {
```
Comment (jingyih) [inline tests/e2e/v3_curl_test.go]: Can we explore the option of modifying the existing `testV3CurlAuth` e2e test to include both w/ and w/o user option cases?

**Comment by jingyih** [comment]
cc @mitake

**Comment by mitake** [comment]
LGTM, thanks @YoyinZyc ! If @jingyih is ok with `TestV3CurlAuthWithoutOption`, I think it's ok to merge (I have no strong opinions about it).

It is not limited to this bug but I feel we should have a testing framework which can detect issues related to protobuf update (it might be useful for validating upgrading and downgrading an etcd cluster with different versions).

**Comment by jingyih** [comment]
> It is not limited to this bug but I feel we should have a testing framework which can detect issues related to protobuf update (it might be useful for validating upgrading and downgrading an etcd cluster with different versions).

Today there are some upgrade e2e tests. I believe in #11362 we are adding some downgrade e2e tests. But in these tests we do not exercise all possible APIs. So I agree, having a framework that supports version skew sounds good to me.

**Comment by jingyih** [comment]
Thanks for adding a new test case. I think this is fine. Let's also backport to 3.4.
