### PR TITLE
clientV3watch: do not return ctx canceled when Close watch

### LINKED ISSUE #10340: Closing Watcher always returns "context canceled"
Example:
```
watcher := clientv3.NewWatcher(etcdClient)
channel := watcher.Watch(context.Background(), "test") 
err := watcher.Close()
if err == context.Caneled {
    fmt.Println("this always happens")
}
```

Is this the expected behavior?  I thought for a time it was failing to close the watch, but looking at a profiler, that doesn't seem to be the case.  It was just misleading.

### PR DESCRIPTION
**Pull request by spzala**
Closing of watch by client will cancel the watch grpc stream and
can produce a context canceled error. However, since client
simply wanted to close the watcher the error can create confusion
that something went wrong instead of a successful close. Ensure
that Close do not return ctx canceled error.

Fixed #10340

### CODE REVIEW

File: clientv3/watch.go [hunk 1]
```diff
@@ -371,6 +371,9 @@ func (w *watcher) Close() (err error) {
 			err = werr
 		}
 	}
+	if err == context.Canceled {
+		return fmt.Errorf("Context canceled as expected")
+	}
 	return err
```
Comment (hexfusion) [inline clientv3/watch.go]: Are there situations where context would be canceled here but not expected?

**Comment by hexfusion** [comment]
@spzala thanks for the PR! Can you please rebase with master?

File: clientv3/watch.go (hunk 1 above)
Comment (spzala) [reply clientv3/watch.go]: I think that's the case right now that it's canceled but not expected by end user. https://github.com/etcd-io/etcd/blob/master/clientv3/watch.go#L414

**Comment by spzala** [comment]
@hexfusion thanks, rebased!

File: clientv3/watch.go (hunk 1 above)
Comment (hexfusion) [reply clientv3/watch.go]: I understand I just mean are there possible corner cases in your experience where this error message would not be appropriate. I am only asking because I have not dug into this.

Comment (spzala) [reply clientv3/watch.go]: Thanks @hexfusion  So far playing with it, I believe this message covers both cases - one where it's displayed without user being explicitly canceling it (i.e. by calling Close which seems most common case) and second if there is anyway context was canceled by user (I wonder why anyone would do this but just thinking as a possible case).

**Comment by hexfusion** [comment]
@gyuho PTAL this seems fine to me but maybe you have ideas on corner cases?

**Comment by gyuho** [comment]
I think `context.Canceled` is already clear enough to tell that it's user-triggered.

**Comment by spzala** [comment]
> I think `context.Canceled` is already clear enough to tell that it's user-triggered.
Hi @gyuho so the issue this PR tries to solve is when user call Close() it gives context.Canceled which is confusing in that it seems like user did something wrong instead of successfully closing the watch (per the original issue). Since Close() calls cancel() underneath, this PR is a try to make it more clear that the error is expected. Not sure if it's a good solution or needed but that's why I wanted to discuss it with you and Sam :-)  Thanks!

File: clientv3/watch.go [hunk 2]
```diff
@@ -371,6 +371,9 @@ func (w *watcher) Close() (err error) {
 			err = werr
 		}
 	}
+	if err == context.Canceled {
+		return fmt.Errorf("Context canceled as expected")
```
Comment (spzala) [inline clientv3/watch.go]: I feel like we should return nil here as context cancel is expected with a related message as here, so that end user see call to the Close() as success instead of one returned with error. Just a thought as we are discussing the PR. Thanks!

**Comment by jingyih** [comment]
If watcher.Close() closes the watcher as expected, shouldn't it return no error?
/cc @jpbetz

**Comment by spzala** [comment]
A gentle reminder for review :-) As @jingyih and I commented earlier, we should probably return no error. @hexfusion @gyuho

**Comment by gyuho** [comment]
> since client simply wanted to close the watcher the error might create confusion

@spzala While I agree with you, we should not introduce a new error value. User would need to handle another error string `"Context canceled as expected"`.

`context.Canceled` is widely used in Go.

So long as we document clearly, we should just keep the old behavior.

I would rather update the godoc here https://github.com/etcd-io/etcd/blob/master/clientv3/watch.go#L45.

**Comment by spzala** [comment]
@gyuho thanks and agree! I was leaning towards not throwing error at all, but updating doc sounds good too, will update PR accordingly.

**Comment by spzala** [comment]
@gyuho @hexfusion does the doc clarification look good? Thanks!

**Comment by xiang90** [comment]
@spzala 

If the user calls Close directly (instead of closing the context, then call Close), Close should not return an error.

**Comment by spzala** [comment]
@xiang90 thanks and I agree that would be ideal, that was my and @jingyih 's earlier thought too. @gyuho I agree that doc changes are non-harmful and adds clarity, but let's try not to return error if you think there is no harm in doing that? I will update PR accordingly. Thanks!

**Comment by xiang90** [comment]
lgtm

**Comment by spzala** [comment]
Thanks @xiang90 !!

**Comment by jingyih** [comment]
Thanks for fixing this:)
