### PR TITLE
etcdserver: add learner check to readyz

### LINKED ISSUE #19001: Make the readiness check fail for learner
### What would you like to be added?

RPC read and write operations are not supported for learners, so the `readyz` check should fail for the learner.

### Why is this needed?

When the etcd cluster is running in Kubernetes, the learner's  readiness probe should fail. #16007

### PR DESCRIPTION
**Pull request by gojoy**
fix  #19001

### CODE REVIEW

**Comment by gojoy** [comment]
@siyuanfoundation Hi. Can you review this request

**Comment by siyuanfoundation** [comment]
lgtm overall. Can you fix the tiny error in the verify test? 
Thanks!

**Comment by gojoy** [comment]
> lgtm overall. Can you fix the tiny error in the verify test? Thanks!

done

**Comment by gojoy** [comment]
> lgtm overall. Can you fix the tiny error in the verify test? Thanks!

error in the verify test has been fixed. please review again @siyuanfoundation

**Comment by gojoy** [comment]
Hi ,Can you review this request? Thanks! @siyuanfoundation

**Review by siyuanfoundation — APPROVED** [review]

File: server/etcdserver/api/etcdhttp/health.go [hunk 1]
```diff
@@ -252,6 +253,8 @@ func installReadyzEndpoints(lg *zap.Logger, mux *http.ServeMux, server ServerHea
 	reg.Register("serializable_read", readCheck(server, true))
 	// linearizable_read check would be replaced by read_index check in 3.6
 	reg.Register("linearizable_read", readCheck(server, false))
+	// check if local is learner
+	reg.Register("learner", learnerCheck(server))
```
Comment (ahrtr) [inline server/etcdserver/api/etcdhttp/health.go:257]: Let's be clearer. `/readyz/learner` isn't clear what's it's for.

```suggestion
	reg.Register("non-learner", learnerCheck(server))
```

Comment (gojoy) [reply server/etcdserver/api/etcdhttp/health.go]: > Let's be clearer. `/readyz/learner` isn't clear what's it's for.

done

**Review by ahrtr — APPROVED** [review]
LGTM

Thank you!

**Review by serathius — APPROVED** [review]
