### PR TITLE
rafthttp: add 3.4.0,3.5.0 stream type

### LINKED ISSUE #11264: Cannot upgrade cluster from 3.4 to 3.5.
I followed the [upgrade instruction](https://github.com/etcd-io/etcd/blob/master/Documentation/upgrades/upgrade_3_5.md) to upgrade the cluster from 3.4 to 3.5. The cluster is unhealthy when it has 3.4 nodes and 3.5 nodes.
Here are my findings:

1. when I stop one 3.4 node and restart it with 3.5, the 3.5 node cannot be published and keeps sending vote request to other two servers. The 3.5 node is unhealthy while another two are healthy. Here is the log of the 3.5 node.
> {"level":"warn","ts":"2019-10-16T11:44:33.748-0700","caller":"etcdserver/server.go:2045","msg":"failed to publish local member to cluster through raft","local-member-id":"91bc3c398fb3c146","local-member-attributes":"{Name:infra2 ClientURLs:[http://127.0.0.1:22379]}","request-path":"/0/members/91bc3c398fb3c146/attributes","publish-timeout":"7s","error":"etcdserver: request timed out"}
{"level":"info","ts":"2019-10-16T11:44:33.935-0700","caller":"raft/raft.go:923","msg":"91bc3c398fb3c146 is starting a new election at term 21"}
{"level":"info","ts":"2019-10-16T11:44:33.935-0700","caller":"raft/raft.go:713","msg":"91bc3c398fb3c146 became candidate at term 22"}
{"level":"info","ts":"2019-10-16T11:44:33.935-0700","caller":"raft/raft.go:824","msg":"91bc3c398fb3c146 received MsgVoteResp from 91bc3c398fb3c146 at term 22"}
{"level":"info","ts":"2019-10-16T11:44:33.935-0700","caller":"raft/raft.go:811","msg":"91bc3c398fb3c146 [logterm: 12, index: 9] sent MsgVote request to 8211f1d0f64f3269 at term 22"}
{"level":"info","ts":"2019-10-16T11:44:33.935-0700","caller":"raft/raft.go:811","msg":"91bc3c398fb3c146 [logterm: 12, index: 9] sent MsgVote request to fd422379fda50e48 at term 22"}
{"level":"info","ts":"2019-10-16T11:44:35.435-0700","caller":"raft/raft.go:923","msg":"91bc3c398fb3c146 is starting a new election at term 22"}
>
Another two 3.4 servers will ignore the vote request.
>{"level":"info","ts":"2019-10-16T11:44:33.944-0700","caller":"raft/raft.go:844","msg":"8211f1d0f64f3269 [logterm: 12, index: 9, vote: 8211f1d0f64f3269] ignored MsgVote from 91bc3c398fb3c146 [logterm: 12, index: 9] at term 12: lease is not expired (remaining ticks: 10)"}
>
2. when I stop the another 3.4 node and restart it with 3.5, the two 3.5 nodes become healthy but the 3.4 node is unhealthy. Here is the log of 3.4 node.
>{"level":"warn","ts":"2019-10-16T12:09:44.872-0700","caller":"etcdserver/util.go:144","msg":"apply request took too long","took":"4.997634337s","expected-duration":"100ms","prefix":"read-only range ","request":"key:\"health\" ","response":"","error":"context canceled"}
{"level":"warn","ts":"2019-10-16T12:09:46.875-0700","caller":"etcdserver/v3_server.go:708","msg":"timed out waiting for read index response (local node might have slow network)","timeout":"7s"}
>

3. Everything works well if I upgrade the cluster from 3.3 to 3.4 and from 3.3 to 3.5.
[m1.log](https://github.com/etcd-io/etcd/files/3736894/m1.log)
[m2.log](https://github.com/etcd-io/etcd/files/3736898/m2.log)
[m3.log](https://github.com/etcd-io/etcd/files/3736899/m3.log)
[operation.txt](https://github.com/etcd-io/etcd/files/3736906/operation.txt)

### PR DESCRIPTION
**Pull request by YoyinZyc**
Fix #11264 
Basically, the bug is due to the failure of `checkStreamSupport`. We need to add stream support to 3.4 and 3.5.
https://github.com/etcd-io/etcd/blob/51b1677d9944e0b28b6b04fab2a64b7a39fe9254/etcdserver/api/rafthttp/stream.go#L635

### CODE REVIEW

**Comment by YoyinZyc** [comment]
@gyuho

**Comment by YoyinZyc** [comment]
cc @wenjiaswe @jingyih

**Comment by wenjiaswe** [comment]
@YoyinZyc thanks for fixing! So the recently cut v3.4.2 missed the supportedStream, would you also please add there as well? https://github.com/etcd-io/etcd/blob/bbe86b066c0c714fa2a17ee93a37882553cf2394/etcdserver/api/rafthttp/stream.go#L59

I will wait for a new 3.4 release then upgrade etcd to the new release: https://github.com/kubernetes/kubernetes/pull/83987

**Comment by YoyinZyc** [comment]
> Yuchen Zhou thanks for fixing! So the recently cut v3.4.2 missed the supportedStream, would you also please add there as well?
> 
> https://github.com/etcd-io/etcd/blob/bbe86b066c0c714fa2a17ee93a37882553cf2394/etcdserver/api/rafthttp/stream.go#L59
> 
> I will wait for a new 3.4 release then upgrade etcd to the new release: [kubernetes/kubernetes#83987](https://github.com/kubernetes/kubernetes/pull/83987)

I added it to 3.4 in another pr #11275

File: etcdserver/api/rafthttp/stream.go [hunk 1]
```diff
@@ -57,6 +57,8 @@ var (
 		"3.1.0": {streamTypeMsgAppV2, streamTypeMessage},
 		"3.2.0": {streamTypeMsgAppV2, streamTypeMessage},
 		"3.3.0": {streamTypeMsgAppV2, streamTypeMessage},
+		"3.4.0": {streamTypeMsgAppV2, streamTypeMessage},
+		"3.5.0": {streamTypeMsgAppV2, streamTypeMessage},
```
Comment (jpbetz) [inline etcdserver/api/rafthttp/stream.go]: Let's write a test that fails if there is not entry in this map for the current etcd major version on master.

Comment (jpbetz) [reply etcdserver/api/rafthttp/stream.go]: That way it's impossible to forget to update this and have a passing build.

Comment (YoyinZyc) [reply etcdserver/api/rafthttp/stream.go]: SGTM

**Comment by jingyih** [comment]
LGTM

**Comment by jingyih** [comment]
Test was added in #11279. I am merging this so the test can pass after rebase.
