### PR TITLE
embed: TestStartEtcdWrongToken now uses dynamic ports instead of default

### LINKED ISSUE #11956: TestStartEtcdWrongToken fails if another etcd is running
On Debian CI (see https://ci.debian.net/data/autopkgtest/unstable/amd64/e/etcd/5695459/log.gz) using etcd-3.2.26 for now (but there is no indication this should be different for master), `TestStartEtcdWrongToken` fails if another etcd is running already:

```
=== RUN   TestStartEtcdWrongToken
    TestStartEtcdWrongToken: serve_test.go:36: expected auth: invalid auth options, got listen tcp 127.0.0.1:2380: bind: address already in use
--- FAIL: TestStartEtcdWrongToken (0.00s)
FAIL
FAIL	github.com/coreos/etcd/embed	0.014s
```

I think all(?) the other tests use random/incremental ports and not the default port. Should this be the case here as well, or is this not possible on principle?

### PR DESCRIPTION
**Pull request by teddylear**
To avoid issues with a test failing due to port conflict when etcd is
already running, this test now uses dynamic ports instead.

Fixes #11956

Please read https://github.com/etcd-io/etcd/blob/master/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

File: embed/serve_test.go [hunk 1]
```diff
@@ -25,14 +27,48 @@ import (
...
+		scheme = "unixs"
+	}
+	for i := 0; i < n; i++ {
+		u, _ := url.Parse(fmt.Sprintf("%s://localhost:%d%06d", scheme, os.Getpid(), i))
+		urls = append(urls, *u)
+	}
+	return urls
+}
+
+func setupEmbedCfg(cfg *Config, curls []url.URL, purls []url.URL) {
```
Comment (jingyih) [inline embed/serve_test.go:62]: Sorry I do not follow why do we need this function. It looks like many settings are the default values in NewConfig()?

Comment (teddylear) [reply embed/serve_test.go:62]: Some of the settings here can be removed. This was copied (along with the other function) from [integration/embed/embed_test.go](https://github.com/etcd-io/etcd/blob/master/integration/embed/embed_test.go). I can move the logic fromm this function back into the main test function and clean up the settings to the minimal required if that would be cleaner.

Comment (teddylear) [reply embed/serve_test.go]: I made the updated to make things cleaner and squashed the commits again, please let me know if update resolves this issue.

**Comment by teddylear** [comment]
Current test failure appears to be unrelated to current changes.

**Review by jingyih — COMMENTED** [review]
LGTM
Thank you!
