### PR TITLE
etcdserver: Fix PeerURL validation

### LINKED ISSUE #11013: ValidateClusterAndAssignIDs() fails due to sorting URLs lexicographically before comparison
In order to validate peer urls, the current code first sorts existing and local members lexicographically BEFORE attempting to compare their resolved IP addresses. This leads to weird behavior where changing the hostname (say due to unique pod identifiers) can cause the sort order to change, leading to random validation failure for no obvious reason.

The correct behavior would be to resolve URLs to IP addresses before sort+compare, or less efficiently try to compare every possible combination of URLs until there are none left.

### PR DESCRIPTION
**Pull request by dbavatar**
In case of URLs that are synonyms, the current lexicographic sorting
and compare of the URLs fails with frustrating errors. Make sure to do
a full comparison between every set of PeerURLs before failing.

Fixes #11013

### CODE REVIEW

**Comment by gyuho** [comment]
@spzala @hexfusion

**Comment by hexfusion** [comment]
@dbavatar could you add a simple test case or example to prove your issue? I think that would help me to understand the problem better.

**Comment by spzala** [comment]
@dbavatar thanks for reporting issue and creating this PR. You mentioned frustrating errors, if possible, would you add the errors in the issue for reference and example URLs that can be used for reproducing error, meanwhile the PR is being reviewed.  I see a related test, that can possibly be modified or we can a new test for your use case,  https://github.com/etcd-io/etcd/blob/master/etcdserver/api/membership/cluster_test.go#L248?  Thanks!

**Comment by dbavatar** [comment]
@hexfusion @spzala was attempting to implement a test case base on cluster_test.go, but I don't see how. The problem there is the same as the root cause of the bug: netutil.go is too much abstraction. To implement the test, I'd have to feed pseudo URL's to cluster.go and have netutil.go return test data, similar to TestResolveTCPAddrs() in netutil_test.go.

Additionally I see the correct design pattern does exist in netutil.go:urlsEqual(), where it resolves the array of URLs first, THEN sorts them, THEN checks if they are equal. But here we've abstracted away Member struct {} which is necessary to assign the matching ID's

I can implement a better fix and a test if I get rid of the netutil abstraction and simply have cluster.go call pkg net.* itself.

My use case is admitted weird, but still correct - there are multiple hostnames for the same host that sort in different orders lexagraphically compared to their resolved IP's.

If I take a step back - I don't know why ValidateClusterAndAssignIDs() is necessary at all. Given we query the existing cluster via GetClusterFromRemotePeers() - why not just use this directly instead of asking the user for input then dying if it does not match?

**Comment by dbavatar** [comment]
Here is an example of the validation error. It says that host IP 172.25.39.140 != 172.25.39.141. Which of course is obvious, it should not be comparing them:

2019-08-15 22:42:31.313588 C | etcdmain: error validating peerURLs {ClusterID:47e4edfc3a75a480 Members:[&{ID:2d66c23bbe7b0ac4 RaftAttributes:{PeerURLs:[https://a172-25-39-140.deploy.akamaitechnologies.com:2380]} Attributes:{Name:root-etcd-pnvvw6b6q7 ClientURLs:[https://root-etcd-pnvvw6b6q7.root-etcd.kube-system.svc:2379]}} &{ID:3ebeaf634b816134 RaftAttributes:{PeerURLs:[https://a172-25-39-139.deploy.akamaitechnologies.com:2380]} Attributes:{Name:a172-25-39-139 ClientURLs:[https://a172-25-39-139.deploy.akamaitechnologies.com:2379]}} &{ID:6aa67a97d05b1b68 RaftAttributes:{PeerURLs:[https://a172-25-39-141.deploy.akamaitechnologies.com:2380]} Attributes:{Name: ClientURLs:[]}}] RemovedMemberIDs:[]}: unmatched member while checking PeerURLs ("https://172.25.39.140:2380"(resolved from "https://a172-25-39-140.deploy.akamaitechnologies.com:2380") != "https://172.25.39.141:2380"(resolved from "https://root-etcd-7lhxcpqq2k.root-etcd.kube-system.svc:2380"))

hosts file:

172.25.39.139 a172-25-39-139.deploy.akamaitechnologies.com
172.25.39.140 a172-25-39-140.deploy.akamaitechnologies.com root-etcd-pnvvw6b6q7.root-etcd.kube-system.svc
172.25.39.141 a172-25-39-141.deploy.akamaitechnologies.com root-etcd-7lhxcpqq2k.root-etcd.kube-system.svc

**Comment by spzala** [comment]
@dbavatar that's a great detail, thanks!

File: etcdserver/api/membership/cluster.go [hunk 1]
```diff
@@ -765,10 +765,17 @@ func ValidateClusterAndAssignIDs(lg *zap.Logger, local *RaftCluster, existing *R
 	ctx, cancel := context.WithTimeout(context.TODO(), 30*time.Second)
 	defer cancel()
 	for i := range ems {
-		if ok, err := netutil.URLStringsEqual(ctx, lg, ems[i].PeerURLs, lms[i].PeerURLs); !ok {
+		var err error
```
Comment (spzala) [inline etcdserver/api/membership/cluster.go]: @dbavatar I don't have a way to reproduce the error as you see with your config. However, I tested your fix. We probably don't need to sort anymore with your proposed fix. I am not comfortable on suggesting to change the current pattern but let's wait on @hexfusion for this thoughts. About test case, adding a new case in netutil_test for urlsEqual similar to what's there covering your use case should a good add. Thanks!

**Comment by spzala** [comment]
@xiang90 yes, I had some comments but it's been already addresses. I have also tested it, so it looks good to me.  @vimalk78 as Xiang said, if you can take a look that would be great. Thanks!

File: etcdserver/api/membership/cluster.go [hunk 2]
```diff
@@ -759,16 +759,21 @@ func ValidateClusterAndAssignIDs(lg *zap.Logger, local *RaftCluster, existing *R
...
+		ok := false
+		for j := range lms {
+			if ok, err = netutil.URLStringsEqual(ctx, lg, ems[i].PeerURLs, lms[j].PeerURLs); ok {
+				lms[j].ID = ems[i].ID
+				break
+			}
+		}
+		if !ok {
 			return fmt.Errorf("unmatched member while checking PeerURLs (%v)", err)
```
Comment (vimalk78) [inline etcdserver/api/membership/cluster.go]: nit: the `err` is error encountered in comparing `ems[i]` with last `lms`. This error statement made more sense when there was only level loop, so we know which `member` is being compared.
perhaps we can say `members` instead of `member` and print `ems[i]` and complete `lms` in the error message.

File: etcdserver/api/membership/cluster.go [hunk 3]
```diff
@@ -759,16 +759,21 @@ func ValidateClusterAndAssignIDs(lg *zap.Logger, local *RaftCluster, existing *R
 	if len(ems) != len(lms) {
 		return fmt.Errorf("member count is unequal")
 	}
-	sort.Sort(MembersByPeerURLs(ems))
-	sort.Sort(MembersByPeerURLs(lms))
 
 	ctx, cancel := context.WithTimeout(context.TODO(), 30*time.Second)
```
Comment (vimalk78) [inline etcdserver/api/membership/cluster.go]: since there are potentially more comparisons now, should the timeout value of 30 seconds be reconsidered? or is it better to move this inside the inner loop?

File: etcdserver/api/membership/cluster.go [hunk 4]
```diff
@@ -759,16 +759,21 @@ func ValidateClusterAndAssignIDs(lg *zap.Logger, local *RaftCluster, existing *R
...
 	defer cancel()
 	for i := range ems {
-		if ok, err := netutil.URLStringsEqual(ctx, lg, ems[i].PeerURLs, lms[i].PeerURLs); !ok {
+		var err error
+		ok := false
+		for j := range lms {
+			if ok, err = netutil.URLStringsEqual(ctx, lg, ems[i].PeerURLs, lms[j].PeerURLs); ok {
```
Comment (vimalk78) [inline etcdserver/api/membership/cluster.go]: The method `netutil.URLStringsEqual` and its callees `netutil.urlEqual` and `netutil.resolveTCPAddrs` take a pair of `[]url.URL` , so perhaps a single loop is assumed. By dividing into multiple level loop, same URL is potentially getting resolved multiple times.
I am not familiar with a real setup to see if it leads to inefficiency and we need to cache the result.

File: etcdserver/api/membership/cluster.go (hunk 3 above)
Comment (dbavatar) [reply etcdserver/api/membership/cluster.go]: There's a maximum of 49 resolutions, and 42 of those should be cached by the local resolver. The minimum possible DNS TTL is 1 second, and that's plenty of time to finish this loop, although more likely TTL is much higher anyway.

I think the 30 second timeout is only relevant to not blocking indefinitely if DNS is unresponsive

File: etcdserver/api/membership/cluster.go (hunk 4 above)
Comment (dbavatar) [reply etcdserver/api/membership/cluster.go]: See above comment, should already be cached by the lower layers (host/resolver). Also see this request to implement a cache in golang that was declined for the same reason https://github.com/golang/go/issues/24796#issuecomment-383716244

File: etcdserver/api/membership/cluster.go (hunk 2 above)
Comment (dbavatar) [reply etcdserver/api/membership/cluster.go]: can do.

Comment (vimalk78) [reply etcdserver/api/membership/cluster.go]: thanks @dbavatar

**Comment by vimalk78** [comment]
lgtm.

**Comment by spzala** [comment]
@xiang90 @gyuho hi, the changes seems like ready to merge. Thanks!

**Comment by xiang90** [comment]
lgtm
