### PR TITLE
[3.5] etcdserver: backport check scheduledCompactKeyName and finishedCompac…

### LINKED ISSUE #15919: Incorrect hash when resuming scheduled compaction after etcd restarts
### What happened?

I tried out using the `--experimental-compact-hash-check-enabled` flag on my etcd cluster today, and I think I might have encountered a race condition when a server starts up/resumes a scheduled compaction that causes the hash value to be incorrect.

About my setup: I have a 5 member cluster, running as k8s pods. They already have the `--experimental-initial-corrupt-check` flag enabled.

I was adding the `--experimental-compact-hash-check-enabled` flag (and also upgrading from 3.5.6 to 3.5.9) on a 5-member node. For 3 of the 4 etcd members, I had already stopped the etcd pod, updated their container URLs to 3.5.9, added the new hash check flag, and then restarted the etcd pod. I then stopped the 4th follower (which I'll call FOO), edited its pod config, and brought it back up. I then stopped the leader, and did the same update/restart. This triggered a leader election, and one of the former followers (which I'll call BAR) became the new leader.

The new leader then performed the periodic compact hash check, as configured. But the strange thing is that, even though all of my pods were up and running (and had passed the initial corruption check), the very first periodic check failed!

Due to the liveness probe problem mentioned in https://github.com/etcd-io/etcd/issues/13340, I had to deal with my pods getting restarted by kube due to the alarm... But when I disarmed the CORRUPT alarm so my etcd pods could stay up and running, they all again passed the initial corrupt data check, and logged the same hashes for the following "storing new hash" logs. So that's why I suspect there was very unlucky timing and a race condition that caused FOO to calculate the wrong hash value and use that when BAR asked for its hash during that periodic compaction hash check.

### What did you expect to happen?

I expected the periodic compaction hash check to succeed and for my cluster be healthy because:
1) the initial data check passed on all members of the cluster
2) the hash/compact-revision that FOO logged with the "storing new hash" line both before and after the problematic hash matched the hashes in the rest of the cluster

### How can we reproduce it (as minimally and precisely as possible)?

I'm not sure how to reproduce it. Maybe create a multi-member cluster with enough data so that compaction takes a non-trivial amount of time, trigger a compaction, and then stop one of the members right in the middle of the compaction so that compaction fails and needs to resume compacting when it comes back up?

### Anything else we need to know?

I saw https://github.com/etcd-io/etcd/issues/15548, but that mentions the cluster ID changing, and in this scenario where just I'm restarting etcd with different flags, I don't think the cluster ID would change.

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
etcd Version: 3.5.9
Git SHA: bdbbde998
Go Version: go1.19.9
Go OS/Arch: linux/amd64

$ etcdctl version
etcdctl version: 3.5.9
API version: 3.5
```

</details>

### Etcd configuration (command line flags or environment variables)

<details>
(from a k8s pod manifest)

```
  - command:
    - etcd
    - --advertise-client-urls=https://XXX:2379
    - --cert-file=/etc/kubernetes/pki/etcd/server.crt
    - --client-cert-auth=true
    - --data-dir=/var/lib/etcd
    - --experimental-initial-corrupt-check=true
    - --experimental-compact-hash-check-enabled=true
    - --initial-advertise-peer-urls=https://XXX:2380
    - --initial-cluster-token=XXX
    - --initial-cluster=XXX
    - --initial-cluster-state=existing
    - --key-file=/etc/kubernetes/pki/etcd/server.key
    - --listen-client-urls=https://127.0.0.1:2379,https://XXX:2379
    - --listen-metrics-urls=http://127.0.0.1:2381,http://XXX:2381
    - --listen-peer-urls=https://XXX:2380
    - --name=XXX
    - --peer-cert-file=/etc/kubernetes/pki/etcd/peer.crt
    - --peer-client-cert-auth=true
    - --peer-key-file=/etc/kubernetes/pki/etcd/peer.key
    - --peer-trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
    - --snapshot-count=10000
    - --trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
    - --auto-compaction-mode=periodic
    - --auto-compaction-retention=1h
    - --quota-backend-bytes=15032385536
    image: registry.k8s.io/etcd:3.5.9-0
```

</details>

### Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# Lost due to pods being restarted, but you can see the endpoints and IDs below

# This endpoint status table was captured while the cluster was in the alarmed state
$ etcdctl --endpoints $endpoints endpoint status -w table
+--------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+----------------+
|      ENDPOINT      |        ID        | VERSION | DB SIZE | IS LEADER | IS LEARNER | RAFT TERM | RAFT INDEX | RAFT APPLIED INDEX |     ERRORS     |
+--------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+----------------+
|  XXX:2379 | 367806663aa1996c |   3.5.9 |  4.9 GB |     false |      false |        30 |  718184797 |          718184797 | alarm:CORRUPT  |
| XXX:2379 | 6069c22b85ee10b0 |   3.5.9 |  4.8 GB |      true |      false |        30 |  718184798 |          718184798 | alarm:CORRUPT  |
| XXX:2379 | 917d2067aeb00315 |   3.5.9 |  4.8 GB |     false |      false |        30 |  718184802 |          718184802 | alarm:CORRUPT  |
| XXX:2379 | b2529a8db451f246 |   3.5.9 |  4.8 GB |     false |      false |        30 |  718184804 |          718184804 | alarm:CORRUPT  |
|  XXX:2379 | e56f12f0d98830bb |   3.5.9 |  4.9 GB |     false |      false |        30 |  718184805 |          718184805 | alarm:CORRUPT  |
+--------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+----------------+
```

</details>

### Relevant log output

```shell
(not literal logs, but reconstructed from my investigation)

* 15:34:55 - all nodes log "storing new hash". revision=702700874 compact-revision=702656236 hash=483395635
* ... I update the other etcd nodes one by one
* 15:39:54 - FOO  starts shutting down
* 15:39:54 - every node but FOO logs "storing new hash" of hash=2533962327 for compact-revision=702700874 at revision=702739864.
* 15:39:54- FOO logs "Failed compaction" (because the etcd pod was terminating)
* 15:40:24 - Updated etcd pod on  FOO starts running
* 15:40:24 - FOO logs "resume scheduled compaction"
* 15:40:35 - FOO logs "storing new hash" of hash=2915350535 for compact-revision=702700874 at revision=702739864. (But every other node for this compact-revision had hash=2533962327)!
* 15:42:06 - BAR became leader
* 15:42:18 - BAR started compact hash check
* 15:42:18 -  BAR (leader) says "failed compaction hash check". For revision 702739864, leader had 2533962327, but follower FOO had hash 2915350535. BAR logged "alarm raised"
```

### PR DESCRIPTION
**Pull request by CaojiamingAlan**
…tKeyName before writing hash to release-3.5.

Follow up of #15985

Fix #15919.
Check ScheduledCompactKeyName and FinishedCompactKeyName before writing hash to hashstore.
If they do not match, then it means this compaction has once been interrupted and its hash value is invalid. In such cases, we won't write the hash values to the hashstore, and avoids the incorrect corruption alarm.

Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Review by serathius — APPROVED** [review]

File: server/mvcc/kvstore.go [hunk 1]
```diff
@@ -227,7 +227,27 @@ func (s *store) updateCompactRev(rev int64) (<-chan struct{}, int64, error) {
 	return nil, compactMainRev, nil
 }
 
-func (s *store) compact(trace *traceutil.Trace, rev, prevCompactRev int64) (<-chan struct{}, error) {
+// checkPrevCompactionCompleted checks whether the previous scheduled compaction is completed.
+func (s *store) checkPrevCompactionCompleted() bool {
+	tx := s.b.ReadTx()
+	tx.Lock()
```
Comment (chaochn47) [inline server/mvcc/kvstore.go:233]: Just curious why not use `tx.RLock()` but understand the PR is a backport of https://github.com/etcd-io/etcd/pull/15985

**Review by chaochn47 — APPROVED** [review]

File: server/mvcc/kvstore.go (hunk 1 above)
Comment (serathius) [reply server/mvcc/kvstore.go:233]: `Lock()` for `ReadTx()` should be by default a `Rlock()`.

Comment (chaochn47) [reply server/mvcc/kvstore.go:233]: For my understanding, do you mean the following RWMutex `Lock` is equal to `RLock` to protect the read buffer? 

https://github.com/etcd-io/etcd/blob/5e40a8b00cc1be3ce0dd3d7e6947d417253fb03f/server/storage/backend/read_tx.go#L127-L130

Comment (CaojiamingAlan) [reply server/mvcc/kvstore.go:233]: After investigating a little bit, I think you are right, we should use RLock() instead. Lock() should only be used when the read buffer is updated by the writes committed by the BatchTxs. However, there are several positions where use read-only operations but Lock() is used. I think it is good to open a separate PR to correct them all.

Comment (chaochn47) [reply server/mvcc/kvstore.go:233]: Yep. That aligns with my understanding. 

I also don't think it blocks this PR to be merged. This can be corrected separately.

File: tests/e2e/corrupt_test.go [hunk 2]
```diff
@@ -180,3 +181,61 @@ func TestCompactHashCheckDetectCorruption(t *testing.T) {
...
+	})
+	require.NoError(t, err)
+	t.Cleanup(func() {
+		if errC := epc.Close(); errC != nil {
+			t.Fatalf("error closing etcd processes (%v)", errC)
+		}
+	})
+
+	// Put 200 identical keys to the cluster, so that the compaction will drop some stale values.
+	// We need a relatively big number here to make the compaction takes a non-trivial time, and we can interrupt it.
```
Comment (jmhbnz) [inline tests/e2e/corrupt_test.go:210]: Double checking my understanding, this backport uses a much larger value here compared to original pr because in 3.5 we don't have the luxury of setting very slow compaction speed is that right?

File: server/mvcc/kvstore.go (hunk 1 above)
Comment (jmhbnz) [reply server/mvcc/kvstore.go:233]: Nice catch @chaochn47 - suggest we raise an issue for this so we don't forget to come back to it.

File: tests/e2e/corrupt_test.go (hunk 2 above)
Comment (CaojiamingAlan) [reply tests/e2e/corrupt_test.go:210]: Yes, it does not have a batch-sleeping-time flag.

**Review by jmhbnz — APPROVED** [review]
LGTM

File: server/mvcc/kvstore.go (hunk 1 above)
Comment (ahrtr) [reply server/mvcc/kvstore.go:233]: The `Lock()/Unlock()` should only be used in the following three cases,
- When [committing a transaction](https://github.com/etcd-io/etcd/blob/dee90e19f1c6fc2aceed38cd2855010df0b6c6a7/server/storage/backend/batch_tx.go#L336). Because it will reset the read tx, including the buffer;
- When [writing the pending data (not committed to bbolt yet) back to read buf](https://github.com/etcd-io/etcd/blob/dee90e19f1c6fc2aceed38cd2855010df0b6c6a7/server/storage/backend/batch_tx.go#L310), because obviously no reading is allowed when writing the read buffer;
- When [performing defragmentation](https://github.com/etcd-io/etcd/blob/dee90e19f1c6fc2aceed38cd2855010df0b6c6a7/server/storage/backend/backend.go#L464),  because again it will reset the read tx, including the read buffer.

`RLock()/RUnlock()` should be used for all other cases.

Please raise a separate ticket to track the change. It should also be backported to 3.5 and 3.4.

File: server/mvcc/kvstore.go [hunk 3]
```diff
@@ -227,7 +227,27 @@ func (s *store) updateCompactRev(rev int64) (<-chan struct{}, int64, error) {
...
+	if len(scheduledCompactBytes) != 0 {
+		scheduledCompact = bytesToRev(scheduledCompactBytes[0]).main
+	}
+
+	_, finishedCompactBytes := tx.UnsafeRange(buckets.Meta, finishedCompactKeyName, nil, 0)
+	finishedCompact := int64(0)
+	if len(finishedCompactBytes) != 0 {
+		finishedCompact = bytesToRev(finishedCompactBytes[0]).main
+
+	}
```
Comment (ahrtr) [inline server/mvcc/kvstore.go:246]: Please add a `UnsafeReadScheduledCompact` and `UnsafeReadFinishedCompact` in server/mvcc/util.go for 3.5.

The two functions should be reused in multiple places, (Please search `scheduledCompactKeyName` and `finishedCompactKeyName` in the code base)

It's accepted to fix it in a separate PR. Please also raise a followup ticket.

**Comment by ahrtr** [comment]
Please raise two followup ticket as mentioned in https://github.com/etcd-io/etcd/pull/16068#discussion_r1263664700 and https://github.com/etcd-io/etcd/pull/16068#discussion_r1263667496. 

Pls also rebase this PR.

**Comment by CaojiamingAlan** [comment]
Just raised #16247. I will solve https://github.com/etcd-io/etcd/pull/16068#discussion_r1263667496 real quick, so no need for another PR.

**Review by ahrtr — APPROVED** [review]
LGTM

thx @CaojiamingAlan

File: server/mvcc/kvstore.go (hunk 1 above)
Comment (serathius) [reply server/mvcc/kvstore.go:233]: @ahrtr thanks for figuring out proper usage of transaction lock. However, I don't_ see reason why we should backport it. Old implementation uses stricter lock, which is sub-optimal, but is not a bug. 

To ensure release stability, we need to assume that the list you proposed can have a mistake. I would prefer that we don't verify correctness of performance improvements on stable releases.

Comment (ahrtr) [reply server/mvcc/kvstore.go:233]: Note I prefer to backporting it, but I am not insist on backporting it if there is strong objection from other maintainers.

Comment (serathius) [reply server/mvcc/kvstore.go:233]: > stricter lock is true, it's also wrong lock. It's a bug to me.

Without a change system behaves correctly, after the change only thing you expect is performance improvement. How this is a bug?

Comment (ahrtr) [reply server/mvcc/kvstore.go:233]: I would say it's harmless (on functionality) bug, obviously the lock isn't correctly be used. Let alone it has impact on performance.

Comment (serathius) [reply server/mvcc/kvstore.go:233]: Bugs is when locks don't protect the critical section, relaxing locks is performance improvement. Nothing is harmless until proven, let alone concurrency change.
