### PR TITLE
Ensure consistent file permissions on broken WAL files

### LINKED ISSUE #18571: Inconsistent WAL file permissions on broken files
### Bug report criteria

- [X] This bug report is not security related, security issues should be disclosed privately via [etcd maintainers](mailto:etcd-maintainers@googlegroups.com).
- [X] This is not a support request or question, support requests or questions should be raised in the etcd [discussion forums](https://github.com/etcd-io/etcd/discussions).
- [X] You have read the etcd [bug reporting guidelines](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/reporting_bugs.md).
- [X] Existing open issues along with etcd [frequently asked questions](https://etcd.io/docs/latest/faq) have been checked and this is not a duplicate.

### What happened?

When etcd recovers from a broken WAL file, it writes the backup broken file to different permissions (0644) than the rest of the files (0600).  This is a result of a system umask of 0022 at create time that does not appear to get changed/updated later.

Specific permissions that appear should be set:
https://github.com/etcd-io/etcd/blob/main/client/pkg/fileutil/fileutil.go#L31

Call to os.Create:
https://github.com/etcd-io/etcd/blob/main/server/storage/wal/repair.go#L70

A simple call to Chmod may fix the issue:

```
bf.Chmod(PrivateFileMode)
```

### What did you expect to happen?

When etcd recovers from a broken WAL file, it should write the backup broken file to the same permissions as the rest of the files.  

### How can we reproduce it (as minimally and precisely as possible)?

Create a scenario to corrupt a WAL file.  Alternatively, write a unit test that validates the permissions mode on the output from the repair.go code.

### Anything else we need to know?

Occurred in OpenShift 4.16.7
Kubernetes Version: v1.29.7+6abe8a1

### Etcd version (please run commands below)

<details>

```console
# etcd --version
etcd Version: 3.5.13
Git SHA: GitNotFound
Go Version: go1.21.11 (Red Hat 1.21.11-1.el9_4) X:strictfipsruntime
Go OS/Arch: linux/amd64

# etcdctl version
etcdctl version: 3.5.13
API version: 3.5
```

</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
# etcdctl member list -w table
+------------------+---------+-------------------------------+----------------------------+----------------------------+------------+
|        ID        | STATUS  |             NAME              |         PEER ADDRS         |        CLIENT ADDRS        | IS LEARNER |
+------------------+---------+-------------------------------+----------------------------+----------------------------+------------+
| 9af34339d56d737e | started | master1.example.com | https://192.168.10.91:2380 | https://192.168.10.91:2379 |      false |
| d10b5e4d21cb8025 | started | master0.example.com | https://192.168.10.90:2380 | https://192.168.10.90:2379 |      false |
| d51bdd1dfc1b1e42 | started | master2.example.com | https://192.168.10.92:2380 | https://192.168.10.92:2379 |      false |
+------------------+---------+-------------------------------+----------------------------+----------------------------+------------+


# etcdctl endpoint status -w table
+----------------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
|          ENDPOINT          |        ID        | VERSION | DB SIZE | IS LEADER | IS LEARNER | RAFT TERM | RAFT INDEX | RAFT APPLIED INDEX | ERRORS |
+----------------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
| https://192.168.10.90:2379 | d10b5e4d21cb8025 |  3.5.13 |  566 MB |     false |      false |       147 |  525018061 |          525018061 |        |
| https://192.168.10.91:2379 | 9af34339d56d737e |  3.5.13 |  432 MB |      true |      false |       147 |  525018062 |          525018062 |        |
| https://192.168.10.92:2379 | d51bdd1dfc1b1e42 |  3.5.13 |  601 MB |     false |      false |       147 |  525018063 |          525018063 |        |
+----------------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
```

</details>

### Relevant log output

```Shell
[root@master2 ~]# ls -l /var/lib/etcd/member/wal/*
-rw-r--r--. 1 root root 64000000 Jun 15 20:14 /var/lib/etcd/member/wal/0000000000007d29-0000000012e90319.wal.broken
-rw-------. 1 root root 64016512 Sep 10 16:28 /var/lib/etcd/member/wal/000000000000cb6c-000000001f48458d.wal
-rw-------. 1 root root 64001752 Sep 10 16:34 /var/lib/etcd/member/wal/000000000000cb6d-000000001f487697.wal
-rw-------. 1 root root 64002720 Sep 10 16:41 /var/lib/etcd/member/wal/000000000000cb6e-000000001f48a32b.wal
-rw-------. 1 root root 64036568 Sep 10 16:47 /var/lib/etcd/member/wal/000000000000cb6f-000000001f48d276.wal
-rw-------. 1 root root 64015152 Sep 10 16:53 /var/lib/etcd/member/wal/000000000000cb70-000000001f490208.wal
-rw-------. 1 root root 64000000 Sep 10 16:53 /var/lib/etcd/member/wal/000000000000cb71-000000001f493093.wal
-rw-------. 1 root root 64000000 Sep 10 16:53 /var/lib/etcd/member/wal/1.tmp

[root@master1 ~]# ls -l /var/lib/etcd/member/wal/*
-rw-------. 1 root root 64000000 Sep 10 16:47 /var/lib/etcd/member/wal/0.tmp
-rw-r--r--. 1 root root 64000000 Jul 15 11:51 /var/lib/etcd/member/wal/0000000000001085-000000001695a9e4.wal.broken
-rw-------. 1 root root 64000128 Sep 10 16:28 /var/lib/etcd/member/wal/0000000000004698-000000001f48461f.wal
-rw-------. 1 root root 64007144 Sep 10 16:34 /var/lib/etcd/member/wal/0000000000004699-000000001f48772e.wal
-rw-------. 1 root root 64004480 Sep 10 16:41 /var/lib/etcd/member/wal/000000000000469a-000000001f48a3ab.wal
-rw-------. 1 root root 64025248 Sep 10 16:47 /var/lib/etcd/member/wal/000000000000469b-000000001f48d303.wal
-rw-------. 1 root root 64000000 Sep 10 16:52 /var/lib/etcd/member/wal/000000000000469c-000000001f4902cd.wal

```

This causes this known issue: https://access.redhat.com/solutions/7055147

### PR DESCRIPTION
**Pull request by lucasrod16**
Fixes #18571

### CODE REVIEW

File: server/storage/wal/repair.go [hunk 1]
```diff
@@ -67,7 +67,7 @@ func Repair(lg *zap.Logger, dirpath string) bool {
 
 		case errors.Is(err, io.ErrUnexpectedEOF):
 			brokenName := f.Name() + ".broken"
-			bf, bferr := os.Create(brokenName)
+			bf, bferr := os.OpenFile(brokenName, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, fileutil.PrivateFileMode)
```
Comment (serathius) [inline server/storage/wal/repair.go:70]: You mention consistency in the PR name, can you maybe look into other places that create WAL file and propose how it can be reused and unified allowing for consistency?

Comment (lucasrod16) [reply server/storage/wal/repair.go]: Here are my observations:

In `wal.Create`, `fileutil.LockFile(p, os.O_WRONLY|os.O_CREATE, fileutil.PrivateFileMode)` is used to bootstrap a new WAL file:

https://github.com/etcd-io/etcd/blob/5088131f51860bb00db8340905639f02c85aa1c7/server/storage/wal/wal.go#L129

and in `alloc()`, `fileutil.LockFile(fpath, os.O_CREATE|os.O_WRONLY, fileutil.PrivateFileMode)` is also used to create/cut a new WAL file:

https://github.com/etcd-io/etcd/blob/5088131f51860bb00db8340905639f02c85aa1c7/server/storage/wal/file_pipeline.go#L78

It seems to make sense to use the same method of creating the backup WAL file in `Repair` as well.

WDYT?

Comment (lucasrod16) [reply server/storage/wal/repair.go]: We could encapsulate the call to `fileutil.LockFile(brokenName, os.O_WRONLY|os.O_CREATE, fileutil.PrivateFileMode)` in a `createNewWALFile` function to promote reuse and maintain consistency. Of course, whether to add this level of abstraction is up to you and your preference for abstraction.

**Comment by ivanvc** [comment]
Hi, @lucasrod16. Thanks for your pull request. Could you please rebase it? The govulncheck job is failing because of a recent update to Go in the main branch. Rebasing should make the CI green. Thanks!

**Comment by lucasrod16** [comment]
> Hi, @lucasrod16. Thanks for your pull request. Could you please rebase it? The govulncheck job is failing because of a recent update to Go in the main branch. Rebasing should make the CI green. Thanks!

Hi @ivanvc, thanks for the heads up! I've rebased the branch, and it should be good now.

File: server/storage/wal/repair.go (hunk 1 above)
Comment (serathius) [reply server/storage/wal/repair.go]: Don't think it's the same, the LockFile function not only creates file but takes a OS lock on it. Maybe what I proposed doesn't make sense here as we need a function that would would need different options for
* Creating a normal file or a locked file (fileutil.LockFile vs os.OpenFile)
* Create a new file or truncating existing file. (os.O_WRONLY|os.O_CREATE vs os.O_CREATE|os.O_WRONLY|os.O_TRUNC)

It might be useful to have a single function to create WAL files to show all the options, however I'm not sure that it would be beneficial. cc @ahrtr

File: server/storage/wal/repair.go [hunk 2]
```diff
@@ -67,7 +67,7 @@ func Repair(lg *zap.Logger, dirpath string) bool {
 
 		case errors.Is(err, io.ErrUnexpectedEOF):
 			brokenName := f.Name() + ".broken"
-			bf, bferr := os.Create(brokenName)
+			bf, bferr := fileutil.LockFile(brokenName, os.O_WRONLY|os.O_CREATE, fileutil.PrivateFileMode)
```
Comment (ahrtr) [inline server/storage/wal/repair.go:70]: `fileutil.LockFile` unnecessarily changes the original semantics. It not only creates a new file, but also lock the file. But I agree it isn't a big problem, because the file is closed soon https://github.com/etcd-io/etcd/blob/981061a4958e8d386b025dbecd43af9b974709e2/server/storage/wal/repair.go#L75
```suggestion
			bf, bferr := os.OpenFile(brokenName, os.O_WRONLY|os.O_CREATE, fileutil.PrivateFileMode)
```

File: server/storage/wal/repair.go (hunk 1 above)
Comment (ahrtr) [reply server/storage/wal/repair.go]: > It might be useful to have a single function to create WAL files to show all the options, however I'm not sure that it would be beneficial. cc @ahrtr

I am open to do such enhancement, so as to make it less error prone.  But I suggest to only fix it per https://github.com/etcd-io/etcd/pull/18574#discussion_r1758778704 in this PR, to keep it as simple as possible, and we can do the enhancement in a separate PR, which definitely needs more careful review.

**Review by ahrtr — APPROVED** [review]

File: server/storage/wal/repair.go (hunk 2 above)
Comment (lucasrod16) [reply server/storage/wal/repair.go]: Updated to use `os.OpenFile`. I agree that it isn't necessary to put a lock on the file in this case of creating a backup WAL file

File: server/storage/wal/repair.go (hunk 1 above)
Comment (lucasrod16) [reply server/storage/wal/repair.go]: That makes sense. I'll follow up with a separate PR for a WAL creation function once this is merged

**Comment by lucasrod16** [comment]
First time I've seen the e2e-386 job fail on this PR. I opened an issue for the test flake: #18585

File: server/storage/wal/repair.go [hunk 3]
```diff
@@ -67,7 +67,7 @@ func Repair(lg *zap.Logger, dirpath string) bool {
 
 		case errors.Is(err, io.ErrUnexpectedEOF):
 			brokenName := f.Name() + ".broken"
-			bf, bferr := os.Create(brokenName)
+			bf, bferr := os.OpenFile(brokenName, os.O_WRONLY|os.O_CREATE, fileutil.PrivateFileMode)
```
Comment (serathius) [inline server/storage/wal/repair.go:70]: This removed `O_TRUNC` from the file open flags, is there any chance for file collision?  cc @ahrtr

Comment (ahrtr) [reply server/storage/wal/repair.go:70]: Right, let's add `os.O_TRUNC`.

We backup the whole wal file to a .broken file, so we should truncate the existing file if present (unlikely in practice).

Comment (lucasrod16) [reply server/storage/wal/repair.go]: Added `os.O_TRUNC` back

**Review by serathius — APPROVED** [review]
