### PR TITLE
netutil: consistently format ipv6 addresses

### LINKED ISSUE #15127: Do not literally compare IPv6 addresses
### What happened?

etcd can't bootstrap a cluster because the IPv6 address in `ETCD_INITIAL_CLUSTER` does not literally match the one in `ETCD_INITIAL_ADVERTISE_PEER_URLS`, even though it's the same IPv6 address.

Error:

```
--initial-cluster has etcd1.cyberfusion.cloud=https://[2a0c:eb00:0:f7:0e5f:7a4b:72e8:fa3a]:2380 but missing from --initial-advertise-peer-urls=https://[2a0c:eb00:0:f7:e5f:7a4b:72e8:fa3a]:2380 ("https://[2a0c:eb00:0:f7:e5f:7a4b:72e8:fa3a]:2380"(resolved from "https://[2a0c:eb00:0:f7:e5f:7a4b:72e8:fa3a]:2380") != "https://[2a0c:eb00:0:f7:0e5f:7a4b:72e8:fa3a]:2380"(resolved from "https://[2a0c:eb00:0:f7:0e5f:7a4b:72e8:fa3a]:2380"))
```

`2a0c:eb00:0:f7:e5f:7a4b:72e8:fa3a` != `2a0c:eb00:0:f7:0e5f:7a4b:72e8:fa3a` (the `0` misses from `0e5f`).

### What did you expect to happen?

The cluster should be bootstrapped. etcd should not compare IPv6 addresses literally.

### How can we reproduce it (as minimally and precisely as possible)?

See 'Etcd configuration (command line flags or environment variables)'.

### Anything else we need to know?

_No response_

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
etcd Version: 3.3.25
Git SHA: Not provided (use ./build instead of go build)
Go Version: go1.15.9
Go OS/Arch: linux/amd64

$ etcdctl version
No help topic for 'version'
```

</details>

### Etcd configuration (command line flags or environment variables)

<details>

```
ETCD_INITIAL_CLUSTER="etcd0=https://[2a0c:eb00:0:f7:ec83:5509:1618:8a97]:2380,etcd1=https://[2a0c:eb00:0:f7:0e5f:7a4b:72e8:fa3a]:2380,etcd2=https://[2a0c:eb00:0:f7:6b30:74f7:ef4e:6ada]:2380"
ETCD_INITIAL_ADVERTISE_PEER_URLS="https://[2a0c:eb00:0:f7:e5f:7a4b:72e8:fa3a]:2380"
```

</details>

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by Kidsan**
This formats ipv6 addresses to ensure they can be compared safely

Fixes #15127

### CODE REVIEW

File: pkg/netutil/netutil.go [hunk 1]
```diff
@@ -103,7 +104,26 @@ func resolveURL(ctx context.Context, lg *zap.Logger, u url.URL) (string, error)
...
+			)
+			return "", err
+
+		}
+		addr := &net.TCPAddr{
+			IP:   net.ParseIP(host),
+			Port: p,
+		}
+		return addr.String(), nil
+	}
```
Comment (ahrtr) [inline pkg/netutil/netutil.go:125]: Probably we can just remove this code block, so that it always execute `resolveTCPAddr` (line 130)

Comment (Kidsan) [reply pkg/netutil/netutil.go]: Thanks for the feedback. I've removed that block as suggested and amended the overridden resolveTCPAddr functions in the other tests in this package to handle valid IP addresses.

**Review by ahrtr — APPROVED** [review]
LGTM

Thank you @Kidsan

**Comment by ahrtr** [comment]
Could you backport this PR to 3.4 and 3.5 as well?

**Comment by serathius** [comment]
Should we add a e2e test for IPv6?

**Comment by ahrtr** [comment]
> Should we add a e2e test for IPv6?

Adding e2e test is good, but I think it can be a separate PR.

**Comment by serathius** [comment]
Makes sense, however let's posmone backport PRs until we ensure that overall issue of IPv6 is fixed and tested. Please remember that we are backporting to fixes to issues, not just backporting PRs for sake of backporting.

**Comment by ahrtr** [comment]
> Makes sense, however let's posmone backporting until we ensure that overall issue of IPv6 is fixed and tested. Please remember that we are backporting to fixes to issues, not just backporting PRs for sake of backporting.

Do not understand the concern.
1. https://github.com/etcd-io/etcd/issues/15127 is a real issue to me, please let me know if you don't think it's an issue. The contributor fixes the issue and backport it to 3.5 and 3.4. It makes perfect sense to me. Thx @Kidsan 
2. We can add whatever e2e test for IPv6 in separate PRs. If we see any other issues, we can just continue fix them. etcd shouldn't care about the IP type (IPv4 or IPv6), so I don't worry about any big changes due to any new issues caused by IPv6.

**Comment by serathius** [comment]
For me a feature like IPv6 support cannot exist without tests. If IPv6 formatting didn't work, means that our tests were insufficient, ergo there might be other things that are in out blind spot. 

Discovering and fixing one detail after another is insufficient to make sufficient progress. We need more holistic approach. My thinking is that if IPv6 had such a rudimental bug like this one, it was never properly tested. We should revisit this feature and add sufficient testing to bring up the quality of this area. 

As agreed in https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/features.md all stable features should have a proper testing.  If we don't think that IPv6 support is mature enough we should mark it as experimental.

**Comment by ahrtr** [comment]
I do not see any strong reason to reject this minor bug fix.

**Comment by sanmai-NL** [comment]
I think you can both merge this PR and open/request an issue or PR for the tests.

**Comment by serathius** [comment]
FYI I'm not blocking merging of this PR, just backporting before whole issue is resolved.
