### PR TITLE
raft node notifies configure when confChanged

### LINKED ISSUE #15528: Flaky Test TestMemberPromoteMemberNotLearner
### Which github workflows are flaking?

Integration Test

### Which tests are flaking?

TestMemberPromoteMemberNotLearner

### Github Action link

https://github.com/etcd-io/etcd/actions/runs/4469937666/jobs/7852763845

second time: https://github.com/etcd-io/etcd/actions/runs/4548835671/jobs/8020273443?pr=15580

### Reason for failure (if possible)

```
     logger.go:130: 2023-03-20T15:29:08.541Z	WARN	m2.client	retrying of unary invoker failed	{"member": "m2", "target": "etcd-endpoints://0xc00044b0e0/localhost:m2", "method": "/etcdserverpb.Cluster/MemberPromote", "attempt": 0, "error": "rpc error: code = FailedPrecondition desc = etcdserver: can only promote a learner member"}

     logger.go:130: 2023-03-20T15:29:08.542Z	WARN	m2.client	retrying of unary invoker failed	{"member": "m2", "target": "etcd-endpoints://0xc00044b0e0/localhost:m2", "method": "/etcdserverpb.Cluster/MemberPromote", "attempt": 0, "error": "rpc error: code = FailedPrecondition desc = etcdserver: can only promote a learner member"}

     logger.go:130: 2023-03-20T15:29:13.743Z	WARN	m2.client	retrying of unary invoker failed	{"member": "m2", "target": "etcd-endpoints://0xc00044b0e0/localhost:m2", "method": "/etcdserverpb.Cluster/MemberPromote", "attempt": 0, "error": "rpc error: code = Unavailable desc = etcdserver: request timed out"}

     cluster_test.go:326: expect error to contain can only promote a learner member, got etcdserver: request timed out
```

The test just created 3 member cluster and expect member promote 

### Anything else we need to know?

Also has been caught in https://github.com/etcd-io/etcd/issues/12372

https://github.com/etcd-io/etcd/blob/22bdc913025de198ef2759e9f534ed8dd555de66/server/etcdserver/server.go#L1487 is unnecessary if the local node is not leader. 

It could be a culprit but test cluster does not have much traffic.

### PR DESCRIPTION
**Pull request by chaochn47**
Fix #15528

The PR is built on top of https://github.com/etcd-io/etcd/pull/15703

Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

PTAL @ahrtr @serathius, thanks!

### CODE REVIEW

**Comment by ahrtr** [comment]
Can https://github.com/etcd-io/etcd/issues/15528 be easily reproduced? If not, then we need to add an integration test; we can intentionally inject a sleep failpoint before [r.Advanced()](https://github.com/etcd-io/etcd/blob/22f3e50adafd9d4cf9dd29dd5837483a6417238c/server/etcdserver/raft.go#L310)

**Comment by chaochn47** [comment]
> Can #15528 be easily reproduced? If not, then we need to add an integration test; we can intentionally inject a sleep failpoint before [r.Advanced()](https://github.com/etcd-io/etcd/blob/22f3e50adafd9d4cf9dd29dd5837483a6417238c/server/etcdserver/raft.go#L310)

Not easily. Inject a sleep should do the trick.

File: server/etcdserver/server.go [hunk 1]
```diff
@@ -107,6 +107,8 @@ const (
 	readyPercent = 0.9
 
 	DowngradeEnabledPath = "/downgrade/enabled"
+
+	maxRaftAdvanceDelay = 500 * time.Millisecond
```
Comment (serathius) [inline server/etcdserver/server.go:111]: Where this variable comes from?

**Comment by fuweid** [comment]
It's hard to reproduce in few requests. It needs to send request one by one without pause. 
FYI: You can use the following test code to reproduce it.  

```go
package verify

import (
        "context"
        "strings"
        "testing"
        "time"

        integration2 "go.etcd.io/etcd/tests/v3/framework/integration"
        "go.etcd.io/etcd/tests/v3/integration"
)

var lazyCluster = integration.NewLazyClusterWithConfig(
        integration2.ClusterConfig{
                Size:                        3,
                WatchProgressNotifyInterval: 200 * time.Millisecond,
                DisableStrictReconfigCheck:  true})

func TestVerify(t *testing.T) {
        defer lazyCluster.Terminate()

        clus := lazyCluster.Cluster()
        leaderIdx := clus.WaitLeader(t)
        members := clus.Members

        followerIdx := (leaderIdx + 1) % 3
        cli := clus.Client(leaderIdx)

        // promoting any of the voting members in cluster should fail
        expectedErrKeywords := "can only promote a learner member"
        var err error
        for i := 0; i < 10000; i++ {
                ctx, cancel := context.WithTimeout(context.TODO(), 1*time.Minute)
                _, err = cli.MemberPromote(ctx, uint64(members[followerIdx].ID()))
                cancel()
                if err == nil {
                        t.Fatalf("expect promoting voting member to fail, got no error")
                }

                if strings.Contains(err.Error(), expectedErrKeywords) {
                        continue
                }

                t.Fatalf("unexpected error: %v", err)
        }
}

```

File: server/etcdserver/server.go [hunk 2]
```diff
@@ -1833,6 +1836,18 @@ func (s *EtcdServer) apply(
 			s.setAppliedIndex(e.Index)
 			s.setTerm(e.Term)
 			shouldStop = shouldStop || removedSelf
+
+			// etcdserver need to ensure the raft has already been notified
+			// or advanced before it responds to the client. Otherwise, the
+			// following config change request may be rejected.
+			// See https://github.com/etcd-io/etcd/issues/15528.
+			select {
+			case <-time.After(maxRaftAdvanceDelay):
```
[the remark this answers is not in the document]
Comment (chaochn47) [reply server/etcdserver/server.go:1845]: Second thought, from linearizability perspective, we should not. It was carried over from the original commit and I was thinking member promote response can be still be sent out even with slow disk with fsync latency because it has already applied even with failure.

File: server/etcdserver/server.go (hunk 1 above)
Comment (chaochn47) [reply server/etcdserver/server.go:111]: Will remove this hardcoded timeout value

**Comment by serathius** [comment]
This CL not only changes MemberPromote, but introduces a big change for all membership changes. We should double check that all configuration changes are properly tested. If not we should add a large set of e2e tests that:
* Grow cluster from 1  to 3 members (without learners)
* Grow cluster from 1 to 3 members (with learners) in both 1 at the time and two at one time scenario
* Reduce cluster from 3 to 1 member 
etc

**Comment by chaochn47** [comment]
> Can #15528 be easily reproduced? If not, then we need to add an integration test; we can intentionally inject a sleep failpoint before [r.Advanced()](https://github.com/etcd-io/etcd/blob/22f3e50adafd9d4cf9dd29dd5837483a6417238c/server/etcdserver/raft.go#L310)

Hi @ahrtr could you please help clarify how would integration test inject a sleep failpoint? I know with etcd binary built with gofail enabled it is achievable. https://github.com/etcd-io/etcd/blob/b75499437b8eb5d0e027b3abfb19932359aebf9b/tests/framework/e2e/etcd_process.go#L298-L318 Thanks to @serathius as part of the robustness test work.

**Comment by ahrtr** [comment]
> Hi @ahrtr could you please help clarify how would integration test inject a sleep failpoint? I know with etcd binary built with gofail enabled it is achievable.

Please refer to the followings,
1. the section "Test" in https://docs.google.com/document/d/1U9hAcZQp3Y36q_JFiw2VBJXVAo2dK2a-8Rsbqv3GgDo/edit#heading=h.wwktogcu1ekk. 
2. https://github.com/etcd-io/bbolt/blob/97d2cc34ac943a03ca596d15e0629b163468f59f/Makefile#L77

**Comment by chaochn47** [comment]
Ping @serathius @ahrtr @fuweid @tjungblu @jmhbnz for review ~

**Review by jmhbnz — COMMENTED** [review]
A comment to respond to review ping. I've read through this pr a few times and at a code level it looks good, however I'm abstaining from hitting approve as I don't understand overall system implications well enough.

**Review by serathius — APPROVED** [review]

**Review by tjungblu — APPROVED** [review]
/lgtm (non-binding)

Thanks for finally fixing this!

File: server/etcdserver/server.go [hunk 3]
```diff
@@ -1673,6 +1674,11 @@ func (s *EtcdServer) configure(ctx context.Context, cc raftpb.ConfChange) ([]*me
 			lg.Panic("failed to configure")
 		}
 		resp := x.(*confChangeResponse)
+		// etcdserver need to ensure the raft has already been notified
+		// or advanced before it responds to the client. Otherwise, the
+		// following config change request may be rejected.
+		// See https://github.com/etcd-io/etcd/issues/15528.
+		<-resp.raftAdvanceC
```
Comment (ahrtr) [inline server/etcdserver/server.go:1681]: This can work, but I'd suggest not to change the API layer. Let's get all the details encapsulated on the raft & etcd application layer, and the API layer should be agnostic to the raft & application side details. 

Please try to follow my original PR https://github.com/etcd-io/etcd/pull/15703/files

Comment (chaochn47) [reply server/etcdserver/server.go:1681]: The original PR waits for the added `raftAdvanceC`, however `raftAdvanceC` will not be sent because it is blocked until 'applyAll' calls 'applyWait.Trigger'. It's a deadlock and will be stuck forever. 

https://github.com/etcd-io/etcd/blob/6cdc9ae4fe1258247de1f7de372b3e8f0f0ea555/server/etcdserver/raft.go#L293-L310

It can be easily reproduced in [TestEnableAuth](https://github.com/etcd-io/etcd/blob/e9edc5432cffce26d53906528ecd125dfae3a699/server/embed/auth_test.go#L24) with https://github.com/etcd-io/etcd/commit/2d4c8eca3b3e51e2b3c43beefa35279955ea7c3d. In a single-node cluster, its first entry and committed entry type is `confChangeAdd` will be blocked in apply forever.

Comment (chaochn47) [reply server/etcdserver/server.go:1681]: I am open to considering other solutions, but I believe that it should be fixed just like this PR.

**Review by fuweid — APPROVED** [review]
LGTM

Thanks!

File: server/etcdserver/server.go (hunk 3 above)
Comment (ahrtr) [reply server/etcdserver/server.go:1681]: Got it, thx for the clarification. 

But I think the implementation is slowly rotting. It's getting harder to understand and maintain. We should consider simplifying the implementation per my above comment https://github.com/etcd-io/etcd/pull/15708#discussion_r1243435646.

**Review by ahrtr — APPROVED** [review]

File: server/etcdserver/server.go (hunk 3 above)
Comment (chaochn47) [reply server/etcdserver/server.go:1681]: Agreed. I feel it's inevitable because of the `r.Advance()` is invoked after `r.transport.Send(msgs)`. However, I doubt the reason of this ordering and pending for investigation. 

Changing the order might be risky so I lean towards to this fix (just for now).
