### PR TITLE
etcdmain,embed: document JSON/YAML config integer requirement for duration fields

### LINKED ISSUE #20342: --watch-progress-notify-interval doesn't work through JSON config
### Bug report criteria

- [x] This bug report is not security related, security issues should be disclosed privately via security@etcd.io.
- [x] This is not a support request or question, support requests or questions should be raised in the etcd [discussion forums](https://github.com/etcd-io/etcd/discussions).
- [x] You have read the etcd [bug reporting guidelines](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/reporting_bugs.md).
- [x] Existing open issues along with etcd [frequently asked questions](https://etcd.io/docs/latest/faq) have been checked and this is not a duplicate.

### What happened?

I got this error from etcd when setting `"watch-progress-notify-interval": "1m",` in a JSON config. I assume that passing it as a flag from the commandline does work.

```
[etcdmain/etcd.go:66] failed to verify flags
error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go struct field configYAML.watch-progress-notify-interval of type time.Duration
```

I suspect this is because `time.Duration` doesn't have an `UnmarshalJSON` method, so there's nothing doing the duration parsing. It can be given as an integer, but then it's interpreted as nanoseconds.

Both `watch-progress-notify-interval` and `experimental-watch-progress-notify-interval` exhibit this behavior.

### What did you expect to happen?

It to work the same as passing `--watch-progress-notify-interval=1m`.

### How can we reproduce it (as minimally and precisely as possible)?

Add `"experimental-watch-progress-notify-interval": "1m",` to JSON.

### Etcd version (please run commands below)

<details>

```console
etcd Version: 3.6.1
Git SHA: a4708be
Go Version: go1.23.10
Go OS/Arch: linux/amd64
```

</details>

### PR DESCRIPTION
**Pull request by alliasgher**
## What this PR does

The `--watch-progress-notify-interval` flag accepts human-readable strings (e.g. `"10m"`) via `flag.DurationVar` on the command line, but reading the same field from a JSON or YAML config file fails with an unmarshalling error because `time.Duration` (int64) only accepts integer values in nanoseconds.

This was decided to be addressed via documentation (see discussion in #20342).

This PR adds notes in two places:

1. **`server/etcdmain/help.go`** — adds a note to the `--watch-progress-notify-interval` help text explaining that config files require an integer in nanoseconds.
2. **`server/embed/config.go`** — expands the `WatchProgressNotifyInterval` struct comment to document the same limitation.

Fixes #20342

### CODE REVIEW

**Comment by ivanvc** [comment]
This caveat applies to all duration configuration options, not just `watch-progress-notify-interval`.

**Comment by alliasgher** [comment]
Good point. Moved the caveat in 3e3500c to two places where it applies generically:

- `usageline` `--config-file` section — note that duration-typed fields in the config file require integer nanoseconds, with a few concrete examples (`--heartbeat-interval`, `--election-timeout`, `--watch-progress-notify-interval`)
- `embed.Config` struct doc comment — same note for SDK users reading the godoc

Reverted the per-field help/struct comments so the message is not duplicated.

File: server/embed/config.go [hunk 1]
```diff
@@ -157,6 +157,11 @@ func init() {
 }
 
 // Config holds the arguments for configuring an etcd server.
+//
+// Note: time.Duration fields in this struct are unmarshalled from JSON/YAML
+// as integer nanoseconds (e.g. 600000000000 for 10 minutes). Human-readable
+// duration strings such as "10m" are only accepted by the equivalent
+// command-line flags, not by the configuration file.
```
Comment (ivanvc) [inline server/embed/config.go:164]: Suggestion to append the known limitation (aligning with https://github.com/etcd-io/website/pull/1149).

```suggestion
// command-line flags, not by the configuration file.
// This is a [known Go standard library limitation](https://github.com/golang/go/issues/10275)
// where time.Duration is unmarshaled as a plain integer.
```

**Review by ivanvc — COMMENTED** [review]
/ok-to-test

File: server/embed/config.go (hunk 1 above)
Comment (alliasgher) [reply server/embed/config.go:164]: Applied in e932d31 — thanks for the pointer to the website PR, good to keep the wording aligned.

**Comment by ivanvc** [comment]
Thanks for the changes, @alliasgher. Can you please squash your commits? After that it should be ready to merge.

**Comment by alliasgher** [comment]
Squashed into a single commit (da81f1b) — thanks @ivanvc.

**Review by ivanvc — APPROVED** [review]
LGTM. Thanks, @alliasgher.

**Review by ahrtr — APPROVED** [review]
Thanks for the contribution!
