### PR TITLE
tests: add robustness test for issue 17780

### LINKED ISSUE #17780: Revision decreasing after panic during compaction
### Bug report criteria

- [x] This bug report is not security related, security issues should be disclosed privately via [etcd maintainers](mailto:etcd-maintainers@googlegroups.com).
- [x] This is not a support request or question, support requests or questions should be raised in the etcd [discussion forums](https://github.com/etcd-io/etcd/discussions).
- [x] You have read the etcd [bug reporting guidelines](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/reporting_bugs.md).
- [x] Existing open issues along with etcd [frequently asked questions](https://etcd.io/docs/latest/faq) have been checked and this is not a duplicate.

### What happened?

Failure in https://github.com/etcd-io/etcd/actions/runs/8659974818

image

### What did you expect to happen?

Revision doesn't decrease

### How can we reproduce it (as minimally and precisely as possible)?

Follow https://github.com/etcd-io/etcd/tree/main/tests/robustness#re-evaluate-existing-report to validate report from https://github.com/etcd-io/etcd/actions/runs/8659974818

Run `TestRobustnessExploratory/Kubernetes/LowTraffic/ClusterOfSize1` with failpoint `compactBeforeSetFinishedCompact=panic()`

### Anything else we need to know?

TODO:
* [x] Try to reproduce the issue
* [x] Try to reproduce the issue on amd64

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
# paste output here

$ etcdctl version
# paste output here
```

</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by fuweid**
Closes #17780 

Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Comment by fuweid** [comment]
ping @ahrtr @serathius @siyuanfoundation

File: tests/robustness/traffic/etcd.go [hunk 1]
```diff
@@ -61,6 +61,18 @@ var (
 			{choice: LargePut, weight: 5},
 		},
 	}
+	// Issue17780EtcdPutDelete is to create high chance to have more delete
+	// requests so that it's likely to compact that revision which is tombstone.
+	Issue17780EtcdPutDelete = etcdTraffic{
```
Comment (siyuanfoundation) [inline tests/robustness/traffic/etcd.go:66]: Could this be inline if it is not used by any other tests?

Comment (fuweid) [reply tests/robustness/traffic/etcd.go:66]: You mean inline is about anonymous value during assignment?
`etcdTraffic` is unexported type and `choiceWeight` is alsog unexported type...
I think it's hard to make it inline if I understand it correctly.

Comment (siyuanfoundation) [reply tests/robustness/traffic/etcd.go:66]: I see. How about just name it to `EtcdPutDeleteHeavy`?

**Comment by serathius** [comment]
I would like to better understand why this is not aligned with exploratory tests. The goal is to incorporate regressions into exploratory testing, not just create a new scenario.

File: tests/robustness/traffic/etcd.go (hunk 1 above)
Comment (serathius) [reply tests/robustness/traffic/etcd.go:66]: +1 incorporating it with exploratory testing.

File: tests/robustness/failpoint/gofail.go [hunk 2]
```diff
@@ -59,6 +59,15 @@ var (
...
 	RaftAfterSaveSleep                       Failpoint = gofailSleepAndDeactivate{"raftAfterSave", time.Second}
+
+	// AllowBatchCompactBeforeSetFinishedCompactPanic is used to trigger
+	// that compactBeforeSetFinishedCompact failpoint only if the current
+	// revision number is higher than that batch limit.
+	AllowBatchCompactBeforeSetFinishedCompactPanic Failpoint = goPanicFailpoint{
+		failpoint: "compactBeforeSetFinishedCompact",
+		trigger:   triggerCompact{multiBatchCompaction: true},
+		target:    AnyMember,
+	}
```
Comment (serathius) [inline tests/robustness/failpoint/gofail.go:70]:
```suggestion
	CompactBeforeSetFinishedCompactPanic Failpoint = goPanicFailpoint{"compactBeforeSetFinishedCompact", triggerCompact{multiBatchCompaction: true}, AnyMember}
```

File: tests/robustness/makefile.mk [hunk 3]
```diff
@@ -84,6 +89,24 @@ $(GOPATH)/bin/gofail: tools/mod/go.mod tools/mod/go.sum
 	  make gofail-enable; \
 	  make build;
 
+# NOTE: The commit 6b034466 is to introduce compactBeforeSetFinishedCompact
+# failpoint and only >= v3.5.14 releases contain failpoint. In order to reproduce
+# the issue 17780, we have to clone the whole branch and checkout that commit.
+# So that built etcd binary won't contain fix patch for issue 17780.
+#
```
Comment (serathius) [inline tests/robustness/makefile.mk:96]:
```suggestion
```

File: tests/robustness/scenarios.go [hunk 4]
```diff
@@ -198,5 +198,24 @@ func regressionScenarios(t *testing.T) []testScenario {
 			cluster:   *e2e.NewConfig(opts...),
 		})
 	}
+	scenarios = append(scenarios, testScenario{
+		name:      "Issue17780",
+		failpoint: failpoint.AllowBatchCompactBeforeSetFinishedCompactPanic,
+		profile: traffic.Profile{
```
Comment (serathius) [inline tests/robustness/scenarios.go:204]: Let's wait for #17968 to be fixed and then remove custom traffic profile

File: tests/robustness/makefile.mk (hunk 3 above)
Comment (fuweid) [reply tests/robustness/makefile.mk]: Removed

File: tests/robustness/failpoint/gofail.go (hunk 2 above)
Comment (fuweid) [reply tests/robustness/failpoint/gofail.go:70]: Hi @serathius , `CompactBeforeSetFinishedCompactPanic` is already existing at https://github.com/etcd-io/etcd/blob/57907746e39da97ed3ce2fbd1f97e8ceb2ce8199/tests/robustness/failpoint/gofail.go#L47 Do you mean that I should replace existing one?

I add new one here because this issue has a requirement that the compactor has to delete tombstone in one batch and update `UnsafeSetFinishedCompact` value in next round. IMO, it's better to have two go-failpoints here.

File: tests/robustness/scenarios.go (hunk 4 above)
Comment (fuweid) [reply tests/robustness/scenarios.go]: Updated

File: tests/robustness/traffic/etcd.go (hunk 1 above)
Comment (fuweid) [reply tests/robustness/traffic/etcd.go:68]: Hi @siyuanfoundation  @serathius , I want to keep it with special name here because it's hard to reproduce it without special input or setting. If we put it into exploratory testing, existing case might have chance to reproduce it. But it's unknown for us. I was trying many combinations of traffic but it runs one day without luck. And then we introduce compact traffic, it also makes it hard to trigger issue 17780. 

If you have better idea, please let me know. Thanks

File: tests/robustness/failpoint/gofail.go (hunk 2 above)
Comment (serathius) [reply tests/robustness/failpoint/gofail.go:70]: We can have both, best to even duplicate all failpoints with triggerCompact to have option with and without multiBatchCompaction.

File: tests/robustness/traffic/etcd.go (hunk 1 above)
Comment (serathius) [reply tests/robustness/traffic/etcd.go:68]: I would prefer to avoid having a issue specific traffic, to prevent regressions in robustness we don't need 100% reproducability, about 2-5% is ok.

**Comment by serathius** [comment]
See https://github.com/etcd-io/etcd/pull/17680 for an example of how to add new repro. I adjusted couple of parameters https://github.com/etcd-io/etcd/pull/17680

**Comment by serathius** [comment]
ping any progress?

File: tests/robustness/traffic/etcd.go (hunk 1 above)
Comment (fuweid) [reply tests/robustness/traffic/etcd.go:68]: I was trying to use existing traffic to reproduce it. Unfortunately, I run it for 3 days. No luck :(

Comment (serathius) [reply tests/robustness/traffic/etcd.go:68]: let me take a look at it

**Comment by fuweid** [comment]
Hi @serathius I switched to use `kubernetes` profile and can reproduce it in my local.
I pick up 300 as batch limit and this value might be different from different local env.
Anyway, I can reproduce it without introducing new profile. :)

```
/tmp/etcd-v3.5.13-compactBeforeSetFinishedCompact/bin/etcd (TestRobustnessRegressionIssue17780-test-0) (2582032): {"level":"info","ts":"2024-11-11T20:23:03.747816Z","caller":"mvcc/index.go:214","msg":"compact tree index","revision":301}
    logger.go:146: 2024-11-11T20:23:03.748Z	INFO	Waiting for member to exit	{"member": "TestRobustnessRegressionIssue17780-test-0"}
/tmp/etcd-v3.5.13-compactBeforeSetFinishedCompact/bin/etcd (TestRobustnessRegressionIssue17780-test-0) (2582032): panic: failpoint panic: {}
/tmp/etcd-v3.5.13-compactBeforeSetFinishedCompact/bin/etcd (TestRobustnessRegressionIssue17780-test-0) (2582032):
/tmp/etcd-v3.5.13-compactBeforeSetFinishedCompact/bin/etcd (TestRobustnessRegressionIssue17780-test-0) (2582032): goroutine 181 [running]:
/tmp/etcd-v3.5.13-compactBeforeSetFinishedCompact/bin/etcd (TestRobustnessRegressionIssue17780-test-0) (2582032): go.etcd.io/gofail/runtime.actPanic(0x2?)
/tmp/etcd-v3.5.13-compactBeforeSetFinishedCompact/bin/etcd (TestRobustnessRegressionIssue17780-test-0) (2582032): 	go.etcd.io/gofail@v0.2.0/runtime/terms.go:324 +0xc6
/tmp/etcd-v3.5.13-compactBeforeSetFinishedCompact/bin/etcd (TestRobustnessRegressionIssue17780-test-0) (2582032): go.etcd.io/gofail/runtime.(*term).do(...)
/tmp/etcd-v3.5.13-compactBeforeSetFinishedCompact/bin/etcd (TestRobustnessRegressionIssue17780-test-0) (2582032): 	go.etcd.io/gofail@v0.2.0/runtime/terms.go:293
/tmp/etcd-v3.5.13-compactBeforeSetFinishedCompact/bin/etcd (TestRobustnessRegressionIssue17780-test-0) (2582032): go.etcd.io/gofail/runtime.(*terms).eval(0xc0008e9360)
/tmp/etcd-v3.5.13-compactBeforeSetFinishedCompact/bin/etcd (TestRobustnessRegressionIssue17780-test-0) (2582032): 	go.etcd.io/gofail@v0.2.0/runtime/terms.go:108 +0xec
/tmp/etcd-v3.5.13-compactBeforeSetFinishedCompact/bin/etcd (TestRobustnessRegressionIssue17780-test-0) (2582032): go.etcd.io/gofail/runtime.(*Failpoint).Acquire(0x12c?)
/tmp/etcd-v3.5.13-compactBeforeSetFinishedCompact/bin/etcd (TestRobustnessRegressionIssue17780-test-0) (2582032): 	go.etcd.io/gofail@v0.2.0/runtime/failpoint.go:45 +0x71
/tmp/etcd-v3.5.13-compactBeforeSetFinishedCompact/bin/etcd (TestRobustnessRegressionIssue17780-test-0) (2582032): go.etcd.io/etcd/server/v3/mvcc.(*store).scheduleCompaction(0xc00038f520, 0x12d, 0xffffffffffffffff)
/tmp/etcd-v3.5.13-compactBeforeSetFinishedCompact/bin/etcd (TestRobustnessRegressionIssue17780-test-0) (2582032): 	go.etcd.io/etcd/server/v3/mvcc/kvstore_compaction.go:62 +0x6ed
/tmp/etcd-v3.5.13-compactBeforeSetFinishedCompact/bin/etcd (TestRobustnessRegressionIssue17780-test-0) (2582032): go.etcd.io/etcd/server/v3/mvcc.(*store).compact.func1({0x12bab08, 0xc000040a00})
/tmp/etcd-v3.5.13-compactBeforeSetFinishedCompact/bin/etcd (TestRobustnessRegressionIssue17780-test-0) (2582032): 	go.etcd.io/etcd/server/v3/mvcc/kvstore.go:247 +0x85
/tmp/etcd-v3.5.13-compactBeforeSetFinishedCompact/bin/etcd (TestRobustnessRegressionIssue17780-test-0) (2582032): go.etcd.io/etcd/pkg/v3/schedule.(*fifo).run(0xc0001324e0)
/tmp/etcd-v3.5.13-compactBeforeSetFinishedCompact/bin/etcd (TestRobustnessRegressionIssue17780-test-0) (2582032): 	go.etcd.io/etcd/pkg/v3@v3.5.13/schedule/schedule.go:157 +0x105
/tmp/etcd-v3.5.13-compactBeforeSetFinishedCompact/bin/etcd (TestRobustnessRegressionIssue17780-test-0) (2582032): created by go.etcd.io/etcd/pkg/v3/schedule.NewFIFOScheduler in goroutine 1
/tmp/etcd-v3.5.13-compactBeforeSetFinishedCompact/bin/etcd (TestRobustnessRegressionIssue17780-test-0) (2582032): 	go.etcd.io/etcd/pkg/v3@v3.5.13/schedule/schedule.go:70 +0x156
    logger.go:146: 2024-11-11T20:23:03.772Z	INFO	server exited	{"name": "TestRobustnessRegressionIssue17780-test-0", "code": 2}
    logger.go:146: 2024-11-11T20:23:03.772Z	INFO	Member exited as expected	{"member": "TestRobustnessRegressionIssue17780-test-0"}
    logger.go:146: 2024-11-11T20:23:03.773Z	INFO	starting server...	{"name": "TestRobustnessRegressionIssue17780-test-0"}
    logger.go:146: 2024-11-11T20:23:03.773Z	INFO	spawning process	{"args": ["/tmp/etcd-v3.5.13-compactBeforeSetFinishedCompact/bin/etcd", "--name=TestRobustnessRegressionIssue17780-test-0", "--listen-client-urls=http://localhost:20000", "--advertise-client-urls=http://localhost:20000", "--listen-peer-urls=http://localhost:20001", "--initial-advertise-peer-urls=http://localhost:20001", "--initial-cluster-token=new", "--data-dir", "/tmp/TestRobustnessRegressionIssue17780506300824/001", "--snapshot-count=1000", "--snapshot-count=1000", "--initial-cluster-token=new", "--experimental-compaction-batch-limit=300", "--initial-cluster=TestRobustnessRegressionIssue17780-test-0=http://localhost:20001", "--initial-cluster-state=new"], "working-dir": "/tmp/TestRobustnessRegression120504966/001", "name": "TestRobustnessRegressionIssue17780-test-0", "environment-variables": ["GOFAIL_HTTP=127.0.0.1:12381", "ETCD_VERIFY=all", "EXPECT_DEBUG=true", "PATH=/home/weifu/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.2.linux-amd64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/weifu/.fzf/bin:/usr/local/go/bin:/home/weifu/go/bin:/opt/bin:/opt/fuwei/bin:/usr/local/go/bin:/home/weifu/go/bin:/opt/bin:/opt/fuwei/bin:/usr/local/go/bin:/home/weifu/go/bin:/opt/bin:/opt/fuwei/bin", "ETCD_UNSUPPORTED_ARCH=amd64"]}
/tmp/etcd-v3.5.13-compactBeforeSetFinishedCompact/bin/etcd (TestRobustnessRegressionIssue17780-test-0) (2582049): {"level":"warn","ts":"2024-11-11T20:23:03.783792Z","caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_VERIFY=all"}
/tmp/etcd-v3.5.13-compactBeforeSetFinishedCompact/bin/etcd (TestRobustnessRegressionIssue17780-test-0) (2582049): {"level":"warn","ts":"2024-11-11T20:23:03.783843Z","caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_UNSUPPORTED_ARCH=amd64"}
/tmp/etcd-v3.5.13-compactBeforeSetFinishedCompact/bin/etcd (TestRobustnessRegressionIssue17780-test-0) (2582049): {"level":"warn","ts":"2024-11-11T20:23:03.784023Z","caller":"embed/config.go:679","msg":"Running http and grpc server on single port. This is not recommended for production."}
/tmp/etcd-v3.5.13-compactBeforeSetFinishedCompact/bin/etcd (TestRobustnessRegressionIssue17780-test-0) (2582049): {"level":"info","ts":"2024-11-11T20:23:03.784065Z","caller":"etcdmain/etcd.go:73","msg":"Running: ","args":["/tmp/etcd-v3.5.13-compactBeforeSetFinishedCompact/bin/etcd","--name=TestRobustnessRegressionIssue17780-test-0","--listen-client-urls=http://localhost:20000","--advertise-client-urls=http://localhost:20000","--listen-peer-urls=http://localhost:20001","--initial-advertise-peer-urls=http://localhost:20001","--initial-cluster-token=new","--data-dir","/tmp/TestRobustnessRegressionIssue17780506300824/001","--snapshot-count=1000","--snapshot-count=1000","--initial-cluster-token=new","--experimental-compaction-batch-limit=300","--initial-cluster=TestRobustnessRegressionIssue17780-test-0=http://localhost:20001","--initial-cluster-state=new"]}
/tmp/etcd-v3.5.13-compactBeforeSetFinishedCompact/bin/etcd (TestRobustnessRegressionIssue17780-test-0) (2582049): {"level":"info","ts":"2024-11-11T20:23:03.784148Z","caller":"etcdmain/etcd.go:116","msg":"server has been already initialized","data-dir":"/tmp/TestRobustnessRegressionIssue17780506300824/001","dir-type":"member"}
/tmp/etcd-v3.5.13-compactBeforeSetFinishedCompact/bin/etcd (TestRobustnessRegressionIssue17780-test-0) (2582049): {"level":"warn","ts":"2024-11-11T20:23:03.784181Z","caller":"embed/config.go:679","msg":"Running http and grpc server on single port. This is not recommended for production."}
/tmp/etcd-v3.5.13-compactBeforeSetFinishedCompact/bin/etcd (TestRobustnessRegressionIssue17780-test-0) (2582049): {"level":"info","ts":"2024-11-11T20:23:03.784202Z","caller":"embed/etcd.go:127","msg":"configuring peer listeners","listen-peer-urls":["http://localhost:20001"]}
/tmp/etcd-v3.5.13-compactBeforeSetFinishedCompact/bin/etcd (TestRobustnessRegressionIssue17780-test-0) (2582049): {"level":"info","ts":"2024-11-11T20:23:03.78472Z","caller":"embed/etcd.go:135","msg":"configuring client listeners","listen-client-urls":["http://localhost:20000"]}
/tmp/etcd-v3.5.13-compactBeforeSetFinishedCompact/bin/etcd (TestRobustnessRegressionIssue17780-test-0) (2582049): {"level":"info","ts":"2024-11-11T20:23:03.784833Z","caller":"embed/etcd.go:308","msg":"starting an etcd server","etcd-version":"3.5.13","git-sha":"c9063a0-FAILPOINTS","go-version":"go1.22.2","go-os":"linux","go-arch":"amd64","max-cpu-set":8,"max-cpu-available":8,"member-initialized":true,"name":"TestRobustnessRegressionIssue17780-test-0","data-dir":"/tmp/TestRobustnessRegressionIssue17780506300824/001","wal-dir":"","wal-dir-dedicated":"","member-dir":"/tmp/TestRobustnessRegressionIssue17780506300824/001/member","force-new-cluster":false,"heartbeat-interval":"100ms","election-timeout":"1s","initial-election-tick-advance":true,"snapshot-count":1000,"max-wals":5,"max-snapshots":5,"snapshot-catchup-entries":5000,"initial-advertise-peer-urls":["http://localhost:20001"],"listen-peer-urls":["http://localhost:20001"],"advertise-client-urls":["http://localhost:20000"],"listen-client-urls":["http://localhost:20000"],"listen-metrics-urls":[],"cors":["*"],"host-whitelist":["*"],"initial-cluster":"","initial-cluster-state":"new","initial-cluster-token":"","quota-backend-bytes":2147483648,"max-request-bytes":1572864,"max-concurrent-streams":4294967295,"pre-vote":true,"initial-corrupt-check":false,"corrupt-check-time-interval":"0s","compact-check-time-enabled":false,"compact-check-time-interval":"1m0s","auto-compaction-mode":"periodic","auto-compaction-retention":"0s","auto-compaction-interval":"0s","discovery-url":"","discovery-proxy":"","downgrade-check-interval":"5s"}
/tmp/etcd-v3.5.13-compactBeforeSetFinishedCompact/bin/etcd (TestRobustnessRegressionIssue17780-test-0) (2582049): {"level":"info","ts":"2024-11-11T20:23:03.789807Z","caller":"etcdserver/backend.go:81","msg":"opened backend db","path":"/tmp/TestRobustnessRegressionIssue17780506300824/001/member/snap/db","took":"4.809657ms"}
/tmp/etcd-v3.5.13-compactBeforeSetFinishedCompact/bin/etcd (TestRobustnessRegressionIssue17780-test-0) (2582049): {"level":"info","ts":"2024-11-11T20:23:03.790272Z","caller":"etcdserver/server.go:532","msg":"No snapshot found. Recovering WAL from scratch!"}
/tmp/etcd-v3.5.13-compactBeforeSetFinishedCompact/bin/etcd (TestRobustnessRegressionIssue17780-test-0) (2582049): {"level":"info","ts":"2024-11-11T20:23:03.790861Z","caller":"etcdserver/raft.go:530","msg":"restarting local member","cluster-id":"34f27e83b3bc2ff","local-member-id":"ca50e9357181d758","commit-index":442}
/tmp/etcd-v3.5.13-compactBeforeSetFinishedCompact/bin/etcd (TestRobustnessRegressionIssue17780-test-0) (2582049): {"level":"info","ts":"2024-11-11T20:23:03.790965Z","logger":"raft","caller":"etcdserver/zap_raft.go:77","msg":"ca50e9357181d758 switched to configuration voters=()"}
/tmp/etcd-v3.5.13-compactBeforeSetFinishedCompact/bin/etcd (TestRobustnessRegressionIssue17780-test-0) (2582049): {"level":"info","ts":"2024-11-11T20:23:03.791005Z","logger":"raft","caller":"etcdserver/zap_raft.go:77","msg":"ca50e9357181d758 became follower at term 2"}
/tmp/etcd-v3.5.13-compactBeforeSetFinishedCompact/bin/etcd (TestRobustnessRegressionIssue17780-test-0) (2582049): {"level":"info","ts":"2024-11-11T20:23:03.791028Z","logger":"raft","caller":"etcdserver/zap_raft.go:77","msg":"newRaft ca50e9357181d758 [peers: [], term: 2, commit: 442, applied: 0, lastindex: 442, lastterm: 2]"}
/tmp/etcd-v3.5.13-compactBeforeSetFinishedCompact/bin/etcd (TestRobustnessRegressionIssue17780-test-0) (2582049): {"level":"warn","ts":"2024-11-11T20:23:03.79358Z","caller":"auth/store.go:1241","msg":"simple token is not cryptographically signed"}
/tmp/etcd-v3.5.13-compactBeforeSetFinishedCompact/bin/etcd (TestRobustnessRegressionIssue17780-test-0) (2582049): {"level":"info","ts":"2024-11-11T20:23:03.796085Z","caller":"mvcc/kvstore.go:407","msg":"kvstore restored","current-rev":300}
/tmp/etcd-v3.5.13-compactBeforeSetFinishedCompact/bin/etcd (TestRobustnessRegressionIssue17780-test-0) (2582049): {"level":"warn","ts":"2024-11-11T20:23:03.796109Z","caller":"mvcc/kvstore.go:411","msg":"compaction encountered error","error":"mvcc: required revision is a future revision"}
/tmp/etcd-v3.5.13-compactBeforeSetFinishedCompact/bin/etcd (TestRobustnessRegressionIssue17780-test-0) (2582049): {"level":"info","ts":"2024-11-11T20:23:03.796142Z","caller":"mvcc/kvstore.go:414","msg":"resume scheduled compaction","meta-bucket-name":"meta","meta-bucket-name-key":"scheduledCompactRev","scheduled-compact-revision":301}
```

```highlight
/tmp/etcd-v3.5.13-compactBeforeSetFinishedCompact/bin/etcd (TestRobustnessRegressionIssue17780-test-0) (2582032): {"level":"info","ts":"2024-11-11T20:23:03.747816Z","caller":"mvcc/index.go:214","msg":"compact tree index","revision":301}

/tmp/etcd-v3.5.13-compactBeforeSetFinishedCompact/bin/etcd (TestRobustnessRegressionIssue17780-test-0) (2582049): {"level":"info","ts":"2024-11-11T20:23:03.796085Z","caller":"mvcc/kvstore.go:407","msg":"kvstore restored","current-rev":300}
/tmp/etcd-v3.5.13-compactBeforeSetFinishedCompact/bin/etcd (TestRobustnessRegressionIssue17780-test-0) (2582049): {"level":"warn","ts":"2024-11-11T20:23:03.796109Z","caller":"mvcc/kvstore.go:411","msg":"compaction encountered error","error":"mvcc: required revision is a future revision"}
```

ping @ahrtr @ivanvc @jmhbnz

**Comment by ahrtr** [comment]
> I pick up 300 as batch limit and this value might be different from different local env.
> Anyway, I can reproduce it without introducing new profile. :)

A quick question, did you reproduce the issue on the latest code of main branch or did you just reproduce it on the code before the fix?

File: tests/robustness/failpoint/trigger.go [hunk 5]
```diff
@@ -72,7 +72,7 @@ func (t triggerCompact) Trigger(ctx context.Context, _ *testing.T, member e2e.Et
 			return nil, fmt.Errorf("failed to get revision: %w", err)
 		}
 
-		if !t.multiBatchCompaction || rev > int64(clus.Cfg.ServerConfig.ExperimentalCompactionBatchLimit) {
+		if !t.multiBatchCompaction || rev >= int64(clus.Cfg.ServerConfig.ExperimentalCompactionBatchLimit) {
```
Comment (serathius) [inline tests/robustness/failpoint/trigger.go:75]: How this change is related? Does it help with repro? I assumed ">" was intentional as we want have additional revision to ensure 2 batches execute.

**Review by serathius — APPROVED** [review]
Managed to reproduce the issue within ~100 runs.

File: tests/robustness/failpoint/trigger.go (hunk 5 above)
Comment (fuweid) [reply tests/robustness/failpoint/trigger.go]: Yeah. Reverted this change.
