### PR TITLE
Fix races in TestLessorRenewExtendPileup

### LINKED ISSUE #18538: [release-3.4] Races in TestLessorRenewExtendPileup TestLessorDetach
### Which Github Action / Prow Jobs are flaking?

Running `make test-unit` on release-3.4 branch detects races for me

### Which tests are flaking?

TestLessorRenewExtendPileup and TestLessorDetach

### Github Action / Prow Job link

_No response_

### Reason for failure (if possible)

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by lucasrod16**
Fixes #18538

Refactors `lessor` functions and `TestLessorRenewExtendPileup` to not operate on the global variable `leaseRevokeRate`.  Passes `leaseRevokeRate` as a `LessorConfig` option to fix the race conditions described in #18538.

Multiple goroutines were concurrently modifying the global variable resulting in the race conditions.

### CODE REVIEW

**Review by serathius — APPROVED** [review]

**Comment by serathius** [comment]
cc @ahrtr

File: server/lease/lessor.go [hunk 1]
```diff
@@ -198,6 +201,7 @@ type LessorConfig struct {
 	CheckpointInterval         time.Duration
 	ExpiredLeasesRetryInterval time.Duration
 	CheckpointPersist          bool
+	LeaseRevokeRate            int
```
Comment (ahrtr) [inline server/lease/lessor.go:204]: Usually an exported field can be configured by users, but this field is just used internally for now.  We can export it and allow users to change its value if needed in future.
```suggestion
	leaseRevokeRate            int
```

Comment (serathius) [reply server/lease/lessor.go:204]: +1

Comment (lucasrod16) [reply server/lease/lessor.go]: @ahrtr thanks for the feedback. Updated to make `leaseRevokeRate` a private field

**Review by ahrtr — APPROVED** [review]
LGTM

Thanks @lucasrod16 

Could you please backport the fix to 3.5 and. 3.4? Thanks.

**Comment by lucasrod16** [comment]
@ahrtr no problem! Here are the backport PRs for 3.4 and 3.5: #18569 #18570
