### PR TITLE
etcdserver: fix incorrect metrics generated when clients cancel watches

### LINKED ISSUE #10289: gRPC code Unavailable instead Canceled
After this PR https://github.com/etcd-io/etcd/pull/9178 we get:

It's in **etcd** running with parameter `--log-package-levels=debug`:

    ...
    etcdserver/api/v3rpc: failed to receive watch request from gRPC stream ("rpc error: code = Unavailable desc = stream error: stream ID 61; CANCEL")
    etcdserver/api/v3rpc: failed to receive watch request from gRPC stream ("rpc error: code = Unavailable desc = stream error: stream ID 78; CANCEL")
    ...
in my prometheus i see: 

    sum by(grpc_type, grpc_service, grpc_code) (grpc_server_handled_total{grpc_code="Unavailable", job="etcd", grpc_type="bidi_stream"}) = 4172

But it seems to me, this not error, and should not fall under [Unavailable Code](https://github.com/grpc/grpc-go/blob/master/codes/codes.go#L139)
> Unavailable indicates the service is currently unavailable. This is a most likely a transient condition and may be corrected by retrying with a backoff. See litmus test above for deciding between FailedPrecondition, Aborted, and Unavailable.

It looks like [Canceled Code](https://github.com/grpc/grpc-go/blob/master/codes/codes.go#L35)
> Canceled indicates the operation was canceled (typically by the caller).

Now everyone who uses prometheus operator + alertmanager, get [this](https://github.com/coreos/prometheus-operator/blob/master/helm/exporter-kube-etcd/templates/etcd3.rules.yaml#L29) alert, because **CANCEL** falls under [Unavailable](https://github.com/etcd-io/etcd/blob/master/etcdserver/api/v3rpc/util.go#L113)

#9725, #9576, #9166 https://github.com/openshift/origin/issues/20311, https://github.com/coreos/prometheus-operator/issues/2046, and in [google groups](https://groups.google.com/forum/#!topic/etcd-dev/ujWldr3ys9M)

### PR DESCRIPTION
**Pull request by ironcladlou**
Before this patch, a client which cancels the context for a watch results in the
server generating a `rpctypes.ErrGRPCNoLeader` error that leads the recording of
a gRPC `Unavailable` metric in association with the client watch cancellation.
The metric looks like this:

    grpc_server_handled_total{grpc_code="Unavailable",grpc_method="Watch",grpc_service="etcdserverpb.Watch",grpc_type="bidi_stream"}

So, the watch server has misidentified the error as a server error and then
propagates the mistake to metrics, leading to a false indicator that the leader
has been lost. This false signal then leads to false alerting.

The commit 9c103dd0dedfc723cd4f33b6a5e81343d8a6bae7 introduced an interceptor which wraps
watch streams requiring a leader, causing those streams to be actively canceled
when leader loss is detected.

However, the error handling code assumes all stream context cancellations are
from the interceptor. This assumption is broken when the context was canceled
because of a client stream cancelation.

The core challenge is lack of information conveyed via `context.Context` which
is shared by both the send and receive sides of the stream handling and is
subject to cancellation by all paths (including the gRPC library itself). If any
piece of the system cancels the shared context, there's no way for a context
consumer to understand who cancelled the context or why.

To solve the ambiguity of the stream interceptor code specifically, this patch
introduces a custom context struct which the interceptor uses to expose a custom
error through the context when the interceptor decides to actively cancel a
stream. Now the consuming side can more safely assume a generic context
cancellation can be propagated as a cancellation, and the server generated
leader error is preserved and propagated normally without any special inference.

When a client cancels the stream, there remains a race in the error handling
code between the send and receive goroutines whereby the underlying gRPC error
is lost in the case where the send path returns and is handled first, but this
issue can be taken separately as no matter which paths wins, we can detect a
generic cancellation.

This is a replacement of https://github.com/etcd-io/etcd/pull/11375.

Fixes #10289, #9725, #9576, #9166

### CODE REVIEW

File: etcdserver/api/v3rpc/watch.go [hunk 1]
```diff
@@ -190,17 +194,32 @@ func (ws *watchServer) Watch(stream pb.Watch_WatchServer) (err error) {
...
+// the stream context and local leader state to detect leader loss. If the
+// reason is inconclusive, assume a client cancellation.
+func getClientStreamClosureError(ctx context.Context, statusGetter etcdserver.RaftStatusGetter) error {
+	err := ctx.Err()
+	if err == context.Canceled {
+		err = rpctypes.ErrGRPCWatchCanceled
+		if md, hasMetadata := metadata.FromIncomingContext(ctx); hasMetadata {
+			if rl := md[rpctypes.MetadataRequireLeaderKey]; len(rl) > 0 && rl[0] == rpctypes.MetadataHasLeader {
+				if statusGetter.Leader() == types.ID(raft.None) {
+					err = rpctypes.ErrGRPCNoLeader
```
Comment (ironcladlou) [inline etcdserver/api/v3rpc/watch.go:215]: Does anyone have an idea how to induce this state in an e2e test?

**Comment by ironcladlou** [comment]
I've added unit tests for the error determination logic, but have a question about additional e2e tests (https://github.com/etcd-io/etcd/pull/12196#discussion_r465834438).

I've done a little more digging and don't yet have any new insights as to whether it's possible to do more conclusive checks (https://github.com/etcd-io/etcd/pull/11375#discussion_r352907219) — maybe devising an e2e for the states in question would be useful in that regard. Even manual steps for inducing the more esoteric states would be useful as a jumping off point.

File: tests/e2e/metrics_test.go [hunk 2]
```diff
@@ -49,6 +49,7 @@ func metricsTest(cx ctlCtx) {
 		{"/metrics", fmt.Sprintf("etcd_mvcc_delete_total 3")},
 		{"/metrics", fmt.Sprintf(`etcd_server_version{server_version="%s"} 1`, version.Version)},
 		{"/metrics", fmt.Sprintf(`etcd_cluster_version{cluster_version="%s"} 1`, version.Cluster(version.Version))},
+		{"/metrics", fmt.Sprintf(`grpc_server_handled_total{grpc_code="Canceled",grpc_method="Watch",grpc_service="etcdserverpb.Watch",grpc_type="bidi_stream"} 6`)},
```
Comment (ironcladlou) [inline tests/e2e/metrics_test.go:52]: At the very least, this seems to clearly demonstrate the efficacy of the fix for the common case the PR was intended to address (generating the correct metric in response to a typical/normal watch close).

File: etcdserver/api/v3rpc/watch.go (hunk 1 above)
Comment (texasbobs) [reply etcdserver/api/v3rpc/watch.go:215]: I recently enabled metrics reporting and stumbled upon this, too.  I'm not able to reproduce it at will, though it does frequently.

**Comment by ironcladlou** [comment]
@xiang90 In https://github.com/etcd-io/etcd/pull/11375#discussion_r352907219 you seemed to indicate skepticism of this approach. Do you know of a specific alternative we should be pursuing instead?

**Comment by ironcladlou** [comment]
I'm going to circle back to the issue today to explore alternative fixes.

**Comment by ironcladlou** [comment]
So, looking at this with fresh eyes today, I observe a race condition here that explains the intermittent nature of the failure: https://github.com/etcd-io/etcd/blob/master/etcdserver/api/v3rpc/watch.go#L200

**Comment by ironcladlou** [comment]
Using the following reproducer program connected to an etcd server with default options:

```go
package main

import (
	"context"
	"fmt"
	"os"
	"time"

	"go.etcd.io/etcd/v3/clientv3"
)

func main() {
	client, err := clientv3.New(clientv3.Config{
		Endpoints: []string{"http://localhost:2379"},
	})
	if err != nil {
		fmt.Printf("failed to create an etcd client: %s\n", err)
		os.Exit(1)
	}
	ctx, cancel := context.WithCancel(context.Background())
	wchan := client.Watch(ctx, "watcher", clientv3.WithRev(3))
	go func() {
		time.Sleep(2)
		cancel()
	}()
	<-wchan
}
```

The following portion of [watch.go](https://github.com/etcd-io/etcd/blob/master/etcdserver/api/v3rpc/watch.go#L200) exhibits a race condition in stream error handling which seems to intermittently obfuscate the client/server nature of the error. Annotations inline:

```go
errc := make(chan error, 1)
// Ideally recvLoop would also use sws.wg to signal its completion
// but when stream.Context().Done() is closed, the stream's recv
// may continue to block since it uses a different context, leading to
// deadlock when calling sws.close().
go func() {
  if rerr := sws.recvLoop(); rerr != nil {
    if isClientCtxErr(stream.Context().Err(), rerr) {
      sws.lg.Debug("failed to receive watch request from gRPC stream", zap.Error(rerr))
    } else {
      sws.lg.Warn("failed to receive watch request from gRPC stream", zap.Error(rerr))
      streamFailures.WithLabelValues("receive", "watch").Inc()
    }
    errc <- rerr
  }
}()

// RACE CONDITION: when the client cancels the watch, two things happen simultaneously:
//
// 1. The stream recv goroutine handles the client error and pushes it into the `errc` channel
// 2. The stream.Context().Done() channel receives a context cancellation error
//
// Depending on the ordering, the following `select` will either handle the error as a client
// cancellation (when `errc` is handled first) or a server error (when `stream` is handled first).
select {
case err = <-errc:
  close(sws.ctrlStream)

case <-stream.Context().Done():
  err = stream.Context().Err()
  // the only server-side cancellation is noleader for now.
  if err == context.Canceled {
    err = rpctypes.ErrGRPCNoLeader
  }
}
```

**Comment by ironcladlou** [comment]
9c103dd0dedfc723cd4f33b6a5e81343d8a6bae7 introduced an interceptor which wraps watch streams requiring a leader, causing those streams to be actively canceled when leader loss is detected.

However, the error handling code assumes _all_ stream context cancellations are from the interceptor. This assumption is broken when the context was canceled because of a client stream cancelation, triggering the race condition.

Hopefully if I've gotten any of these details wrong, somebody will correct me.

**Comment by ironcladlou** [comment]
I think one of the central challenges here is the use of `context.WithCancel` which is too generic to convey to the consuming side who canceled and why. Any code which wants to branch based on the source of the cancelation has no access to the underlying cause (e.g. gRPC error from a client cancelation, or an interceptor decision) that ultimately led to a generic context cancelation.

Need to think more about this.

**Comment by ironcladlou** [comment]
Alright, I think I found a way to fix this more sensibly by introducing a new context type the interceptor can use to definitively signal when the cancellation is from the server (e.g. the interceptor) vs. a normal closure. PTAL.

**Comment by ironcladlou** [comment]
Tomorrow I can improve the test coverage here.

**Comment by ironcladlou** [comment]
The interceptor changes are covered by the existing `TestGRPCRequireLeader`, and I've added a test case for the metrics point via `TestV3MetricsInsecure`. I think the PR is ready for review.

**Comment by brancz** [comment]
cc @xiang90

**Comment by ironcladlou** [comment]
@xiang90 @hexfusion who can review this?

File: etcdserver/api/v3rpc/interceptor.go [hunk 3]
```diff
@@ -251,6 +257,38 @@ func newStreamInterceptor(s *etcdserver.EtcdServer) grpc.StreamServerInterceptor
...
+}
+
+func (c *leaderMonitoringContext) CancelForLeaderLoss() {
+	c.lock.Lock()
+	c.cancelReason = rpctypes.ErrGRPCNoLeader
+	c.lock.Unlock()
+	c.cancel()
+}
+
+func (c *leaderMonitoringContext) Err() error {
```
Comment (gyuho) [inline etcdserver/api/v3rpc/interceptor.go:283]: Can we document where this `Err` func is called?

File: etcdserver/api/v3rpc/interceptor.go [hunk 4]
```diff
@@ -231,8 +232,13 @@ func newStreamInterceptor(s *etcdserver.EtcdServer) grpc.StreamServerInterceptor
 					return rpctypes.ErrGRPCNoLeader
 				}
 
-				cctx, cancel := context.WithCancel(ss.Context())
-				ss = serverStreamWithCtx{ctx: cctx, cancel: &cancel, ServerStream: ss}
+				cancelCtx, cancelFn := context.WithCancel(ss.Context())
+				monitorCtx := &leaderMonitoringContext{
```
Comment (gyuho) [inline etcdserver/api/v3rpc/interceptor.go:236]: Do we really need this struct to wrap around the error? I am seeing the cancel func is only called in `monitorLeader` `(*ssWithCtx.cancel)()`. Maybe simpler to embed this error info in `serverStreamWithCtx` and implement `Err` method against it?

Comment (ironcladlou) [reply etcdserver/api/v3rpc/interceptor.go:236]: I'm not sure I understand your proposal. The `watchServer.Watch` method (in `v3rpc/watch.go`) handles the context cancellation and has only the context itself and its embedded error to interpret (via `Context.Err()`). The stdlib doesn't seem to provide any context implementations that allow errors to be injected, hence my wrapper. 

Would you be able to try explaining in more detail what you had in mind?

Comment (ironcladlou) [reply etcdserver/api/v3rpc/interceptor.go:236]: @gyuho friendly ping — I think what I have here solves the problem, and I'm not entirely clear on what the proposed alternative is. Can you please clarify?

Comment (gyuho) [reply etcdserver/api/v3rpc/interceptor.go:236]: @ironcladlou Sorry for delay. I will take another look today.

File: etcdserver/api/v3rpc/interceptor.go [hunk 5]
```diff
@@ -251,6 +257,38 @@ func newStreamInterceptor(s *etcdserver.EtcdServer) grpc.StreamServerInterceptor
 	}
 }
 
+// leaderMonitoringContext wraps a context and provides a custom error when
+// the CancelForLeaderLoss() method is used to cancel the context. This is
+// so downstream context users can disambiguate the reason for the cancellation
+// which could be from the client (for example) or from this interceptor code.
+type leaderMonitoringContext struct {
```
Comment (gyuho) [inline etcdserver/api/v3rpc/interceptor.go:264]: I was suggesting these fields can be just moved to:

```go
type serverStreamWithCtx struct {
   ...
```
?

File: etcdserver/api/v3rpc/interceptor.go (hunk 4 above)
Comment (gyuho) [reply etcdserver/api/v3rpc/interceptor.go:236]: > embedded error to interpret (via Context.Err()). The stdlib doesn't seem to provide any context implementations that allow errors to be injected, hence my wrapper.

Would combining these to `serverStreamWithCtx` make this simpler?

```
func (ssc serverStreamWithCtx) Err() error {
	c.lock.RLock()
	defer c.lock.RUnlock()
	if c.cancelReason != nil {
		return c.cancelReason
	}
	return c.Context.Err()
}
```

File: etcdserver/api/v3rpc/watch.go [hunk 6]
```diff
@@ -197,15 +197,25 @@ func (ws *watchServer) Watch(stream pb.Watch_WatchServer) (err error) {
...
 
+	// TODO: There's a race here. When a stream  is closed (e.g. due to a cancellation),
+	// the underlying error (e.g. a gRPC stream error) may be returned and handled
+	// through errc if the recv goroutine finishes before the send goroutine.
+	// When the recv goroutine wins, the stream error is retained. When recv loses
+	// the race, the underlying error is lost (unless the root error is propagated
+	// through Context.Err() which is not always the case (as callers have to decide
+	// to implement a custom context to do so). The stdlib context package builtins
+	// may be insufficient to carry semantically useful errors around and should be
+	// revisited.
```
Comment (gyuho) [inline etcdserver/api/v3rpc/watch.go:208]: Thanks for the detailed comment :+1:

File: etcdserver/api/v3rpc/interceptor.go (hunk 4 above)
Comment (ironcladlou) [reply etcdserver/api/v3rpc/interceptor.go]: @gyuho okay, I think I now see where you were going with this suggestion. I spent some more time thinking about it and came up with a slightly new factoring which I hope is easier to understand.

I greatly simplified the context responsibility with a `cancellableContext` struct which I hope now has very clear and self contained semantics. Then I made `serverStreamWithCtx` depend on a concrete `cancellableContext` and was able to move the specific cancellation error to the point it's actually generated instead of indirectly way out in the setup code like before.

I can still imagine a factoring where `cancellableContext` is moved into `serverStreamWithCtx` which itself would implement `context.Context`, but I currently think with the new factoring the `cancellableContext` is clear and self contained enough to keep it separate.

Let me know what you think — I really appreciate the feedback!

**Comment by jicki** [comment]
Hi guys, any update on this? Thanks in advance!

**Comment by sferich888** [comment]
@ironcladlou what do we need to do to progress this? 
/retest

**Comment by ironcladlou** [comment]
@sferich888 I'm waiting for feedback on the latest changes (https://github.com/etcd-io/etcd/pull/12196#discussion_r526455602) and for somebody to make a merge decision.

File: server/etcdserver/api/v3rpc/interceptor.go [hunk 7]
```diff
@@ -251,10 +252,52 @@ func newStreamInterceptor(s *etcdserver.EtcdServer) grpc.StreamServerInterceptor
...
+}
+
+// Cancel stores the cancellation reason and then delegates to context.WithCancel
+// against the parent context.
+func (c *cancellableContext) Cancel(reason error) {
+	c.lock.Lock()
+	c.cancelReason = reason
+	c.lock.Unlock()
+	c.cancel()
+}
```
Comment (ptabor) [inline server/etcdserver/api/v3rpc/interceptor.go:283]: I wonder whether the first cancelation reason is not more important than the last. 
In some sense all the following cancellations are being ignored if we are already Cancelling. 

Is it protection in depth, or we really see multiple cancellations of the same context ?

**Review by ptabor — APPROVED** [review]

File: etcdserver/api/v3rpc/interceptor.go (hunk 4 above)
Comment (ptabor) [reply etcdserver/api/v3rpc/interceptor.go]: It looks clear to me.
I would have some doubts if this 'alternative' context was a public class, but 
as long it stays private implementation detail (as in this case), I think its good.

**Comment by ptabor** [comment]
@ironcladlou Please retrigger the tests on this change. Not "green" changes have lower chances to get maintainers attention (when scanning the PR list). 
@gyuho Does the change LGTY ?

**Review by gyuho — APPROVED** [review]
lgtm thx

**Comment by gyuho** [comment]
@ironcladlou Can we highlight this in release 3.5 changelog and 3.4 if we need back ports?

**Comment by cfz** [comment]
should we also fix the LeaseKeepAlive api metric which share the same logic as the old watch?

**Comment by deniseschannon** [comment]
Will this be backported/can it be backported to 3.4?
