### PR TITLE
etcdmain: fix ignoring of ETCD_CONFIG_FILE env variable

### LINKED ISSUE #10747: ETCD_CONFIG_FILE env variable is ignored
etcd v3.3

etcd appears to recognize and then promptly ignore the **ETCD_CONFIG_FILE** environment variable. Passing the **--config-file** flag seems to work properly. As an example, create a super simplistic config file at _/etc/etcd/etcd.conf.yaml_ containing only 
`data-dir: /var/lib/etcd`

Setting **ETCD_CONFIG_FILE=/etc/etcd/etcd.conf.yaml** and trying to start etcd returns something similar to the following:
```
2019-05-21 17:32:51.695776 I | pkg/flags: recognized and used environment variable ETCD_CONFIG_FILE=/etc/etcd/etcd.conf.yaml  
2019-05-21 17:32:51.695920 I | etcdmain: etcd Version: 3.3.13  
2019-05-21 17:32:51.695929 I | etcdmain: Git SHA: 98d3084  
2019-05-21 17:32:51.695936 I | etcdmain: Go Version: go1.10.8  
2019-05-21 17:32:51.695942 I | etcdmain: Go OS/Arch: linux/amd64  
2019-05-21 17:32:51.695949 I | etcdmain: setting maximum number of CPUs to 40, total number of available CPUs is 40  
2019-05-21 17:32:51.695960 W | etcdmain: no data-dir provided, using default data-dir ./default.etcd  
2019-05-21 17:32:51.696439 I | embed: listening for peers on http://localhost:2380  
2019-05-21 17:32:51.696555 I | embed: listening for client requests on localhost:2379  
2019-05-21 17:32:51.696650 C | etcdmain: cannot access data directory: mkdir default.etcd: permission denied  
```

However, starting etcd with the **--config-file /etc/etcd/etcd.conf.yaml** works properly:
```
2019-05-21 17:33:57.303742 I | etcdmain: Loading server configuration from "/etc/etcd/etcd.conf.yaml"
2019-05-21 17:33:57.305112 I | etcdmain: etcd Version: 3.3.13
2019-05-21 17:33:57.305124 I | etcdmain: Git SHA: 98d3084
2019-05-21 17:33:57.305128 I | etcdmain: Go Version: go1.10.8
2019-05-21 17:33:57.305131 I | etcdmain: Go OS/Arch: linux/amd64
2019-05-21 17:33:57.305136 I | etcdmain: setting maximum number of CPUs to 40, total number of available CPUs is 40
2019-05-21 17:33:57.306523 N | etcdmain: the server is already initialized as member before, starting as etcd member...
2019-05-21 17:33:57.306815 I | embed: listening for peers on http://localhost:2380
2019-05-21 17:33:57.306916 I | embed: listening for client requests on localhost:2379
2019-05-21 17:33:57.325706 I | etcdserver: name = default
2019-05-21 17:33:57.325736 I | etcdserver: data dir = /var/lib/etcd
2019-05-21 17:33:57.325751 I | etcdserver: member dir = /var/lib/etcd/member
2019-05-21 17:33:57.325760 I | etcdserver: heartbeat = 100ms
2019-05-21 17:33:57.325772 I | etcdserver: election = 1000ms
2019-05-21 17:33:57.325782 I | etcdserver: snapshot count = 100000
2019-05-21 17:33:57.325803 I | etcdserver: advertise client URLs = http://localhost:2379
2019-05-21 17:33:57.335837 I | etcdserver: restarting member 8e9e05c52164694d in cluster cdf818194e3a8c32 at commit index 4
2019-05-21 17:33:57.335910 I | raft: 8e9e05c52164694d became follower at term 2
2019-05-21 17:33:57.335955 I | raft: newRaft 8e9e05c52164694d [peers: [], term: 2, commit: 4, applied: 0, lastindex: 4, lastterm: 2]
2019-05-21 17:33:57.340926 W | auth: simple token is not cryptographically signed
2019-05-21 17:33:57.342299 I | etcdserver: starting server... [version: 3.3.13, cluster version: to_be_decided]
2019-05-21 17:33:57.344222 I | etcdserver/membership: added member 8e9e05c52164694d [http://localhost:2380] to cluster cdf818194e3a8c32
2019-05-21 17:33:57.344395 N | etcdserver/membership: set the initial cluster version to 3.3
2019-05-21 17:33:57.344492 I | etcdserver/api: enabled capabilities for version 3.3
2019-05-21 17:33:58.738818 I | raft: 8e9e05c52164694d is starting a new election at term 2
2019-05-21 17:33:58.738866 I | raft: 8e9e05c52164694d became candidate at term 3
2019-05-21 17:33:58.738916 I | raft: 8e9e05c52164694d received MsgVoteResp from 8e9e05c52164694d at term 3
2019-05-21 17:33:58.738945 I | raft: 8e9e05c52164694d became leader at term 3
2019-05-21 17:33:58.738960 I | raft: raft.node: 8e9e05c52164694d elected leader 8e9e05c52164694d at term 3
2019-05-21 17:33:58.741399 I | etcdserver: published {Name:default ClientURLs:[http://localhost:2379]} to cluster cdf818194e3a8c32
2019-05-21 17:33:58.743342 I | embed: ready to serve client requests
2019-05-21 17:33:58.744298 N | embed: serving insecure client requests on 127.0.0.1:2379, this is strongly discouraged!
```

### PR DESCRIPTION
**Pull request by FrozenAndrey**
Fixes #10747

### CODE REVIEW

File: etcdmain/config.go [hunk 1]
```diff
@@ -283,6 +283,11 @@ func (cfg *config) parse(arguments []string) error {
 	}
 
 	var err error
+
```
Comment (jingyih) [inline etcdmain/config.go]: Maybe add a comment mentioning that we have to treat this env variable differently than the other env variables, because we need to determine whether to use or ignore the env variables based on if the config file is set.

File: etcdmain/config.go [hunk 2]
```diff
@@ -283,6 +283,11 @@ func (cfg *config) parse(arguments []string) error {
...
+	if cfg.configFile == "" {
+		cfg.configFile = os.Getenv("ETCD_CONFIG_FILE")
```
Comment (jingyih) [inline etcdmain/config.go]: Instead of hard-coding this env name, use `FlagToEnv()`.
https://github.com/etcd-io/etcd/blob/e8b940f268a80c14f7082589f60cbfd3de531d12/pkg/flags/flag.go#L70

**Comment by jingyih** [comment]
BTW, test failure is unrelated to this PR.

**Comment by spzala** [comment]
Re-running the failed build. @jingyih has already fixed the doc related problem in another fix.
