### PR TITLE
Fix the issue that cannot add a new member when one member is down, even if quorum is still satisfied

### LINKED ISSUE #21640: Cannot add a new member when one member is down, even if quorum is still satisfied
### Bug report criteria

- [ ] This bug report is not security related, security issues should be disclosed privately via security@etcd.io.
- [ ] This is not a support request or question, support requests or questions should be raised in the etcd [discussion forums](https://github.com/etcd-io/etcd/discussions).
- [ ] You have read the etcd [bug reporting guidelines](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/reporting_bugs.md).
- [ ] Existing open issues along with etcd [frequently asked questions](https://etcd.io/docs/latest/faq) have been checked and this is not a duplicate.

### What happened?

When adding a new member (even a learner),  the current logic requires the etcd member which receives the request to be fully connected to all peers, see link below. When there is one member down, it will reject the add member request. This doesn't make sense.

This issue prevents Cluster API from automatically recovering a cluster when 2 out of 5 members are down. See https://github.com/kubernetes/kubernetes/pull/138403

https://github.com/etcd-io/etcd/blob/3401a41e51e0b3a58309fd3422016831e529248a/server/etcdserver/server.go#L1423-L1433

### What did you expect to happen?

.

### How can we reproduce it (as minimally and precisely as possible)?

.

### Anything else we need to know?

_No response_

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
# paste output here

$ etcdctl version
# paste output here
```

</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

### Relevant log output

```Shell

```

### PR DESCRIPTION
**Pull request by ahrtr**
fix https://github.com/etcd-io/etcd/issues/21640

cc @fuweid @serathius

### CODE REVIEW

**Comment by serathius** [comment]
Think the requirements for all members available was by design. I would not change it without good understanding for the original motivation. Also, it's been like this for long time. I don't think we should rush the fix.

**Comment by ahrtr** [comment]
> I would not change it without good understanding for the original motivation. Also, it's been like this for long time. I don't think we should rush the fix.

read https://github.com/kubernetes/kubernetes/pull/138403

**Comment by ahrtr** [comment]
/retest


The bug was introduced in https://github.com/etcd-io/etcd/pull/10730

**Comment by ahrtr** [comment]
@ivanvc it's interesting that once I manually added the ok-to-test label, some workflows which are already green, are re-triggered/re-run.

**Comment by ahrtr** [comment]
> @ivanvc it's interesting that once I manually added the ok-to-test label, some workflows which are already green, are re-triggered/re-run.

It seems that your previous PR of automatically adding ok-to-test label is still not working

File: server/etcdserver/server.go [hunk 1]
```diff
@@ -1420,9 +1420,9 @@ func (s *EtcdServer) mayAddMember(memb membership.Member) error {
 		return errors.ErrNotEnoughStartedMembers
 	}
 
-	if !isConnectedFullySince(s.r.transport, time.Now().Add(-HealthInterval), s.MemberID(), s.cluster.VotingMembers()) {
+	if !isConnectedToQuorumSince(s.r.transport, time.Now().Add(-HealthInterval), s.MemberID(), s.cluster.VotingMembers()) {
```
Comment (fuweid) [inline server/etcdserver/server.go]: Revisit this comment - https://github.com/etcd-io/etcd/issues/10738#issuecomment-500181854

It's what I thought. maybe the user should retry it later.
Just don't want to get into any corner case.

**Comment by fuweid** [comment]
> The bug was introduced in https://github.com/etcd-io/etcd/pull/10730

I don't think so. it's just refactor. The check was introduced in https://github.com/etcd-io/etcd/pull/6106

File: server/etcdserver/server.go (hunk 1 above)
Comment (fuweid) [reply server/etcdserver/server.go]: If it's to replace the host or node, does user delete that member from cluster first?

Comment (ahrtr) [reply server/etcdserver/server.go]: > does user delete that member from cluster first?

Copied the slack message in sig-etcd and the description in the related issue below again:

> This issue prevents Cluster API from automatically recovering a cluster when 2 out of 5 members are down. See https://github.com/kubernetes/kubernetes/pull/138403

Comment (ahrtr) [reply server/etcdserver/server.go]: Note that there is 2 down members in a 5 member cluster. 

The cluster-api tries to replace two members one by one (remove it from etcd cluster, remove the VM, create a new one, add a learner, promote it later)...

Comment (ahrtr) [reply server/etcdserver/server.go]: One minor improvement would be to treat a newly added member (learner or voter) as temporarily unavailable when validating membership changes.

That means we count the new member as failed and check whether quorum would still hold.

Examples:

- 3-member cluster:
  If 1 member is already down, adding a new member makes it 4 members total.
  Assuming the new member is unavailable, 2 of 4 members are down, leaving only 2 running.
  Since quorum for 4 members is 3, the request should be rejected. 

- 5-member cluster:
  If 2 members are already down, adding a new member makes it 6 members total.
  Assuming the new member is unavailable, 3 of 6 members are down.
  Since quorum for 6 members is 4, the request should be rejected.

cluster-api is not affected because it usually removes failed members first before adding replacements.

Sounds good?

Comment (ahrtr) [reply server/etcdserver/server.go]: Updated. PTAL

Please take a look at the e2e test cases.  

This PR hold the original intention: if one member in a 3 member cluster is down, we reject adding a new member.

**Comment by ivanvc** [comment]
> > @ivanvc it's interesting that once I manually added the ok-to-test label, some workflows which are already green, are re-triggered/re-run.
> 
> It seems that your previous PR of automatically adding ok-to-test label is still not working

That's only for @k8s-infra-cherrypick-robot's pull request. It will automatically add the `ok-to-test` label to their pull requests.

Reference: https://github.com/etcd-io/etcd/blob/f3815932116c5d2edb91be9f0a63c7dc50127dc0/.github/workflows/cherrypick-bot-ok-to-test.yaml#L17-L20

You don't need to run `/ok-to-test` or add the `ok-to-test` label to any etcd-io member pull request. The workflows and Prow jobs automatically run for them.

File: server/etcdserver/server.go (hunk 1 above)
Comment (ahrtr) [reply server/etcdserver/server.go]: @ivanvc @jberkus we might want to update [document](https://etcd.io/docs/v3.6/op-guide/runtime-configuration/#add-a-new-member) as well.

In general, this PR relaxes the requirement, so it won't break any existing system.
- old behaviour: require the member fully connects to all peers
  - for example, assuming it's a 3 member cluster, and member 1 receives a memberAdd request, then member 1 must be fully connected to all peers, otherwise member 1 rejects the memberAdd request.
- new behaviour: only require the member connects to quorum of the member (assuming the new member to be added as failed). See comment above https://github.com/etcd-io/etcd/pull/21641#discussion_r3118504477

**Comment by ahrtr** [comment]
ping @fuweid @serathius

File: server/etcdserver/util.go [hunk 2]
```diff
@@ -25,8 +25,15 @@ import (
 
 // isConnectedToQuorumSince checks whether the local member is connected to the
 // quorum of the cluster since the given time.
-func isConnectedToQuorumSince(transport rafthttp.Transporter, since time.Time, self types.ID, members []*membership.Member) bool {
```
Comment (fuweid) [inline server/etcdserver/util.go:28]: I am wondering whether we should keep two purpose-specific helpers here instead of adding a generic `totalMembers` argument. `members` and `totalMembers` can describe different sets, so the caller has to know exactly which quorum denominator to pass. That makes the helper easy to misuse. 

Maybe we can make this explicit with two helpers, such as:


```go
func isConnectedToCurrentVotingQuorumSince(
      transport rafthttp.Transporter,
      since time.Time,
      self types.ID,
      voters []*membership.Member,
  ) bool {
      return numConnectedSince(transport, since, self, voters) >= quorum(len(voters))
  }
```

```go
 func isConnectedToQuorumAfterAddingVotingMemberSince(
      transport rafthttp.Transporter,
      since time.Time,
      self types.ID,
      currentVoters []*membership.Member,
  ) bool {
      if len(currentVoters) == 1 {
          // Preserve existing single-member recovery behavior.
          return true
      }
      return numConnectedSince(transport, since, self, currentVoters) >= quorum(len(currentVoters)+1)
  }
```

As you mentioned, adding a new voting member can increase the quorum size, so we still need to ensure enough existing voting members are active before accepting the reconfiguration. The idea looks good so far.

**Review by fuweid — COMMENTED** [review]
I don't currently have a concrete failing case for this change.

 However, `PromoteMember` uses a different safety model: it checks that the learner has caught up, then verifies the future quorum by started-member count. It does not require full transport connectivity for a `HealthInterval`. Given that, I think we should avoid making `isConnectedToQuorumSince` too generic with a caller-provided `totalMembers`; two purpose-
  specific helpers would make the intended semantics clearer and harder to misuse.

File: server/etcdserver/util.go (hunk 2 above)
Comment (ahrtr) [reply server/etcdserver/util.go:28]: > keep two purpose-specific helpers

Makes sense & updated.

**Review by fuweid — APPROVED** [review]
LGTM on green
