### PR TITLE
Check ScheduledCompactKeyName and FinishedCompactKeyName before writing hash

### LINKED ISSUE #15919: Incorrect hash when resuming scheduled compaction after etcd restarts
### What happened?

I tried out using the `--experimental-compact-hash-check-enabled` flag on my etcd cluster today, and I think I might have encountered a race condition when a server starts up/resumes a scheduled compaction that causes the hash value to be incorrect.

About my setup: I have a 5 member cluster, running as k8s pods. They already have the `--experimental-initial-corrupt-check` flag enabled.

I was adding the `--experimental-compact-hash-check-enabled` flag (and also upgrading from 3.5.6 to 3.5.9) on a 5-member node. For 3 of the 4 etcd members, I had already stopped the etcd pod, updated their container URLs to 3.5.9, added the new hash check flag, and then restarted the etcd pod. I then stopped the 4th follower (which I'll call FOO), edited its pod config, and brought it back up. I then stopped the leader, and did the same update/restart. This triggered a leader election, and one of the former followers (which I'll call BAR) became the new leader.

The new leader then performed the periodic compact hash check, as configured. But the strange thing is that, even though all of my pods were up and running (and had passed the initial corruption check), the very first periodic check failed!

Due to the liveness probe problem mentioned in https://github.com/etcd-io/etcd/issues/13340, I had to deal with my pods getting restarted by kube due to the alarm... But when I disarmed the CORRUPT alarm so my etcd pods could stay up and running, they all again passed the initial corrupt data check, and logged the same hashes for the following "storing new hash" logs. So that's why I suspect there was very unlucky timing and a race condition that caused FOO to calculate the wrong hash value and use that when BAR asked for its hash during that periodic compaction hash check.

### What did you expect to happen?

I expected the periodic compaction hash check to succeed and for my cluster be healthy because:
1) the initial data check passed on all members of the cluster
2) the hash/compact-revision that FOO logged with the "storing new hash" line both before and after the problematic hash matched the hashes in the rest of the cluster

### How can we reproduce it (as minimally and precisely as possible)?

I'm not sure how to reproduce it. Maybe create a multi-member cluster with enough data so that compaction takes a non-trivial amount of time, trigger a compaction, and then stop one of the members right in the middle of the compaction so that compaction fails and needs to resume compacting when it comes back up?

### Anything else we need to know?

I saw https://github.com/etcd-io/etcd/issues/15548, but that mentions the cluster ID changing, and in this scenario where just I'm restarting etcd with different flags, I don't think the cluster ID would change.

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
etcd Version: 3.5.9
Git SHA: bdbbde998
Go Version: go1.19.9
Go OS/Arch: linux/amd64

$ etcdctl version
etcdctl version: 3.5.9
API version: 3.5
```

</details>

### Etcd configuration (command line flags or environment variables)

<details>
(from a k8s pod manifest)

```
  - command:
    - etcd
    - --advertise-client-urls=https://XXX:2379
    - --cert-file=/etc/kubernetes/pki/etcd/server.crt
    - --client-cert-auth=true
    - --data-dir=/var/lib/etcd
    - --experimental-initial-corrupt-check=true
    - --experimental-compact-hash-check-enabled=true
    - --initial-advertise-peer-urls=https://XXX:2380
    - --initial-cluster-token=XXX
    - --initial-cluster=XXX
    - --initial-cluster-state=existing
    - --key-file=/etc/kubernetes/pki/etcd/server.key
    - --listen-client-urls=https://127.0.0.1:2379,https://XXX:2379
    - --listen-metrics-urls=http://127.0.0.1:2381,http://XXX:2381
    - --listen-peer-urls=https://XXX:2380
    - --name=XXX
    - --peer-cert-file=/etc/kubernetes/pki/etcd/peer.crt
    - --peer-client-cert-auth=true
    - --peer-key-file=/etc/kubernetes/pki/etcd/peer.key
    - --peer-trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
    - --snapshot-count=10000
    - --trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
    - --auto-compaction-mode=periodic
    - --auto-compaction-retention=1h
    - --quota-backend-bytes=15032385536
    image: registry.k8s.io/etcd:3.5.9-0
```

</details>

### Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# Lost due to pods being restarted, but you can see the endpoints and IDs below

# This endpoint status table was captured while the cluster was in the alarmed state
$ etcdctl --endpoints $endpoints endpoint status -w table
+--------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+----------------+
|      ENDPOINT      |        ID        | VERSION | DB SIZE | IS LEADER | IS LEARNER | RAFT TERM | RAFT INDEX | RAFT APPLIED INDEX |     ERRORS     |
+--------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+----------------+
|  XXX:2379 | 367806663aa1996c |   3.5.9 |  4.9 GB |     false |      false |        30 |  718184797 |          718184797 | alarm:CORRUPT  |
| XXX:2379 | 6069c22b85ee10b0 |   3.5.9 |  4.8 GB |      true |      false |        30 |  718184798 |          718184798 | alarm:CORRUPT  |
| XXX:2379 | 917d2067aeb00315 |   3.5.9 |  4.8 GB |     false |      false |        30 |  718184802 |          718184802 | alarm:CORRUPT  |
| XXX:2379 | b2529a8db451f246 |   3.5.9 |  4.8 GB |     false |      false |        30 |  718184804 |          718184804 | alarm:CORRUPT  |
|  XXX:2379 | e56f12f0d98830bb |   3.5.9 |  4.9 GB |     false |      false |        30 |  718184805 |          718184805 | alarm:CORRUPT  |
+--------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+----------------+
```

</details>

### Relevant log output

```shell
(not literal logs, but reconstructed from my investigation)

* 15:34:55 - all nodes log "storing new hash". revision=702700874 compact-revision=702656236 hash=483395635
* ... I update the other etcd nodes one by one
* 15:39:54 - FOO  starts shutting down
* 15:39:54 - every node but FOO logs "storing new hash" of hash=2533962327 for compact-revision=702700874 at revision=702739864.
* 15:39:54- FOO logs "Failed compaction" (because the etcd pod was terminating)
* 15:40:24 - Updated etcd pod on  FOO starts running
* 15:40:24 - FOO logs "resume scheduled compaction"
* 15:40:35 - FOO logs "storing new hash" of hash=2915350535 for compact-revision=702700874 at revision=702739864. (But every other node for this compact-revision had hash=2533962327)!
* 15:42:06 - BAR became leader
* 15:42:18 - BAR started compact hash check
* 15:42:18 -  BAR (leader) says "failed compaction hash check". For revision 702739864, leader had 2533962327, but follower FOO had hash 2915350535. BAR logged "alarm raised"
```

### PR DESCRIPTION
**Pull request by CaojiamingAlan**
Fix #15919 
Commit 1: add an e2e test to reproduce the problem. This test won't pass without the fix.
Commit 2: check ScheduledCompactKeyName and FinishedCompactKeyName
before writing hash to hashstore. If they do not match, then it means this compaction has once been interrupted and its hash value is invalid. In such cases, we won't write the hash values to the hashstore, and avoids the incorrect corruption alarm.

### CODE REVIEW

File: server/storage/mvcc/kvstore.go [hunk 1]
```diff
@@ -238,7 +247,11 @@ func (s *store) compact(trace *traceutil.Trace, rev, prevCompactRev int64) (<-ch
 			s.compactBarrier(context.TODO(), ch)
 			return
 		}
-		s.hashes.Store(hash)
+		// Only store the hash value is the previous hash is completed, i.e. this compaction
```
Comment (jmhbnz) [inline server/storage/mvcc/kvstore.go:250]: nit: looks like a small typo?

```suggestion
		// Only store the hash value if the previous hash is completed, i.e. this compaction
```

File: tests/e2e/corrupt_test.go [hunk 2]
```diff
@@ -193,3 +193,71 @@ func TestCompactHashCheckDetectCorruption(t *testing.T) {
...
+	)
+
+	t.Cleanup(func() {
+		if errC := epc.Close(); errC != nil {
+			t.Fatalf("error closing etcd processes (%v)", errC)
+		}
+	})
+
+	// Add a member to the cluster, assign it a very slow compaction speed, so that its compaction can be interrupted.
+	//
```
Comment (jmhbnz) [inline tests/e2e/corrupt_test.go:219]: Should this empty comment line be removed?

File: tests/e2e/corrupt_test.go [hunk 3]
```diff
@@ -193,3 +193,71 @@ func TestCompactHashCheckDetectCorruption(t *testing.T) {
...
+	if err != nil {
+		t.Fatalf("could not start etcd process cluster (%v)", err)
+	}
+
+	// Put 10 identical keys to the cluster, so that the compaction will drop some stale values.
+	t.Log("putting 10 values to the identical key...")
+	cc, err := e2e.NewEtcdctl(epc.Cfg.Client, epc.EndpointsGRPC())
+	assert.NoError(t, err)
+	for i := 0; i < 10; i++ {
+		//use the same key
```
Comment (jmhbnz) [inline tests/e2e/corrupt_test.go:234]: nit: spacing

```suggestion
		// Use the same key
```

**Review by jmhbnz — COMMENTED** [review]
Thanks for your work on this @CaojiamingAlan!

Still getting my head around the changes and linked issue, a few tiny nitpicks to consider after an initial read through.

**Comment by CaojiamingAlan** [comment]
Still need to make some changes to the tests using a fake store.

File: server/storage/mvcc/kvstore.go [hunk 4]
```diff
@@ -225,7 +225,16 @@ func (s *store) updateCompactRev(rev int64) (<-chan struct{}, int64, error) {
 	return nil, compactMainRev, nil
 }
 
-func (s *store) compact(trace *traceutil.Trace, rev, prevCompactRev int64) (<-chan struct{}, error) {
+// checkPrevCompactionCompleted checks whether the previous scheduled compaction is completed.
+func (s *store) checkPrevCompactionCompleted() bool {
+	s.b.ReadTx().Lock()
+	defer s.b.ReadTx().Unlock()
+	scheduledCompact, scheduledCompactFound := UnsafeReadScheduledCompact(s.b.ReadTx())
+	finishedCompact, finishedCompactFound := UnsafeReadFinishedCompact(s.b.ReadTx())
```
Comment (serathius) [inline server/storage/mvcc/kvstore.go:233]:
```suggestion
	tx := s.b.ReadTx()
	defer tx.Unlock()
	scheduledCompact, scheduledCompactFound := UnsafeReadScheduledCompact(tx)
	finishedCompact, finishedCompactFound := UnsafeReadFinishedCompact(tx)
```

File: server/storage/mvcc/store.go [hunk 5]
```diff
@@ -19,15 +19,7 @@ import (
...
-func UnsafeReadFinishedCompact(tx backend.ReadTx) (finishedComact int64, found bool) {
-	_, finishedCompactBytes := tx.UnsafeRange(schema.Meta, schema.FinishedCompactKeyName, nil, 0)
-	if len(finishedCompactBytes) != 0 {
-		return bytesToRev(finishedCompactBytes[0]).main, true
-	}
-	return 0, false
-}
-
-func UnsafeReadScheduledCompact(tx backend.ReadTx) (scheduledComact int64, found bool) {
+func UnsafeReadScheduledCompact(tx backend.ReadTx) (scheduledCompact int64, found bool) {
```
Comment (serathius) [inline server/storage/mvcc/store.go:22]: Please don't reorder the functions, it mudies the git history.

File: tests/e2e/corrupt_test.go [hunk 6]
```diff
@@ -193,3 +193,69 @@ func TestCompactHashCheckDetectCorruption(t *testing.T) {
...
+		e2e.WithClusterSize(1),
+	)
+
+	t.Cleanup(func() {
+		if errC := epc.Close(); errC != nil {
+			t.Fatalf("error closing etcd processes (%v)", errC)
+		}
+	})
+
+	// Add a member to the cluster, assign it a very slow compaction speed, so that its compaction can be interrupted.
```
Comment (serathius) [inline tests/e2e/corrupt_test.go:218]: Why not create 3 node cluster? I would prefer to avoid reconfiguring member flags if possible.

File: tests/e2e/corrupt_test.go [hunk 7]
```diff
@@ -193,3 +193,69 @@ func TestCompactHashCheckDetectCorruption(t *testing.T) {
...
+		assert.NoError(t, err, "error on put")
+	}
+
+	// HACK: manually change the --experimental-compaction-sleep-interval to a small value,
+	// so that the compaction can finish.
+	// todo: add disable method to robustness/failpoint interface
+	t.Log("compaction started...")
+	_, err = cc.Compact(ctx, 5, config.CompactOption{})
+	for i, arg := range epc.Procs[1].Config().Args {
+		if arg == "--experimental-compaction-sleep-interval" {
```
Comment (serathius) [inline tests/e2e/corrupt_test.go:243]: Please avoid using args modification. It's not readable.

File: tests/e2e/corrupt_test.go [hunk 8]
```diff
@@ -193,3 +193,69 @@ func TestCompactHashCheckDetectCorruption(t *testing.T) {
...
+			epc.Procs[1].Config().Args[i+1] = "1ms"
+		}
+	}
+
+	t.Log("restart proc 1 to interrupt its compaction...")
+	err = epc.Procs[1].Restart(ctx)
+
+	t.Log("sleeping 5 sec to let nodes do compact hash check...")
+	time.Sleep(5 * time.Second)
```
Comment (serathius) [inline tests/e2e/corrupt_test.go:252]: Can we wait for etcd to write a log that hash check completed instead of waiting arbitrary 5s?

File: tests/e2e/corrupt_test.go [hunk 9]
```diff
@@ -193,3 +194,106 @@ func TestCompactHashCheckDetectCorruption(t *testing.T) {
...
+	if err != nil {
+		t.Fatalf("can't get log indicating finished scheduled compaction")
+	}
+
+	leaderIndex := epc.WaitLeader(t)
+	_, err = epc.Procs[leaderIndex].Logs().ExpectFunc(ctx, func(s string) bool {
+		// NB: there are several possible branches in CompactHashCheck(),
+		// need to check each of them to confirm the check is finished,
+		// otherwise this ExpectFunc would be blocked.
+		// todo log "finished compaction hash check" on every possible branch
```
Comment (jmhbnz) [inline tests/e2e/corrupt_test.go:274]: nit: Write as `// TODO:` to align with etcd standard way of writing todo comments in case someone is searching codebase in future to identify.

```diff
-// todo log "finished compaction hash check" on every possible branch
+// TODO: log "finished compaction hash check" on every possible branch
```

**Comment by serathius** [comment]
Please mark conversations as resolved if you have addressed the comment.

File: tests/e2e/corrupt_test.go [hunk 10]
```diff
@@ -193,3 +194,106 @@ func TestCompactHashCheckDetectCorruption(t *testing.T) {
...
+	if err != nil {
+		t.Fatalf("can't get log indicating finished scheduled compaction")
+	}
+
+	leaderIndex := epc.WaitLeader(t)
+	_, err = epc.Procs[leaderIndex].Logs().ExpectFunc(ctx, func(s string) bool {
+		// NB: there are several possible branches in CompactHashCheck(),
+		// need to check each of them to confirm the check is finished,
+		// otherwise this ExpectFunc would be blocked.
+		// TODO: log "finished compaction hash check" on every possible branch
```
Comment (serathius) [inline tests/e2e/corrupt_test.go:274]: Could you implement the TODO?

File: tests/framework/e2e/cluster.go [hunk 11]
```diff
@@ -813,6 +821,33 @@ func (epc *EtcdProcessCluster) StartNewProc(ctx context.Context, cfg *EtcdProces
...
+	epc.Cfg.SetInitialOrDiscovery(serverCfg, initialCluster, "new")
+
+	proc, err := NewEtcdProcess(serverCfg)
+	if err != nil {
+		return err
+	}
+	err = epc.Procs[i].Close()
+	if err != nil {
+		return err
+	}
```
Comment (serathius) [inline tests/framework/e2e/cluster.go:846]: UpdateProcOptions function stopping a process is a little unexpected for me. I know that to override the `epc.Procs[i] = proc` you need to stop old process, but the approach here is not very natural. 

What about `UpdateProcOptions` expecting that `epc.Procs[i]` is already stopped and assert that? Before calling `UpdateProcOptions` test should close the process.

**Review by jmhbnz — APPROVED** [review]
LGTM - Thanks @CaojiamingAlan 👍🏻

**Comment by serathius** [comment]
cc @ahrtr

File: tests/framework/e2e/etcd_process.go [hunk 12]
```diff
@@ -62,6 +62,7 @@ type EtcdProcess interface {
 
 type LogsExpect interface {
 	ExpectWithContext(context.Context, string) (string, error)
+	ExpectFunc(ctx context.Context, f func(string) bool) (string, error)
```
Comment (ahrtr) [inline tests/framework/e2e/etcd_process.go:65]: Why add `ExpectFunc`?

Comment (CaojiamingAlan) [reply tests/framework/e2e/etcd_process.go:65]: Because once I expected multiple strings(different branches may have different logs). But after adding the logs it is not needed. However I think it provides more flexibility and is something good to have so I didn't delete it.

Comment (ahrtr) [reply tests/framework/e2e/etcd_process.go:65]: It makes no sense to add something which is not used at all.

Please remove it in this PR, and If you really think it's useful, let's discuss it separately.

File: tests/e2e/corrupt_test.go [hunk 13]
```diff
@@ -193,3 +193,95 @@ func TestCompactHashCheckDetectCorruption(t *testing.T) {
...
+	_, err = epc.Procs[slowCompactionNodeIndex].Logs().ExpectWithContext(ctx, "finished scheduled compaction")
+	if err != nil {
+		t.Fatalf("can't get log indicating finished scheduled compaction")
+	}
+
+	leaderIndex := epc.WaitLeader(t)
+	_, err = epc.Procs[leaderIndex].Logs().ExpectWithContext(ctx, "finished compaction hash check")
+	if err != nil {
+		t.Fatalf("can't get log indicating finished compaction hash check")
+	}
```
Comment (ahrtr) [inline tests/e2e/corrupt_test.go:277]: same as above

File: tests/e2e/corrupt_test.go [hunk 14]
```diff
@@ -193,3 +193,95 @@ func TestCompactHashCheckDetectCorruption(t *testing.T) {
...
+
+	alarmResponse, err := cc.AlarmList(ctx)
+	assert.NoError(t, err, "error on alarm list")
+	for _, alarm := range alarmResponse.Alarms {
+		if alarm.Alarm == etcdserverpb.AlarmType_CORRUPT {
+			t.Fatalf("there should be no corruption after resuming the compaction, but corruption detected")
```
Comment (ahrtr) [inline tests/e2e/corrupt_test.go:283]: same as above

**Review by ahrtr — COMMENTED** [review]
Overall look good to me, with a couple of minor comments.

File: tests/e2e/corrupt_test.go [hunk 15]
```diff
@@ -193,3 +193,95 @@ func TestCompactHashCheckDetectCorruption(t *testing.T) {
...
+		e2e.WithCompactHashCheckEnabled(true),
+		e2e.WithCompactHashCheckTime(checkTime),
+		e2e.WithClusterSize(3),
+		e2e.WithDataDirPath(dataDirPath),
+		e2e.WithLogLevel("info"),
+	)
+	epc, err := e2e.InitEtcdProcessCluster(t, cfg)
+	if err != nil {
+		t.Fatalf("could not init etcd process cluster (%v)", err)
+	}
```
[the remark this answers is not in the document]
Comment (serathius) [reply tests/e2e/corrupt_test.go:220]: Could we make sure this suggestion is obvious to reviewers next time. Maybe we should have a test writing guide for contributors? Do you know what percent of files are using `require.NoError` vs `if err != nil { t.Fatal(...)}`?

cc @jmhbnz

[the remark this answers is not in the document]
Comment (jmhbnz) [reply tests/e2e/corrupt_test.go:220]: For a rough estimation (inside `tests/`):

```bash
find | grep ".go" | xargs grep -il "require.noerror" | wc -l
24

find | grep ".go" | xargs grep -Pzol 'if err != nil.*(\n|.)*t.Fatal' | wc -l
107
```

Obviously just a quick ball park but looks like only about 25% of test files are using `require.NoError` currently.

Agree we could highlight this as something important for reviewers to call out. If folks are on board with it I'm happy to make an issue so we don't forget.

File: tests/e2e/corrupt_test.go [hunk 16]
```diff
@@ -193,3 +195,81 @@ func TestCompactHashCheckDetectCorruption(t *testing.T) {
...
+func TestCompactHashCheckDetectCorruptionInterrupt(t *testing.T) {
+	checkTime := time.Second
+	e2e.BeforeTest(t)
+	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
+	defer cancel()
+
+	slowCompactionNodeIndex := 1
+
+	// Start a new cluster, with compact hash check enabled.
+	t.Log("creating a new cluster with 1 node...")
```
Comment (chaochn47) [inline tests/e2e/corrupt_test.go:208]: 3 nodes.

**Review by chaochn47 — APPROVED** [review]
LGTM (non-binding)

**Review by ahrtr — APPROVED** [review]
LGTM

Thanks @CaojiamingAlan

File: tests/e2e/corrupt_test.go [hunk 17]
```diff
@@ -20,6 +20,8 @@ import (
 	"testing"
 	"time"
 
+	"github.com/stretchr/testify/require"
+
```
Comment (ahrtr) [inline tests/e2e/corrupt_test.go:24]: remove the blank line?

**Comment by ahrtr** [comment]
@CaojiamingAlan could you backport this PR to 3.5?

**Comment by CaojiamingAlan** [comment]
@ahrtr Sure, does it mean proposing a PR to merge this change to the release-3.5 branch?

**Comment by ahrtr** [comment]
> @ahrtr Sure, does it mean proposing a PR to merge this change to the release-3.5 branch?

Yes. Please note that `release-3.5` has big difference with `main` branch, so please try not to cherry-pick the commit.
