### PR TITLE
use v2 api to update cluster version

### LINKED ISSUE #12987: 3.4 to 3.5 upgrade may panic
Originally reported by @chaochn47 https://github.com/etcd-io/etcd/pull/11427/files#r633271675

We've added a new internal raft request field here https://github.com/etcd-io/etcd/pull/11427, but we did not have the test coverage where cluster version is already 3.5 but minority are still in 3.4. As a result, monitoring and persisting cluster versions using v3 crashes 3.4 nodes.

> Looks like these two fields made v3.5 to v3.4 downgrade fail.
> 
> Can we make it an experimental API in v3.4 and add these two fields to make downgrade from v3.5 to v3.4 possible?
> 
> ```
> panic: not implemented
> 
> goroutine 214 [running]:
> go.etcd.io/etcd/etcdserver.(*applierV3backend).Apply(0xc000238468, 0xc0002b2460, 0x0)
>         /home/chaochn/workplace/EKS-etcd/src/EKS-etcd/etcdserver/apply.go:173 +0xf85
> go.etcd.io/etcd/etcdserver.(*authApplierV3).Apply(0xc000242000, 0xc0002b2460, 0x0)
>         /home/chaochn/workplace/EKS-etcd/src/EKS-etcd/etcdserver/apply_auth.go:60 +0xd2
> go.etcd.io/etcd/etcdserver.(*EtcdServer).applyEntryNormal(0xc000290600, 0xc0002d14d8)
>         /home/chaochn/workplace/EKS-etcd/src/EKS-etcd/etcdserver/server.go:2230 +0x1fb
> go.etcd.io/etcd/etcdserver.(*EtcdServer).apply(0xc000290600, 0xc000302a80, 0xa, 0xc, 0xc0001c8000, 0x0, 0xc000046000, 0xc00033f640)
>         /home/chaochn/workplace/EKS-etcd/src/EKS-etcd/etcdserver/server.go:2144 +0x579
> go.etcd.io/etcd/etcdserver.(*EtcdServer).applyEntries(0xc000290600, 0xc0001c8000, 0xc00002c000)
>         /home/chaochn/workplace/EKS-etcd/src/EKS-etcd/etcdserver/server.go:1396 +0xe5
> go.etcd.io/etcd/etcdserver.(*EtcdServer).applyAll(0xc000290600, 0xc0001c8000, 0xc00002c000)
>         /home/chaochn/workplace/EKS-etcd/src/EKS-etcd/etcdserver/server.go:1120 +0x88
> go.etcd.io/etcd/etcdserver.(*EtcdServer).run.func8(0x11b6e30, 0xc0005da040)
>         /home/chaochn/workplace/EKS-etcd/src/EKS-etcd/etcdserver/server.go:1065 +0x3c
> go.etcd.io/etcd/pkg/schedule.(*fifo).run(0xc0003c0180)
>         /home/chaochn/workplace/EKS-etcd/src/EKS-etcd/pkg/schedule/schedule.go:157 +0xf3
> created by go.etcd.io/etcd/pkg/schedule.NewFIFOScheduler
>         /home/chaochn/workplace/EKS-etcd/src/EKS-etcd/pkg/schedule/schedule.go:70 +0x13b
> ```

### PR DESCRIPTION
**Pull request by chaochn47**
Fix #12987

```
{
  "level":"info",
  "ts":"2021-05-17T18:28:27.564Z",
  "caller":"membership/cluster.go:522",
  "msg":"updated cluster version",
  "cluster-id":"ef37ad9dc622a7c4",
  "local-member-id":"6f7e5687e0b95471",
  "from":"3.4",
  "to":"3.5"
}
```

## Testing cluster version upgrade from 3.4 to 3.5
```
rm -rf /home/chaochn/log/etcd/
mkdir -p /home/chaochn/log/etcd

# create 3.4 cluster
~/etcd/release-3.4/etcd --name infra1 \
--listen-client-urls http://127.0.0.1:2379 \
--advertise-client-urls http://127.0.0.1:2379 \
--listen-peer-urls http://127.0.0.1:12380 \
--initial-advertise-peer-urls http://127.0.0.1:12380 \
--initial-cluster-token etcd-cluster-1 --initial-cluster 'infra1=http://127.0.0.1:12380,infra2=http://127.0.0.1:22380,infra3=http://127.0.0.1:32380' --initial-cluster-state new \
--enable-pprof > /home/chaochn/log/etcd/infra1.log 2>&1 &

~/etcd/release-3.4/etcd --name infra2 \
--listen-client-urls http://127.0.0.1:22379 \
--advertise-client-urls http://127.0.0.1:22379 \
--listen-peer-urls http://127.0.0.1:22380 \
--initial-advertise-peer-urls http://127.0.0.1:22380 \
--initial-cluster-token etcd-cluster-1 --initial-cluster 'infra1=http://127.0.0.1:12380,infra2=http://127.0.0.1:22380,infra3=http://127.0.0.1:32380' --initial-cluster-state new \
--enable-pprof > /home/chaochn/log/etcd/infra2.log 2>&1 &

~/etcd/release-3.4/etcd --name infra3 \
--listen-client-urls http://127.0.0.1:32379 \
--advertise-client-urls http://127.0.0.1:32379 \
--listen-peer-urls http://127.0.0.1:32380 \
--initial-advertise-peer-urls http://127.0.0.1:32380 \
--initial-cluster-token etcd-cluster-1 --initial-cluster 'infra1=http://127.0.0.1:12380,infra2=http://127.0.0.1:22380,infra3=http://127.0.0.1:32380' --initial-cluster-state new \
--enable-pprof > /home/chaochn/log/etcd/infra3.log 2>&1 &

# upgrade to 3.5
## first
ETCDCTL_API=3 ~/etcd/release-3.4/etcdctl --endpoints http://127.0.0.1:2379,http://127.0.0.1:22379 member remove fd422379fda50e48
ETCDCTL_API=3 ~/etcd/release-3.4/etcdctl --endpoints http://127.0.0.1:2379,http://127.0.0.1:22379 member add infra4 --peer-urls=http://127.0.0.1:32381

~/etcd/3.5.0-alpha.0/etcd --name infra4 \
--listen-client-urls http://127.0.0.1:32379 \
--advertise-client-urls http://127.0.0.1:32379 \
--listen-peer-urls http://127.0.0.1:32381 \
--initial-advertise-peer-urls http://127.0.0.1:32381 \
--initial-cluster-token etcd-cluster-1 --initial-cluster 'infra1=http://127.0.0.1:12380,infra2=http://127.0.0.1:22380,infra4=http://127.0.0.1:32381' --initial-cluster-state existing \
--enable-pprof > /home/chaochn/log/etcd/infra4.log 2>&1 &

## second
ETCDCTL_API=3 ~/etcd/release-3.4/etcdctl --endpoints http://127.0.0.1:2379,http://127.0.0.1:32379 member remove 91bc3c398fb3c146
ETCDCTL_API=3 ~/etcd/release-3.4/etcdctl --endpoints http://127.0.0.1:2379,http://127.0.0.1:32379 member add infra5 --peer-urls=http://127.0.0.1:22381

~/etcd/3.5.0-alpha.0/etcd --name infra5 \
--listen-client-urls http://127.0.0.1:22379 \
--advertise-client-urls http://127.0.0.1:22379 \
--listen-peer-urls http://127.0.0.1:22381 \
--initial-advertise-peer-urls http://127.0.0.1:22381 \
--initial-cluster-token etcd-cluster-1 --initial-cluster 'infra1=http://127.0.0.1:12380,infra5=http://127.0.0.1:22381,infra4=http://127.0.0.1:32381' --initial-cluster-state existing \
--enable-pprof > /home/chaochn/log/etcd/infra5.log 2>&1 &

## third
ETCDCTL_API=3 ~/etcd/release-3.4/etcdctl --endpoints http://127.0.0.1:22379,http://127.0.0.1:32379 member remove 8211f1d0f64f3269
ETCDCTL_API=3 ~/etcd/release-3.4/etcdctl --endpoints http://127.0.0.1:22379,http://127.0.0.1:32379 member add infra6 --peer-urls=http://127.0.0.1:12381

~/etcd/3.5.0-alpha.0/etcd --name infra6 \
--listen-client-urls http://127.0.0.1:2379 \
--advertise-client-urls http://127.0.0.1:2379 \
--listen-peer-urls http://127.0.0.1:12381 \
--initial-advertise-peer-urls http://127.0.0.1:12381 \
--initial-cluster-token etcd-cluster-1 --initial-cluster 'infra6=http://127.0.0.1:12381,infra5=http://127.0.0.1:22381,infra4=http://127.0.0.1:32381' --initial-cluster-state existing \
--enable-pprof > /home/chaochn/log/etcd/infra6.log 2>&1 &

```

## Testing cluster version downgrade from 3.5 to 3.4
```
rm -rf /home/chaochn/log/etcd/
mkdir -p /home/chaochn/log/etcd

# create 3.5 cluster
~/etcd/3.5.0-alpha.0/etcd --name infra1 \
--listen-client-urls http://127.0.0.1:2379 \
--advertise-client-urls http://127.0.0.1:2379 \
--listen-peer-urls http://127.0.0.1:12380 \
--initial-advertise-peer-urls http://127.0.0.1:12380 \
--initial-cluster-token etcd-cluster-1 --initial-cluster 'infra1=http://127.0.0.1:12380,infra2=http://127.0.0.1:22380,infra3=http://127.0.0.1:32380' --initial-cluster-state new \
--enable-pprof > /home/chaochn/log/etcd/infra1.log 2>&1 &

~/etcd/3.5.0-alpha.0/etcd --name infra2 \
--listen-client-urls http://127.0.0.1:22379 \
--advertise-client-urls http://127.0.0.1:22379 \
--listen-peer-urls http://127.0.0.1:22380 \
--initial-advertise-peer-urls http://127.0.0.1:22380 \
--initial-cluster-token etcd-cluster-1 --initial-cluster 'infra1=http://127.0.0.1:12380,infra2=http://127.0.0.1:22380,infra3=http://127.0.0.1:32380' --initial-cluster-state new \
--enable-pprof > /home/chaochn/log/etcd/infra2.log 2>&1 &

~/etcd/3.5.0-alpha.0/etcd --name infra3 \
--listen-client-urls http://127.0.0.1:32379 \
--advertise-client-urls http://127.0.0.1:32379 \
--listen-peer-urls http://127.0.0.1:32380 \
--initial-advertise-peer-urls http://127.0.0.1:32380 \
--initial-cluster-token etcd-cluster-1 --initial-cluster 'infra1=http://127.0.0.1:12380,infra2=http://127.0.0.1:22380,infra3=http://127.0.0.1:32380' --initial-cluster-state new \
--enable-pprof > /home/chaochn/log/etcd/infra3.log 2>&1 &

# downgrade to 3.4
## first
ETCDCTL_API=3 ~/etcd/release-3.4/etcdctl --endpoints http://127.0.0.1:2379,http://127.0.0.1:22379 member remove fd422379fda50e48
ETCDCTL_API=3 ~/etcd/release-3.4/etcdctl --endpoints http://127.0.0.1:2379,http://127.0.0.1:22379 member add infra4 --peer-urls=http://127.0.0.1:32381

~/etcd/release-3.4-with-rollback/etcd --name infra4 \
--listen-client-urls http://127.0.0.1:32379 \
--advertise-client-urls http://127.0.0.1:32379 \
--listen-peer-urls http://127.0.0.1:32381 \
--initial-advertise-peer-urls http://127.0.0.1:32381 \
--initial-cluster-token etcd-cluster-1 --initial-cluster 'infra1=http://127.0.0.1:12380,infra2=http://127.0.0.1:22380,infra4=http://127.0.0.1:32381' --initial-cluster-state existing \
--enable-pprof > /home/chaochn/log/etcd/infra4.log 2>&1 \
--unsafe-allow-cluster-version-downgrade=true &

## second
ETCDCTL_API=3 ~/etcd/release-3.4/etcdctl --endpoints http://127.0.0.1:2379,http://127.0.0.1:32379 member remove 91bc3c398fb3c146
ETCDCTL_API=3 ~/etcd/release-3.4/etcdctl --endpoints http://127.0.0.1:2379,http://127.0.0.1:32379 member add infra5 --peer-urls=http://127.0.0.1:22381

~/etcd/release-3.4-with-rollback/etcd --name infra5 \
--listen-client-urls http://127.0.0.1:22379 \
--advertise-client-urls http://127.0.0.1:22379 \
--listen-peer-urls http://127.0.0.1:22381 \
--initial-advertise-peer-urls http://127.0.0.1:22381 \
--initial-cluster-token etcd-cluster-1 --initial-cluster 'infra1=http://127.0.0.1:12380,infra5=http://127.0.0.1:22381,infra4=http://127.0.0.1:32381' --initial-cluster-state existing \
--enable-pprof > /home/chaochn/log/etcd/infra5.log 2>&1 \
--unsafe-allow-cluster-version-downgrade=true &

## third
ETCDCTL_API=3 ~/etcd/release-3.4/etcdctl --endpoints http://127.0.0.1:22379,http://127.0.0.1:32379 member remove 8211f1d0f64f3269
ETCDCTL_API=3 ~/etcd/release-3.4/etcdctl --endpoints http://127.0.0.1:22379,http://127.0.0.1:32379 member add infra6 --peer-urls=http://127.0.0.1:12381

~/etcd/release-3.4-with-rollback/etcd --name infra6 \
--listen-client-urls http://127.0.0.1:2379 \
--advertise-client-urls http://127.0.0.1:2379 \
--listen-peer-urls http://127.0.0.1:12381 \
--initial-advertise-peer-urls http://127.0.0.1:12381 \
--initial-cluster-token etcd-cluster-1 --initial-cluster 'infra6=http://127.0.0.1:12381,infra5=http://127.0.0.1:22381,infra4=http://127.0.0.1:32381' --initial-cluster-state existing \
--enable-pprof > /home/chaochn/log/etcd/infra6.log 2>&1 \
--unsafe-allow-cluster-version-downgrade=true &

# clean up all the process and logs
sudo ps -aef | grep etcd | grep -v grep | awk '{print $2}' | xargs sudo kill
rm -rf ~/infra*
rm -rf /home/chaochn/log/etcd/*.log
```

### CODE REVIEW

File: server/etcdserver/server.go [hunk 1]
```diff
@@ -2484,6 +2485,46 @@ func (s *EtcdServer) updateClusterVersion(ver string) {
 		)
 	}
```
Comment (gyuho) [inline server/etcdserver/server.go:2487]: Might as well rename this method to `updateClusterVersionV2`, to be clear?

Comment (gyuho) [reply server/etcdserver/server.go:2487]: Can we also update the logging

```
"updating cluster version using v2 API
```

Comment (gyuho) [reply server/etcdserver/server.go:2487]:
```
"setting up initial cluster version using v2 API"
```

File: server/etcdserver/server.go [hunk 2]
```diff
@@ -2484,6 +2485,46 @@ func (s *EtcdServer) updateClusterVersion(ver string) {
...
+		lg.Warn("failed to update cluster version", zap.Error(err))
+	}
+}
+
+func (s *EtcdServer) updateClusterVersionV3(ver string) {
+	lg := s.Logger()
+
+	if s.cluster.Version() == nil {
+		lg.Info(
+			"setting up initial cluster version",
```
Comment (gyuho) [inline server/etcdserver/server.go:2517]: `... using v3 API`

File: server/etcdserver/server.go [hunk 3]
```diff
@@ -2484,6 +2485,46 @@ func (s *EtcdServer) updateClusterVersion(ver string) {
...
+			zap.String("cluster-version", version.Cluster(ver)),
+		)
+	} else {
+		lg.Info(
+			"updating cluster version",
```
Comment (gyuho) [inline server/etcdserver/server.go:2522]: `... using v3 API`

File: server/etcdserver/server.go (hunk 1 above)
Comment (chaochn47) [reply server/etcdserver/server.go:2487]: Added in the next revision as your comments. PTAL @gyuho

**Comment by ptabor** [comment]
I wonder how apply V2 is working. This lines worry me: 

https://github.com/etcd-io/etcd/blob/e73facb7e206698c1fd9650178e4f2ac1e42ff66/server/etcdserver/apply_v2.go#L95-L99

looks like neither write to v2 store nor v3 store, or I'm missing something. 
Where the data are stored is important in context of: 

https://github.com/etcd-io/etcd/blob/e73facb7e206698c1fd9650178e4f2ac1e42ff66/server/etcdserver/api/membership/cluster.go#L256-L262

**Comment by chaochn47** [comment]
Thought contributor of https://github.com/etcd-io/etcd/pull/11427/files?file-filters%5B%5D=.go#diff-2a81e175edbcc322a52051676dc08cb497741e608dbefa4ac67d8e042cd902ccL94-L99 removed the v2 apply to store cluster version and added to v3 api. 

I just revert back her change.

**Comment by gyuho** [comment]
@ptabor 

> I wonder how apply V2 is working. This lines worry me:

Looks like we just return empty response, because there's no really consumer of this response given it's an internal API.

This change looks good to me. Any other concern?

**Comment by ptabor** [comment]
> @ptabor
> 
> > I wonder how apply V2 is working. This lines worry me:
> 
> Looks like we just return empty response, because there's no really consumer of this response given it's an internal API.
> 
> This change looks good to me. Any other concern?

The actual storeV2 set happens in line 100. If we return in line 98, how do we store the value ?

https://github.com/etcd-io/etcd/blob/e73facb7e206698c1fd9650178e4f2ac1e42ff66/server/etcdserver/apply_v2.go#L100

**Comment by gyuho** [comment]
@ptabor In release 3.4, we don't call `a.store.Create` either. We just return success without persisting it.

> The actual storeV2 set happens in line 100. If we return in line 98, how do we store the value ?

I believe that was the motivation we are migrating to v3 API for everything, right? v2 cluster state as it is now is not persistent. Unfortunately, those migration effort made some breaking changes.

**Review by ptabor — APPROVED** [review]

**Comment by ptabor** [comment]
Thanks. 

I missed that: 

```
a.cluster.SetVersion(semver.Must(semver.NewVersion(r.Val)), api.UpdateCapability, membership.ApplyBoth)
``` was added back.

**Comment by zaisongz** [comment]
How to enable the downgrade by API, could you please share an example?@chaochn47

**Comment by chaochn47** [comment]
@zaisongz I was patching this PR #13022 to local etcd code base to verify downgrade and upgrade correctness. 

This is the new flag `--unsafe-allow-cluster-version-downgrade=true` I introduced. 

The official downgrade support should be ready by 3.6 based on #13168
