### PR TITLE
robustness: add MemberID to porcupine visualization output

### LINKED ISSUE #19029: Add more custom annotations to robustness visualizations
### What would you like to be added?

With v1.0.0 porcupine now support custom annotations in visualization. https://github.com/anishathalye/porcupine?tab=readme-ov-file#visualizing-histories

Would be great to add:
* Failed requests that were not part of linearization
* When and what failpoint was injected
* Any useful information about servers 

Previous attemp: https://github.com/etcd-io/etcd/pull/17779

cc @MadhavJivrajani @fuweid @siyuanfoundation 

### Why is this needed?

Adds more context to history visualization

### PR DESCRIPTION
**Pull request by henrybear327**
Include the MemberID (which etcd cluster member processed the request) in the describe output for porcupine visualization when it is set.

Fixes #19029

Before:
Screenshot 2026-02-27 at 6 05 52 PM

After:
Screenshot 2026-02-27 at 6 05 58 PM

### CODE REVIEW

File: tests/robustness/model/describe_test.go [hunk 1]
```diff
@@ -169,6 +169,21 @@ func TestModelDescribe(t *testing.T) {
 			resp:           rangeResponse(nil, 0, 16),
 			expectDescribe: `range("key16".."key16b", limit=2) -> [], count: 0, rev: 16`,
 		},
+		{
+			req:            putRequest("key17", "17"),
+			resp:           putResponseWithMemberID(17, 1),
+			expectDescribe: `put("key17", "17") -> ok, rev: 17, member: 1`,
```
Comment (serathius) [inline tests/robustness/model/describe_test.go]: I don't want memberID be part of description of request, description should short and to the point. Only information needed to confirm request was correctly handled. Metadata information like which member handled it is not needed for that. Didn't we upstreamed Describing metadata just for this reason?

Comment (henrybear327) [reply tests/robustness/model/describe_test.go]: Yes, metadata code change was upstreamed already and the dependency was also bumped. 

Based on the meeting yesterday, seeing how you are navigating around different systems / logs and correlate data, I thought the ability to copy / search for the memberID directly in the browser is critical, so I put it in the "blue bar" which can do both. 

I will make adjustment to display it in the metadata, and sorry for not checking in with you on this beforehand.

**Review by serathius — APPROVED** [review]

**Comment by serathius** [comment]
Please fix

```
../tests/robustness/model/describe.go:24:1: File is not properly formatted (gci)
	clientv3 "go.etcd.io/etcd/client/v3"
^
```

**Comment by henrybear327** [comment]
The failing unit tests are now all addressed.
