### PR TITLE
fix(server/etcdserver/api/v3compactor): fix flaky TestPeriodicHourly and others with Retry Mechanism

### LINKED ISSUE #19499: Flaky `go.etcd.io/etcd/server/v3/etcdserver/api/v3compactor: TestPeriodicHourly `
### Which Github Action / Prow Jobs are flaking?

https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/etcd-io_etcd/19426/pull-etcd-coverage-report/1895067242123497472

```

go.etcd.io/etcd/server/v3/etcdserver/api/v3compactor: TestPeriodicHourly expand_less | 1s
-- | --
{Failed  === RUN   TestPeriodicHourly     logger.go:146: 2025-02-27T11:08:18.530Z	INFO	starting auto periodic compaction	{"revision": 1, "compact-period": "2h0m0s"}     logger.go:146: 2025-02-27T11:08:18.530Z	INFO	completed auto periodic compaction	{"revision": 1, "compact-period": "2h0m0s", "took": "0s"}     logger.go:146: 2025-02-27T11:08:18.850Z	INFO	starting auto periodic compaction	{"revision": 10, "compact-period": "2h0m0s"}     logger.go:146: 2025-02-27T11:08:18.851Z	INFO	completed auto periodic compaction	{"revision": 10, "compact-period": "2h0m0s", "took": "0s"}     logger.go:146: 2025-02-27T11:08:19.032Z	INFO	starting auto periodic compaction	{"revision": 20, "compact-period": "2h0m0s"}     logger.go:146: 2025-02-27T11:08:19.032Z	INFO	completed auto periodic compaction	{"revision": 20, "compact-period": "2h0m0s", "took": "0s"}     logger.go:146: 2025-02-27T11:08:19.281Z	INFO	starting auto periodic compaction	{"revision": 30, "compact-period": "2h0m0s"}     periodic_test.go:72: len(actions) = 0, expected >= 1 --- FAIL: TestPeriodicHourly (1.49s) }


```

FYI. Previously I raised a similar issue https://github.com/etcd-io/etcd/issues/17054, which was resolved in https://github.com/etcd-io/etcd/pull/18608. It seems the fix still has flaw.

### Which tests are flaking?

.

### Github Action / Prow Job link

_No response_

### Reason for failure (if possible)

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by amosehiguese**
This commit fixes the flaky TestPeriodicHourly test (issue #19499) and similar test cases by introducing an exponential backoff retry mechanism for waiting on actions rather than relying on a fixed timeout.

The root cause of the flakiness was timing inconsistencies in CI environments, where actions sometimes take slightly longer than the expected 10ms timeout set when creating a compactable object.

The new waitWithRetry function attempts to get the expected actions multiple times with exponentially increasing wait periods (10ms, 20ms, 40ms, etc.) before ultimately failing.

The solution was verified by reproducing the issue with an artificial delay and stress-testing the fix with 1000 consecutive runs.

The following test functions were updated to use the new retry mechanism:
- TestPeriodicHourly
- TestPeriodicMinutes
- TestPeriodicPause
- TestPeriodicSkipRevNotChange

Fixes #19499

test

Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

File: server/etcdserver/api/v3compactor/periodic_test.go [hunk 1]
```diff
@@ -244,3 +245,23 @@ func waitOneAction(t *testing.T, r testutil.Recorder) {
...
+
+	expectedActions, maxRetries := 1, 5
+	for retry := 0; retry < maxRetries; retry++ {
+		actions, lastErr = compactable.Wait(expectedActions)
+		if lastErr == nil || len(actions) >= expectedActions {
+			return actions, nil
+		}
+		// Exponential backoff
+		backoffTime := time.Duration(10*(1<<retry)) * time.Millisecond
+		t.Logf("Retry %d: waiting %v before next attempt (last error: %v)", retry+1, backoffTime, lastErr)
```
Comment (ahrtr) [inline server/etcdserver/api/v3compactor/periodic_test.go:263]: nit: %s is more human readable
```suggestion
		t.Logf("Retry %d: waiting %s before next attempt (last error: %v)", retry+1, backoffTime, lastErr)
```

**Review by ahrtr — APPROVED** [review]
Thanks

cc @fuweid

**Comment by amosehiguese** [comment]
You are welcome @ahrtr and thanks for the correction. I guess I can move on to other issues. 😊
