### PR TITLE
pkg, clientv3: etcdctl can snaprestore when data-dir exits but empty

### LINKED ISSUE #11618: get dir exits when snapshot restore
**Problems**
when I use `etcdctl snapshot restore --data-dir=/var/lib/etcd xxx`, I get `Error:  data-dir "/var/lib/etcd" exists`, (There is nothing in the data-dir /var/lib/etcd), is this a bug?

I can't delete dir "/var/lib/etcd", because I mounted a ssd on the dir.

**etcd version**
```
etcd Version: 3.2.26
Git SHA: 06cec4091
Go Version: go1.8.7
Go OS/Arch: linux/amd64
```

### PR DESCRIPTION
**Pull request by zhanw15**
Fix #11618

### CODE REVIEW

**Comment by zhanw15** [comment]
I think it will work when data-dir exists but empty @spzala @gyuho

File: clientv3/snapshot/v3_snapshot.go [hunk 1]
```diff
@@ -267,8 +267,8 @@ func (s *v3Manager) Restore(cfg RestoreConfig) error {
 	if dataDir == "" {
 		dataDir = cfg.Name + ".etcd"
 	}
-	if fileutil.Exist(dataDir) {
-		return fmt.Errorf("data-dir %q exists", dataDir)
+	if fileutil.Exist(dataDir) && !fileutil.Empty(dataDir) {
+		return fmt.Errorf("data-dir %q not empty", dataDir)
```
Comment (spzala) [inline clientv3/snapshot/v3_snapshot.go]: @zhanw15 thanks for the PR! Please wait on this because a separate discussion is going on in handling existing files. I will be updating on it to you here. Also, if we decide to go further, a small suggestion on modifying the error message to something like `data-dir %q not empty or could not be read` considering any read error in the `Empty` function? Thanks again!

Comment (zhanw15) [reply clientv3/snapshot/v3_snapshot.go]: Yes, I think you are right, now I change the logs info.

**Comment by xiang90** [comment]
LGTM
